### ISSUE TITLE
"Attempt to present X on Y whose view is not in the window hierarchy!" using authorize_url_handler

### ISSUE THREAD

**Issue by DennisDreissen** [OAuthSwift/OAuthSwift#154]
I'm trying to let my users authenticate from within my application, so they don't need to be redirected to safari. I have implemented the WebViewController and set the authorize_url_handler to WebViewController. But I'm getting the following warning:

Warning: Attempt to present <.WebViewController: 0x7967b7e0> on <.LoadingViewController: 0x7a029e60> whose view is not in the window hierarchy!

Am I missing something here? I can't seem to find any information about it anywhere, so that's why I'm asking here.

**Comment by phimage** [comment]
ios?
without your code difficult to give an exact answer but the error seems clear and just do a google search on "whose view is not in the window hierarchy"

did you addChildViewController ?
If you present a view not using as parent the root, you must add the WebViewController as child controller of the parent controller view where you did presentXXX....

**Comment by DennisDreissen** [comment]
WebViewController: http://pastebin.com/GdA8iFFE

```
func authenticateUser() {
    let theView = WebViewController()
    OAuth.authorize_url_handler = theView
    OAuth.authorizeWithCallbackURL( NSURL(string: "MyApp://oauth")!, success: {
        credential, response in
        print("success")
        }, failure: { error in
            print(error)
    })
}
```

I have tried adding self.addChildViewController(theView) but that crashes the application.

**Comment by DennisDreissen** [comment]
Not getting the SFSafariViewController to work either.

**Comment by phimage** [comment]
ok you copy demo code using the `OAuthWebViewController`

and the code used to present is :
```swift
 UIApplication.sharedApplication().keyWindow?.rootViewController?.presentViewController(
theWebViewController, animated: true, completion: nil)
```

I will test the demo app just in case

maybe it's because you are not displaying currently the  `UIApplication.sharedApplication().keyWindow?.rootViewController`, but another when doing the job
*I will add a function to override to choose the good controller, the one that is displayed maybe*

or have you a `UINavigationController`? a Storyboard?

or you call `authenticateUser` when you have not finished to load a view (for instance in a viewDidLoad stack)

**Comment by DennisDreissen** [comment]
I'm calling the authenticateUser after the user presses a button, so the view has loaded. When the app loads it loads a view calling LoadingViewController, if the user is not logged in it shows the LoginViewController, which contains the button and the authenticateUser  method.


Not sure what to do now?

**Comment by phimage** [comment]
try in   override func handle(url: NSURL) {
do not call super.handle(url:)

instead do some code to present the view from your LoadingViewController 
loadingViewConroller.presentViewController(self, animated: true, completion: nil)

you can add this LoadingViewController into your WebViewController as attribute when you creating it (passing in init for instance)

**Comment by DennisDreissen** [comment]
Alright, got it working now. Would be awesome to be able to override the controller, so I can pass the LoginViewController to the handle method.

Thanks for helping! :+1:

**Comment by phimage** [comment]
yes I will add that to OAuthWebViewController
and keep the issue open until that

**Comment by DennisDreissen** [comment]
Any idea how I can implement the webView into a custom viewController?

**Comment by phimage** [comment]
maybe I don't understand the question.
You put a UIWebView into your custom WebViewController (by coping demo code) that's the way to do it.

PS: there is also [![Join the chat at https://gitter.im/dongri/OAuthSwift](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/dongri/OAuthSwift?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) to ask little question

**Comment by driver733** [comment]
If anyone is interested, here is how I managed to solve the discussed problem.
 ```
public func handle(url: NSURL){
        #if os(iOS)
           var topController = UIApplication.sharedApplication().keyWindow?.rootViewController      
           while ((topController?.presentedViewController) != nil) {
           	topController = topController?.presentedViewController
           }
          topController?.presentViewController(self, animated: true, completion: nil)
       ...
 ````

**Comment by phimage** [comment]
97d692c198918a14483dca7460ec193957662641 @driver733 I take your code but make a recursive one in `UIViewController`/`UIApplication` extension 
I make special case for `UINavigationController` and `UITabViewController` as I read on internet but maybe I do wrong by doing this

@driver733 @DennisDreissen feedback is welcome because I have no app with a controller hierarchy to test (demo app have only an `UINavigationController` as root)
