### ISSUE TITLE
Can you keep the entire HTTP response in the postOAuthRequestTokenWithCallbackURL?

### ISSUE THREAD

**Issue by SokichiFujita** [OAuthSwift/OAuthSwift#155]
I would like to use the entire HTTP response of access token endpoint in the `authorizeWithCallbackURL` of `OAuth1Swift`. But `postOAuthRequestTokenWithCallbackURL` drops a lot of information from it.

In spite of Twitter returns `user_id` and `screen_name` with `access_token` and `access_token_secret`,  `postOAuthRequestTokenWithCallbackURL` method only pass `access_token` and `access_token_secret`. Another information is dropped. I think `user_id` or `screen_name` are also important for apps. 

I want to use following success handler:

```
public typealias TokenSuccessHandler = (credential: OAuthSwiftCredential, data: NSData, response: NSURLResponse) -> Void
```

Current success handler:

```
public typealias TokenSuccessHandler = (credential: OAuthSwiftCredential, response: NSURLResponse) -> Void
```

How do you think about this idea?

**Comment by phimage** [comment]
Did you look master branch head code in OAuthSwift.swift?
Someone make a PR to add to TokenSuccessHandler 'paramètres'
Maybe in this dictionnary there is the information you looking for

**Comment by SokichiFujita** [comment]
Thank you! #152 fixed this issue, as you mentioned.
`parameters` has the information that I need.

**Comment by SokichiFujita** [comment]
Thank you! #152 fixed this issue, as you mentioned.
parameters has the information that I need.
