### ISSUE TITLE
How to refresh token

### ISSUE THREAD

**Issue by czzhengkw** [OAuthSwift/OAuthSwift#162]
I have success to get access_token
But the token has an expire time, I have to refresh token in 10 minutes.

**Comment by phimage** [comment]
oauth provider?
oauth version?


# Refresh token RFC

http://tools.ietf.org/html/rfc6749#section-1.5
http://tools.ietf.org/html/rfc6749#section-6
http://tools.ietf.org/html/rfc6749#section-10.4

make a post described by your oauth provider
POST xxx/refresh?refresh_token=XXX&client_id=YYY&grant_type=refresh_token&client_secret ...

expiration currently must be handled by you in failure callback, and reconnect then
https://github.com/OAuthSwift/OAuthSwift/wiki/OAuth-2.0-Token-Expiration

**Comment by fabiomassimo** [comment]
Is it there a reason why `OAtuhSwift` does not implement the refresh mechanism but itself?
I believe a good start would be to add `expires_in` and `refresh_token` properties in the `OAuthSwiftCredential` object such that those can be exposed to the client that might need to kick off a "token refresh" request.

I'd like to make a PR about this but I'm not sure if it is against the `OAuthSwift`'s roadmap.

Thanks.

**Comment by phimage** [comment]
@fabiomassimo no reason I think 
(I use only oauth1 so I did not investigate this topic, just make some google and rfc search to provide some answer)
every PR is welcomed about this subject
