### ISSUE TITLE
Example usage for OAuthWebViewController

### ISSUE THREAD

**Issue by aozbayra** [OAuthSwift/OAuthSwift#167]
Like everyone else I am trying to open the sign in process through a web view instead of Safari. This is the piece of code I have:

        if #available(iOS 9.0, *) {
            oauthswift.authorize_url_handler = SafariURLHandler(viewController: self)
        }
        else {
            let webView = OAuthWebViewController()
            oauthswift.authorize_url_handler = webView
        }

SafariURLHandler works fine but the OAuthWebViewController does not work I need to present the webvViewController both from the root view controller and some other view controller. 

What is the proper implementation of OAuthWebViewController in my case? Thank you in advance.

**Comment by phimage** [comment]
version used?
message, log, error ? maybe #154

Did you try breakpoint into OAuthWebViewController, doHandle method ?

**Comment by aozbayra** [comment]
Ok yeah I know about that recursive code I used it before. I have the above lines on two places on of them being the root view controller. When I try it on the root view controller I am getting the black screen so maybe I am not adding the view to the hierarchy but I thought that was being done inside doHandle on this line:
                UIApplication.sharedApplication().keyWindow?.rootViewController?.presentViewController(
                    self, animated: true, completion: nil)
I pulled the code through cocoaPods and oauthswift.version.shortVersion gives me 2.0. What else would you recommend me to add into this piece of code?
    if #available(iOS 9.0, *) {
        oauthswift.authorize_url_handler = SafariURLHandler(viewController: self)
    }
    else {
        let webView = OAuthWebViewController()
        oauthswift.authorize_url_handler = webView
    }

**Comment by phimage** [comment]
There is no version 2.0, see https://github.com/OAuthSwift/OAuthSwift/releases
If you use cocoapod there is a PodFile.lock near PodFile with version used

Please update because that following code is old, previous 0.5.0
`UIApplication.sharedApplication().keyWindow?.rootViewController?.presentViewController(`

**Comment by aozbayra** [comment]
As per your advice, I used my own class like in the demo and I have updated my version to 0.5. It is working fine right now, thank you for your help.
