### ISSUE TITLE
"Could not get Access Token" error when one of the values in response is not a string.

### ISSUE THREAD

**Issue by valentinvarbanov** [OAuthSwift/OAuthSwift#171]
The OAuth2Swift class interprets wrongly the response from HTTP request in method `postOAuthAccessTokenWithRequestTokenByCode`("OAuth2Swift.swift") when one of the response values is not of type String. In this case on line 123 in file "OAuth2Swift.swift" the if statement returns false even that it should cast successfully the oath token, and the authentication process returns an error at the end.(I had this problem with LinkedIn OAuth2 authentication. The value of another key-value pair was with types `[String: Int]`.)
My solution is inserting another case(line 125) to try to convert non-string object to string like that:
```swift
else if var jsonDico = responseJSON as? [String:AnyObject] { 
                for(k, v) in jsonDico {
                    if !(v is String) {
                        jsonDico[k] = "\(v)"
                    }
                }
                responseParameters = jsonDico as! [String:String]
            }
```

**Comment by phimage** [comment]
did you experiment the issue with current code? (because I have already fixed that in #159)
watch your PR diff and see that your code will never be called, the previous if cast with same dictionary type, no more String:String
