### ISSUE TITLE
Nothing passed back on redirect

### ISSUE THREAD

**Issue by amruss** [OAuthSwift/OAuthSwift#175]
Sorry ahead of time I'm new to IOS development. 

Trying to connect to the Fitbit API and it authenticates fine but when it redirects back to my app nothing is passed back, or rather the code inside the closure never executes. Anyone know what I'm doing wrong?

oauthswift.authorizeWithCallbackURL( NSURL(string: "FitAlarmHelper://")!, scope: "profile", state: state, success: {
            credential, response, parameters in
            self.showTokenAlert(serviceParameters["name"], credential: credential)
            print("done")
            self.testFitbit2(oauthswift)
            }, failure: { error in
                print("error")
                print(error.localizedDescription)
        })

**Comment by phimage** [comment]
Maybe the callback URL need a path to work
FitAlarmHelper://oauth

**Comment by amruss** [comment]
When I change the callback url to FitAlarmHelper://oauth or anything else I get this

<img width="369" alt="screen shot 2016-01-21 at 9 31 24 pm" src="https://cloud.githubusercontent.com/assets/13264141/12503221/09fccd16-c087-11e5-924a-047a525e8288.png">

Done Both of those:
<img width="517" alt="screen shot 2016-01-21 at 9 33 43 pm" src="https://cloud.githubusercontent.com/assets/13264141/12503222/0f724e9c-c087-11e5-9516-5b930e3a2c17.png">

<img width="382" alt="screen shot 2016-01-21 at 9 36 06 pm" src="https://cloud.githubusercontent.com/assets/13264141/12503225/1419a1f2-c087-11e5-80d1-46bd71c1b0f7.png">

**Comment by phimage** [comment]
Did you define an application into https://dev.fitbit.com/apps/
and defined the callback url white list

**Comment by amruss** [comment]
Yes I did! 
<img width="385" alt="screen shot 2016-01-21 at 9 47 21 pm" src="https://cloud.githubusercontent.com/assets/13264141/12503374/9e94c68a-c088-11e5-8565-e4c02b475a7b.png">

**Comment by phimage** [comment]
Set  FitAlarmHelper://oauth if you use  FitAlarmHelper://oauth
Set  FitAlarmHelper://oauth-callback is you use  FitAlarmHelper://oauth-allback

**Comment by amruss** [comment]
Hmm I did that, and i don't get an error when it redirects back to my app. But, it still doesn't execute the code in the closure. It acts just like when I used FitAlarmHelper://

**Comment by phimage** [comment]
Have you see `OAuthSwift.handleOpenURL` called? using a breakpoint into `func application(application: UIApplication!, openURL url: NSURL!, sourceApplication: String!, annotation: AnyObject!)`

Is it your code ?
https://cloud.githubusercontent.com/assets/13264141/12503225/1419a1f2-c087-11e5-80d1-46bd71c1b0f7.png 
This code is for FitAlarmHelper://oauth-callback only

**Comment by amruss** [comment]
Okay it doesn't look like handleOpenURL is ever called
I took away the if statement to see if it was blocking it but it still wasn't called. Any idea what I'm doing wrong?

**Comment by phimage** [comment]
hummm

Did you use a `authorize_url_handler` ? if you make iOS9 dev you can try the `SFSafariViewController`

--
I just updated readme ae4c47d4a742b7b10cdbdec1e8766fbd60e87514  `application(application: ` method signature, without any `!` because have a wrong method signature by copying readme could be the issue


--

Maybe iOS9 must also declare URL scheme into LSApplicationQueriesSchemes, I expect not...
#### Declare targeted applications URL schemes in iOS9
In iOS 9 you must whitelist any URL schemes your app wants to query in Info.plist under the *LSApplicationQueriesSchemes* key (an array of strings)
![xcode-white-list](http://useyourloaf.com/assets/images/2015/2015-09-06-001.png)

**Comment by amruss** [comment]
Thank you! I changed my AppDelegate and it fixed the issue. Appreciate the help!
