### ISSUE TITLE
Scope with space symbol doesn't create NSURL

### ISSUE THREAD

**Issue by leo150** [OAuthSwift/OAuthSwift#176]
Let's say we need to login into fitbit account with `profile` and `weight` scopes. From docs `scope` field is: 
> space-delimited list of the permissions you are requesting

But when we call `authorizeWithCallbackURL` with scope string "profile weight" than this part of code silently skips our url:
`if let queryURL = NSURL(string: urlString) {
           self.authorize_url_handler.handle(queryURL)
        }`
It would be nice to add some log message or replace all space delimiters in `urlString`

**Comment by leo150** [comment]
Duplicate of #156

**Comment by phimage** [comment]
I thinks is not a duplucate

I will call failure callback in this case 
Scope must be encoded here
workaround for now, html encode yourself the scope, I think replace space with %20

**Comment by leo150** [comment]
@phimage, thanks for support!

Small sample of replacement if anyone needs: 
```
	if let utf8String = urlString
		.stringByAddingPercentEncodingWithAllowedCharacters(
		NSCharacterSet.URLQueryAllowedCharacterSet()) {
			if let queryURL = NSURL(string: utf8String) {
				self.authorize_url_handler.handle(queryURL)
			}
		}
```

**Comment by phimage** [comment]
I just encode the query, not the full URL because of `NSCharacterSet.URLQueryAllowedCharacterSet()`

Also if there is problem to create te URL, failure callback will be called
