### ISSUE TITLE
Retrieving Instagram user data along side access token

### ISSUE THREAD

**Issue by cameronbarker** [OAuthSwift/OAuthSwift#179]
I see from Instagram that when you authenticate it returns the information below.  Is there a way to get the user data along side the access token initially using OAuthSwift?

```json
{
    "access_token": "fb2e77d.47a0479900504cb3ab4a1f626d174d2d",
    "user": {
        "id": "1574083",
        "username": "snoopdogg",
        "full_name": "Snoop Dogg",
        "profile_picture": "..."
    }
}
```

**Comment by phimage** [comment]
success callback have third parameters, the last one 'parameters' I think contains the data you want

**Comment by cameronbarker** [comment]
@phimage Took a look and only found the "access_token" and "state" keys in the returned "parameters" dictionary

**Comment by phimage** [comment]
To get this information you must not use the "token" type authentification but the "code"

```swift
accessTokenUrl: "https://api.instagram.com/oauth/access_token",
responseType:   "code"
``` 

you will receive in the response parameters a json string into "user" index
decode it with `NSJSONSerialization` or any third party json framework
