### ISSUE TITLE
State not being checked after response

### ISSUE THREAD

**Issue by mats-claassen** [OAuthSwift/OAuthSwift#182]
I am trying to connect to Linkedin. After requesting authorization they return a `code` and a `state`. The `code` is used to get the access token but it is not being checked (or at least I did not find it) if the `state` matches the one send in the first request.

**Comment by phimage** [comment]
I think you are right (and  must be check to prevent CSRF)

**Comment by phimage** [comment]
added a check about state value when receiving a `code`
don't know if all case is supported

add a var `allowMissingStateCheck` to remove this check in case of some problem in provider oauth protocol
