### ISSUE TITLE
No callback when calling authorizeWithCallbackURL

### ISSUE THREAD

**Issue by mohwaili** [OAuthSwift/OAuthSwift#184]
On iOS 9 I get the callback from this function: `authorizeWithCallbackURL`
On iOS 8 I don't get anything back, no success nor error. 

version oauthswift: 0.5.0

```
let oauthswift = OAuth1Swift(
            consumerKey: Router.consumerKey,
            consumerSecret: Router.consumerSecret,
            requestTokenUrl: Constants.URLs.RequestTokenURL,
            authorizeUrl: Constants.URLs.AuthorizeURL,
            accessTokenUrl: Constants.URLs.AccessTokenURL)
oauthswift.authorize_url_handler = WebViewController()
        
// RequestTokenURL = "https://publicapi.avans.nl/oauth/request_token"
// AuthorizeURL = "https://publicapi.avans.nl/oauth/login.php"
// AccessTokenURL = "https://publicapi.avans.nl/oauth/access_token"
// RedirectURL = "oauth-swift://oauth-callback/avans?dummy=1"
oauthswift.authorizeWithCallbackURL(NSURL(string: Constants.URLs.RedirectURL)!, success: { (credential, response, parameters) -> Void in
    print(credential.oauth_token)
    print(credential.oauth_token_secret)
}) { (error) -> Void in
                
}
```

**Comment by phimage** [comment]
please read contributing guide for issue/bug https://github.com/OAuthSwift/OAuthSwift/blob/master/CONTRIBUTING.md

not working is not a good description for a bug

provide some code, version of oauthswift used, the authorization url handler used, provider/website to auth...

**Comment by mohwaili** [comment]
Sorry for not being very descriptive, I've updated the question.

**Comment by mohwaili** [comment]
I've found the solution for this issue: 

on iOS 9 this delegate function works in AppDelegate:  func application(app: UIApplication, openURL url: NSURL, options: [String : AnyObject]) -> Bool 

on iOS 8 I had to use this function: func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject) -> Bool

I think this issue can be closed.
