### ISSUE TITLE
Support for Microsoft Share point cloud, OneDrive and Box.net

### ISSUE THREAD

**Issue by pushanGlobant** [OAuthSwift/OAuthSwift#185]
Hi,
Can you clarify that OAuthSwift works for following cloud providers Microsoft SharePoint, OneDrive and Box.net. 

Thanks And Regards,
Pushan

**Comment by phimage** [comment]
No we cannot work for you... All tested providers are listed... But if provider follow oauth...

Find provider doc and try yourself (you can add provider into demo app to test)
or ask the question in stackoverflow(but I think you will not have response)

**Comment by pushanGlobant** [comment]
thanks
