### ISSUE TITLE
logged or not? 

### ISSUE THREAD

**Issue by sourov2008** [OAuthSwift/OAuthSwift#189]
`@IBAction func stratAuth(sender: AnyObject) {
         let oauthswift = OAuth2Swift(
            consumerKey:    "xxx",
            consumerSecret: "xxx",
            authorizeUrl:   "https://www.fitbit.com/oauth2/authorize",
            responseType:   "token"
        )
        
        oauthswift.authorizeWithCallbackURL(
            NSURL(string: "HealthAnother://oauth-callback/fitbit")!,
            scope: "activity+profile+location+sleep+weight", state:"Fitbit",
            success: { credential, response, parameters in
                
                print(credential.oauth_token)
                self.testFitbit2(oauthswift)
                
            },
            failure: { error in
                print(error.localizedDescription)
            }
        )
        
    }
   
    func testFitbit2(oauthswift: OAuth2Swift) {
        oauthswift.client.get("https://api.fitbit.com/1/user/227G3S/activities/tracker/steps/date/2016-02-23.json", parameters: [:],
            success: {
                data, response in
                let jsonDict: AnyObject! = try? NSJSONSerialization.JSONObjectWithData(data, options: [])
                print(jsonDict)
            }, failure: { error in
                print(error.localizedDescription)
        })
    }
`
The scenario is i want to set a button and the text of the button will change depends on user Authenticated or Not .
If someone already authenticated button text will set Disconnect/Logged out Or Authenticate Here .
How can i checked is user already Authenticated or Not .  
- **OS targeted (with version): ios 9.2
- **OAuth provider: Fitbit 
- **OAuthSwift version:  Current Version

**Comment by phimage** [comment]
:warning: don't share in github your consumer key and secret (secret means secret), I edit your message...

A user is not disconnected or logger... You have a token, valid or not
So store the token  in `success` callback, you are logged
no token you are not logger
then to know if token always valid you must do an api request and see if success or failed

**Comment by sourov2008** [comment]
Thank You :)
How Long token will alive ?

**Comment by phimage** [comment]
depending on the provider, here fitbit, and sometimes when requesting authorization you can specify the token duration

in `success` there is `parameters` and sometimes expiration time is defined in this dictionary

but token could also be invalidated, exception must be handled
more info here https://github.com/OAuthSwift/OAuthSwift/wiki/OAuth-2.0-Token-Expiration
