### ISSUE TITLE
SharedApplication is unavailable (UIApplication+OAuthSwift.swift)

### ISSUE THREAD

**Issue by Mauricevb** [OAuthSwift/OAuthSwift#193]
I get the following compiler-error:
```
UIApplication+OAuthSwift.swift:14:34: 'sharedApplication()' is unavailable: Use view controller based solutions where appropriate instead.
```

It refers to the following code from OAuthSwift:
```
static var topViewController: UIViewController? {
    return UIApplication.sharedApplication().topViewController
}
```

Of course I set `OAUTH_APP_EXTENSIONS`..

Everywhere else in the code, OAuthSwift uses:
```
#if !OAUTH_APP_EXTENSIONS
    UIApplication.sharedApplication()......
#endif
```
Is there a reason this if-statement is not used inside `UIApplication+OAuthSwift.swift`?

(Newest OAuthSwift version, installed with CocoaPods, but I also tried installing manually)

- **OS targeted (with version):** iOS 9.0
- **OAuth provider:** -
- **OAuthSwift version:**  0.5.1

**Comment by phimage** [comment]
(issue template?...)

so no any reason, code has been extracted one day, and will be never be called in extensions but in fact code doesn't compile

`UIApplication+OAuthSwift.swift`  must be excluded for extension
or 
```swift
 #if !OAUTH_APP_EXTENSIONS
// all the code
#endif
```
must be added to this file

**Comment by Mauricevb** [comment]
How can I do this? I installed with CocoaPods so I can't exclude a file or change code?

**Comment by phimage** [comment]
many ways

1/ edit the code temporary, but each pod update will erase the code change
2/ clone repository, edit, change your podfile to specify the path of the repository `, 'path' => '../the/local/path/where/OAuthSwift/is/OAuthSwift.podspec'`
3/ the best: fork , clone your fork. edit the code, commit the fix with a clear message
- change your podfile to specify your fork using  `, :git => 'url of your git' `  , until new OAuthSwift release
- then you can also make a pull request to our repository
