### ISSUE TITLE
Add in REAME a check for an application is calling you

### ISSUE THREAD

**Issue by vronin** [OAuthSwift/OAuthSwift#205]
Current example in REAME looks like that:
```
func application(app: UIApplication, openURL url: NSURL, options: [String : AnyObject]) -> Bool {
  if (url.host == "oauth-callback") {
    OAuthSwift.handleOpenURL(url)
  }
  return true
}
```
However, this leaves an application open for abuses. Any other application may try to open a URL and this app will accept it.

The better check would be
```
if (options["UIApplicationOpenURLOptionsSourceApplicationKey"] as? String == "com.apple.SafariViewService" && url.host == "oauth-callback") 
```

**Comment by vronin** [comment]
BTW. I think it make sense to add this check for pre-OS 9 example too (just to be on the same side)

**Comment by phimage** [comment]
agree to add some info about it into readme.md
but maybe a chapter just because maybe there is other value than "com.apple.SafariViewService"
This value is for external safari app and/or new safari(internal)controller?

**Comment by vronin** [comment]
Yeah. You right. There could be other browser. I just implied SafariViewService, because I was using it.

This value is for new SFSafariViewController. It looks (from UI perspective) as internal, but it's actually executed in a separate process.
