### ISSUE TITLE
Provide a cancel function on OAuthSwiftHTTPRequest

### ISSUE THREAD

**Issue by FGoessler** [OAuthSwift/OAuthSwift#211]
It would be nice to cancel running HTTP requests. NSURLSessionTask offers a simple API for that (just call cancel), but since the NSURLSessionTask is not exposed in the OAuthSwiftHTTPRequest class we cannot access it.

One could either provide a method on OAuthSwiftHTTPRequest to cancel the request or just expose the underlying task as a property.

**Comment by phimage** [comment]
Add near `session` an attribute `task` into `OAuthSwiftHTTPRequest` and provide the `stop`or `cancel` function (function which do nothing if no task)

or alternatively add a callback on `start` method to get the `task`...

You can PR
