### ISSUE TITLE
Provide a method on OAuthSwiftClient that accepts a plain NSURLRequest

### ISSUE THREAD

**Issue by FGoessler** [OAuthSwift/OAuthSwift#212]
To interact with existing Objective C APIs, which often work with NSURLRequests, it would be nice to have a method on OAuthSwiftClient which accepts an NSURLRequest in addition to the more convenient method that accept URL string, parameters, headers and co.

With that it would also be possible to use advanced properties of NSURLRequest like cachePolicy and timeoutInterval.

**Comment by phimage** [comment]
`OAuthSwiftHTTPRequest` have a private init with `NSURLRequest`. Don't know if already used.

So in `OAuthSwiftClient` a `request`method could be created with `NSURLRequest` as parameter
`makeRequest` must be splitted to 3 functions 
- one with common code and parameters OAuthSwiftHTTPRequest
- one with same signature as current one (and call the first one)
- one with  `NSURLRequest` (and call the first one)

PR if you want

**Comment by FGoessler** [comment]
The initialiser on ```OAuthSwiftHTTPRequest``` which accepts an ```NSURLRequest``` isn't used yet, but imo also partially broken, since it doesn't extract the requests data into the ```OAuthSwiftHTTPRequest``` local properties (e.g. params, headers, ...) which might lead to confusion when requesting certain information about the request from an ```OAuthSwiftHTTPRequest``` object which are wrong then.

I'll try to fix that as well.

**Comment by FGoessler** [comment]
Is there a reason that the parameters property on ```OAuthSwiftHTTPRequest``` is of type ```[String:AnyObject]``` - imo it should be ```[String:String]``` like in other places of the lib?
