### ISSUE TITLE
Persist OAuthSwiftCredential version

### ISSUE THREAD

**Issue by paulhimes** [OAuthSwift/OAuthSwift#222]
The "version" property of the OAuthSwiftCredential object is not persisted during the NSCoder encode / decode cycle.

The version always comes back as OAuth1 after a decode.

**Comment by phimage** [comment]
Yes it is not and a PR can be done if this is a real problem


In which case not persist the version could be a problem?
(The credential could not be set in oauthclient)

**Comment by phimage** [comment]
without response I close

**Comment by phimage** [comment]
N.B. now the credential could be set when initialising client, this could add misunderstanding
