### ISSUE TITLE
UIApplication is missing in OAuthSwiftHTTPRequest.swift

### ISSUE THREAD

**Issue by emericspiroux** [OAuthSwift/OAuthSwift#225]
Hi guys, 
I've some "use of unresolved identifier 'UIApplication'." when i build my application, can i fix this by importing UIKit or something went wrong in my install ?
Details :
- OS targeted (with version): *9.3*
- OAuth provider: ~
- OAuthSwift version: 0.5.0 download from pod
- Xcode Version : 7.3 (7D175)
- Swift : version 2.2 (swiftlang-703.0.18.1 clang-703.0.29) Target: x86_64-apple-macosx10.9

**Comment by phimage** [comment]
Did you use in application extension?
If yes see wiki

**Comment by emericspiroux** [comment]
👍  My bad, sorry for wasting your time >< (RTFM !!!!)
