### ISSUE TITLE
Setting scope for OAuth1

### ISSUE THREAD

**Issue by nsbarr** [OAuthSwift/OAuthSwift#226]
I'm sorry if this isn't the right place to post this question, but I don't understand how to set permissions with the authorizeWithCallbackURL method for oauth1swift. 

My specific need is to set scope:"read,write" for Trello. Trello uses oauth1. How would I set this and other parameters (eg., "name")?

**Comment by phimage** [comment]
There is no scope in oauth version 1 protocol, that's why there is no specific parameter

You can add in the url scope=...
Or maybe there is  'parameters' dictionary (i can't check now)

**Comment by nsbarr** [comment]
Thank you for the help. In case anyone else runs into this:

Trello docs: https://developers.trello.com/authorize

I was able to set parameters via the authorizeURL parameters, like this:

authorizeUrl:    "https://trello.com/1/OAuthAuthorizeToken?name=helloapp&expiration=30days&scope=read,write",
