### ISSUE TITLE
Parameters converted to String

### ISSUE THREAD

**Issue by kajensen** [OAuthSwift/OAuthSwift#227]
I think you should just return the response NSData (or [String: AnyObject]) instead of casting json to a [String: String]. Unless there is a good reason for this?
This is an issue for instagram oauth where the response has user data in a dictionary.

**Comment by phimage** [comment]
Could you give the lines of code?

**Comment by kajensen** [comment]
Yeah, thats the line i'm talking about. I changed it so parameters is a [String: AnyObject] dictionary in TokenSuccessHandler, and I return the responseJSON (line 190 in Oauth2.swift) instead of the casted parameters used to extract the credentials as strings.

**Comment by kajensen** [comment]
The cast made it nearly impossible to translate it back to a dictionary so this was easier for me.

**Comment by phimage** [comment]
are you able to respond to my question? is it NSData or NSDictionary?
its readable after converting it to string ?(ie is its a json string, its easy a create a dictionary from it)

**Comment by kajensen** [comment]
its an nsdictionary. its readable as a string, but I tried a few different things and did not find it easy to create a dictionary from it.

**Comment by phimage** [comment]
try this from stack over flow if its a json string, maybe not, just a dictionary string representation
(if not json, maybe I will add a way to choose how to cast to string)

func convertStringToDictionary(text: String) -> [String:AnyObject]? {
    if let data = text.dataUsingEncoding(NSUTF8StringEncoding) {
        do {
            let json = try NSJSONSerialization.JSONObjectWithData(data, options: .MutableContainers) as? [String:AnyObject]
            return json
        } catch {
            print("Something went wrong")
        }
    }
    return nil
}

**Comment by kajensen** [comment]
Yeah I tried that among other things. I guess I just don't understand the rationale for casting it to a string and then forcing a cast back if necessary?

**Comment by phimage** [comment]
Unfortunately I can change method signature easily without impacting all people which use the library
You could PR anyway, and I will think about it and merge only into a main release
