### ISSUE TITLE
How to access OAuthSwift WebView?

### ISSUE THREAD

**Issue by SamuelNLerner** [OAuthSwift/OAuthSwift#228]
I am writing an app for iOS 8.0 using OAuthSwift. I am trying to implement logout functionality. I have already deleted cookies, cleared the cache, and synchronized nsuserdefaults. However, the web browser that oauthswift sends me to keeps me logged in. I read that I needed to also call:

`<UIWebView>.stringByEvaluatingJavaScriptFromString("localStorage.clear();")!`

However, I don't know how to access the webview (or is it an SFSafariController?) to be able to clear it.

**Comment by phimage** [comment]
Did you set the authorize_url_handler ?
If not, an external safari app is open and you cannot do anything I suppose...
You must set your custom handler to use your own web view, see demo app for instance

(SFSafariController is iOS9 and must be set explicitly)

**Comment by hibidibigibidibi** [comment]
Thank you. That worked; however, now the webview won't redirect back to the app.
