### ISSUE TITLE
Redirect URI not working

### ISSUE THREAD

**Issue by SamuelNLerner** [OAuthSwift/OAuthSwift#229]
I was previously using the default authorize_url_handler for authorization, and the redirect_uri that I registered with Spotify worked properly. However, I recently set the authorize_url_handler to a custom webview. The authorization still works but the redirect_uri doesn't anymore. Did the default oauthswift handler append something to the uri that I should do as well?

**Comment by phimage** [comment]
Did you define a delegate to your webview,maybe the delegate do something
You can in delegate handle the redirection url and call OauthSwift.handleOp...
But redirection with scheme must work as well
