### ISSUE TITLE
Not All Services are available with OAuthSwfit Demo

### ISSUE THREAD

**Issue by huiwang** [OAuthSwift/OAuthSwift#232]
== Describe here the steps to reproduce, with error message if any, and your code if relevant ==

- **OS targeted (with version): 10.11.3 (15D21)
- **OAuth provider: 
- **OAuthSwift version: master

After openning the demo app, i can't see the full list of services in the homepage. The service list starts with 500px. For example, I can't see the service twitter.

**Comment by phimage** [comment]
I can reproduce the issue, maybe a file reading failure

If you want to debug into ViewController.swift, see `initConf`
the following code must be executed
```swift
if let path = NSBundle.mainBundle().pathForResource("Services", ofType: "plist") {
            services.loadFromFile(path) // debug point here
```
