### ISSUE TITLE
Is there any way to do logout with SFSafariViewController?

### ISSUE THREAD

**Issue by dasoga** [OAuthSwift/OAuthSwift#235]
I'm trying to do logout user from my server. 
With url like: "http://auth.mydomain.com/logout

I'm using Safari View controller
Somebody knows how can I do logout through OAuthSwift?.
Thanks!

**Comment by phimage** [comment]
According to the docs: SFSafariViewController shares cookies and other website data with Safari and because it runs outside your app's process (for security reasons) I think you cannot modify it's state from inside your app 
(Without SFSafariViewController  ie. webkit view we remove the cookies)

Maybe we could present the SFSafariViewController with logout page for the specific provider, for instance http://github.com/logout

**Comment by dasoga** [comment]
My problem is when I open SFSafariViewController with my url "http://auth.mydomain.com/logout" whit this code:

        for key in Array(NSUserDefaults.standardUserDefaults().dictionaryRepresentation().keys) {
            print(key)
            NSUserDefaults.standardUserDefaults().removeObjectForKey(key)
        }
        let urlString = "http://auth.dubalu.com/logout"
        if let url = NSURL(string: urlString) {
            let vc = SFSafariViewController(URL: url, entersReaderIfAvailable: true)
            vc.delegate = self
            presentViewController(vc, animated: true, completion: { 
                self.goToLoginView()
            })
        }

I'm clearing all cache and in completion I'm going to my login view controller, but SFSafariViewController is still in the stack of view controller.

Someone who knows if is another way to do this?

Really thanks!

**Comment by dasoga** [comment]
@phimage actually that's work good, but the SFSafariViewController is still in the stack of view controllers.

**Comment by phimage** [comment]
you have an error message which specify that? (view already in stack..)

**Comment by dasoga** [comment]
@phimage sorry, yes that is the problem, the SFSafariViewController is not well dismissed.

**Comment by phimage** [comment]
@dasoga If you have an error message please post it (google search with this message could help me to understand)

In the past I have some issue with controller not well dismissed, dispatch queue problem. So I use a library like https://github.com/kodlian/Eki to dispatch some code into main (or background) queue

**Comment by phimage** [comment]
https://github.com/OAuthSwift/OAuthSwift/wiki/Logout

**Comment by mishravinay** [comment]
OAuth Swift not provide any .logout functionality
