### ISSUE TITLE
custom the modal presentation style of SafariURLHandler 

### ISSUE THREAD

**Issue by ElvisYang** [OAuthSwift/OAuthSwift#236]
I found there is no way to custom the modal presentation style of SafariURLHandler, just like i want to
```
controller.modalPresentationStyle = .FormSheet
```

**Comment by phimage** [comment]
You can set a block to create the controller with your custom change
see SafariURLHandler.factory attribute

**Comment by ElvisYang** [comment]
Thanks @phimage That is helpful
