### ISSUE TITLE
How to keep user signed in ?

### ISSUE THREAD

**Issue by archiewahwah** [OAuthSwift/OAuthSwift#240]
What should I do if token expires ? Is there a way to get new token without forcing user to re-enter his login and password ?

**Comment by phimage** [comment]
Oauth2 or oauth1?
Look for "renew" process

**Comment by archiewahwah** [comment]
oauth2
tried looking, but didnt find anything useful :(

**Comment by phimage** [comment]
There is a pr for automatic renew that could not be merged
But you can do it by making a request, see your oauth provider doc

**Comment by antwerpenR** [comment]
@archiewahwah  I have found that the auto renewal generally does work.  When it fails you will get a error.code of 401 and you can try the call again and it will work.   I guess the foolproof way to do it is to use:  
'renewAccesstokenWithRefreshToken(refreshToken: String, success: TokenSuccessHandler, failure: FailureHandler?)'

**Comment by phimage** [comment]
"expire in" date must be checked and `renewAccesstokenWithRefreshToken` used

(one day automatic renew will be merged I hope)
