### ISSUE TITLE
Crash in OAuthSwiftHTTPRequest.swift

### ISSUE THREAD

**Issue by Ankish** [OAuthSwift/OAuthSwift#241]
- **OS targeted (with version):**  9.2.1
- **OAuth provider:**  LinkedIn
- **OAuthSwift version:** pod "OAuthSwift", "~> 0.5.0"

OAuthSwiftHTTPRequest.swift OAuthSwiftHTTPRequest.(start(OAuthSwiftHTTPRequest) -> () -> ()).(closure #1).(closure #1)
It generally happens at app launch . Seen from the logs. PFA the log
[OAuthCrash.pdf](https://github.com/OAuthSwift/OAuthSwift/files/327249/OAuthCrash.pdf)

**Comment by phimage** [comment]
trying to investigate
maybe an issue with dispatch module

try to add `import Dispatch` in your 'AppDelegate.swift'

Where you use OAuthSwift in an `UIApplicationDelegate` method? crash show `AppDelegate.swift:20`
Maybe too soon so a task or a dispatch could used to postpone the use of OAuthSwift

**Comment by phimage** [comment]
I close because no response for 15 days. Feel free to respond anyway. I can reopen this issue
