### ISSUE TITLE
When will there be swift 3 support?

### ISSUE THREAD

**Issue by simonnarang** [OAuthSwift/OAuthSwift#244]
Thanks, have an app running on spm 3.0

**Comment by phimage** [comment]
I will a create a beta branch starting with last stable release
(and me or another contributor will commit into)
Master branch will be updated as usual when xcode 8 will be released

Downloading xcode 8 beta now
I am not familiar with swift package manager, so If you have some clues 
- like maybe create a file at root which describe the repository[like cocoadpod] or this could work "automatically"[like carthage])
- if a branch could be specified (ie. the beta branch from OAuthSwift)

**Comment by phimage** [comment]
branch swift 3.0 created with automatic conversion and come compilation fix

**Comment by phimage** [comment]
WIP  PR #267 https://github.com/skedgo/OAuthSwift.git branch swift3.0

**Comment by leo150** [comment]
What about https://github.com/OAuthSwift/OAuthSwift.git swift3.0 branch? Is it working?

**Comment by phimage** [comment]
@leo150  the branch I thinks is not working
use temporary fork https://github.com/skedgo/OAuthSwift/ on branch swift3.0

**Comment by phimage** [comment]
PR #277 (old one PR #267 ) merged into swift3.0 branch
then merged into master 5a1e5759934f8138c8ae96d2c7614d776c608b33 
with some modifications :
- fix project settings
- some missing conversion
- add swift-version file 
- rename functions and attributes
  - `authorizeWithCallbackURL(...`-> `authorize(withCallbackURL...`-
  - `authorize_url_handler` -> `authorizeURLHandler`
  - ...
- Return only `OAuthSwiftError` in failure callback ie. typed errors (`tokenExpired`, ...)
- Return an handle on request to cancel
- ...


There is yet some TODO
- remove NSData and NSString reference
- better handle returned when authorizing 
  - when cancelling, cancel all the children request (there is cascading request)
  - by keeping a list of current request in `OAuthSwift`object


let me know if there is some bug, before tagging and releasing

**Comment by SMillerDev** [comment]
@phimage the branch for https://github.com/skedgo/OAuthSwift/ is swift3 btw (no **.0**)

**Comment by phimage** [comment]
@SMillerDev you comment an old post (so useless)
skedgo branch has been merged to origin swift3.0 branch and then master

**Comment by SMillerDev** [comment]
My bad, it was still open. Figured it was still relevant.

**Comment by hardikdevios** [comment]
@phimage Please update PodSpec bro

**Comment by phimage** [comment]
@@]podspeczer sq

**Comment by hardikdevios** [comment]
Lol no problem Bro 👍 

For now i am using 

> 
> `pod 'OAuthSwift', :git => 'https://github.com/OAuthSwift/OAuthSwift.git', :commit => '0b8f8d10e101d3c67c809fc2365c0ef07407ba47'
> `

Working perfectly have to make some changes in Methods for Swift 3 other then its safe :)

**Comment by jjjeeerrr111** [comment]
Any idea when the 1.0.0 will be release for Cocoapod support?

**Comment by phimage** [comment]
@jjjeeerrr111: no, why?
see no date for milestone https://github.com/OAuthSwift/OAuthSwift/milestone/2

**Comment by tonygon** [comment]
@hardikdevios thanks for the command!
@phimage and of course thank you for developing OAuthSwift ;) great stuff!

**Comment by jjjeeerrr111** [comment]
@phimage wondering how I can incorporate OAuthSwift into my Swift 3.0 project

**Comment by ahmad-ishfaq** [comment]
pod 'OAuthSwift', :git => 'https://github.com/OAuthSwift/OAuthSwift.git' is not working properly it gives me an oauthswit error -10 when authenticating for twitter

**Comment by phimage** [comment]
@ahmad-ishfaq please make a descriptive issue instead of writing here... (and fill issue template)
with the detailed content of the error  (maybe an `OAuthSwiftError.requestError(error: /*an NSError  with info*/)`)

**Comment by phimage** [comment]
1.0.0 tagged
swift3 branch removed

please open new issues if bug
