### ISSUE TITLE
No encoding the auth_token for authorize

### ISSUE THREAD

**Issue by ElvisYang** [OAuthSwift/OAuthSwift#246]
in https://github.com/OAuthSwift/OAuthSwift/blob/master/OAuthSwift/OAuth1Swift.swift#L87

do not encoding the oauth_token

"oauth_token=\(credential.oauth_token)", when it contains just like `&`, `+` .....

For example `credential.oauth_token.urlEncodedStringWithEncoding(OAuthSwiftDataEncoding)`

**Comment by phimage** [comment]
Ok I think you are right, there is an encoding problem
But I will use `urlQueryEncoded`to encode based on `NSCharacterSet.URLQueryAllowedCharacterSet()`
