### ISSUE TITLE
How to do Google+/Youtube authentication correctly?

### ISSUE THREAD

**Issue by martinpilch** [OAuthSwift/OAuthSwift#247]
Hello,
I'm trying to sign-in  into Youtube and Google+ API using `SafariURLHandler`. Anytime I pass through the process and press *Allow* Safari tells me it can't open the page because address is invalid

In your dem I noticed you are using `https://oauthswift.herokuapp.com/callback/google` as Callback URL for GoogleDrive. I guess it's doing kind of redirect. How exactly does it work?
Thanks,
Martin

**Comment by phimage** [comment]
Yes it's redirection the url to a new one with scheme oauth swift://. (Custom scheme allow to pass information to the application, query of the url)

Herokuapp is used because Google accept only http:// url scheme.
Check also that your callback url must be declared or not in your Google account.

**Comment by martinpilch** [comment]
That's weird. Because my URL scheme I can see in Google Console is:
`com.googleusercontent.apps.XXXXXXXXXXXXXXXXXXX`
How is that possible? Are you able to authorise against G+ or Youtube?

**Comment by martinpilch** [comment]
So I found solution. It's necessary to:
- add this URL scheme: `com.googleusercontent.apps.XXXXXXXXXXXXXXXXXXX` into Supported URL schemes 
- also into `LSApplicationQueriesSchemes` section in plist. 
- and finally check for it also when handling URLs in AppDelegate (to pass it to OAuthSwift)

Then it's not necessary to do any redirect
