### ISSUE TITLE
Google Drive example fails with missing state error

### ISSUE THREAD

**Issue by ianbytchek** [OAuthSwift/OAuthSwift#249]
Using `responseType = "token"` works, but the original `responseType = "code"` fails with `Missing state` error. Need to use `code` type in order to get refresh token, base on the [playground](https://developers.google.com/oauthplayground/) notes.

- **OS targeted (with version):** 10.11
- **OAuth provider:** Google Drive OAuth 2.0
- **OAuthSwift version:** latest release

**Comment by phimage** [comment]
maybe this could work by setting `allowMissingStateCheck` to true (if state missing)
let me know

**Comment by ianbytchek** [comment]
Yep, it works, but `refresh_token` in credentials provided as an empty string. Any ideas why would that be?

**Comment by phimage** [comment]
Did we pass in the code defined bellow in OAuthSwift2 (code which affect the refresh token
```swift
if let refreshToken = responseParameters["refresh_token"] as? String {
                self.client.credential.oauth_refresh_token = refreshToken.safeStringByRemovingPercentEncoding
            }
```

**Comment by ianbytchek** [comment]
Yes, there is that check in the code. Apparently must provide additional parameters `approval_prompt=force&access_type=offline` – they are used in the playground and `access_type` is reported to be the one that enforces `refresh_token` being sent with the response.
