### ISSUE TITLE
Wrong 'parameter' for startAuthorizedRequest() after requesting a new access token

### ISSUE THREAD

**Issue by mixable** [OAuthSwift/OAuthSwift#253]
Using `startAuthorizedRequest()` when the stored access token expired will force a renew of the access token by automatically calling `renewAccesstokenWithRefreshToken()`. After successfully retrieving a new token, `startAuthorizedRequest()` will be called a second time to get the requested data ([see OAuth2Swift.swift line 243](https://github.com/OAuthSwift/OAuthSwift/blob/v0.5.2/OAuthSwift/OAuth2Swift.swift#L243)).

**Bug:** the second method call is done with different parameters. `parameters` in line 249 are not the original once given to `startAuthorizedRequest()`. When passing custom parameters, they are not available in the second method call.

Or am I using this method in a wrong way? As the method `client.post()` does not have the feature of automatically renewing the access token, I passed my POST data to `startAuthorizedRequest()` and ended up with the described behaviour.

- **OS targeted (with version):** iOS 9.x
- **OAuthSwift version:** v0.5.2

**Comment by mixable** [comment]
**Solution:**
In [line 234](https://github.com/OAuthSwift/OAuthSwift/blob/v0.5.2/OAuthSwift/OAuth2Swift.swift#L234) rename `parameters` to e.g. `refreshParameters`:
```php
self.renewAccesstokenWithRefreshToken(self.client.credential.oauth_refresh_token, success: { (credential, response, refreshParameters) in
```

**Comment by phimage** [comment]
could you make a PR?
