### ISSUE TITLE
CocoaPods v0.5.2 Not synced with release v0.5.2

### ISSUE THREAD

**Issue by freynolds** [OAuthSwift/OAuthSwift#255]
For example

`    func renewAccesstokenWithRefreshToken(refreshToken: String, success: TokenSuccessHandler, failure: FailureHandler?) {
`

Still has the code of v0.5.1

My regrads
Francis

**Comment by phimage** [comment]
the current signature , head master -> will be 0.6.0 -> https://github.com/OAuthSwift/OAuthSwift/milestone/1
```swift
  public func renewAccessTokenWithRefreshToken(refreshToken: String, headers: [String:String]? = nil, success: TokenSuccessHandler, failure: FailureHandler?) {
```

the 0.5.2 on Apr 5 ( https://github.com/OAuthSwift/OAuthSwift/releases/tag/v0.5.2 )
  signature is 
```swift
 renewAccesstokenWithRefreshToken(refreshToken: String, success: TokenSuccessHandler, failure: FailureHandler?)
```

I think I will release next version tomorrow

Could you close

**Comment by freynolds** [comment]
Ok, following @phimage  reply will update tomorrow. For now I use direct link to repo!
