### ISSUE TITLE
Cannot convert value to expected argument type TokenSuccessHandler

### ISSUE THREAD

**Issue by ianbytchek** [OAuthSwift/OAuthSwift#260]
Just updated to 0.6.0 using Carthage and getting an amazing compiler error for OS X.

> Error:(60, 22) cannot convert value of type '(OAuthSwiftCredential, NSURLResponse?, [String : String]) -> ()' to expected argument type 'TokenSuccessHandler' (aka '(credential: OAuthSwiftCredential, response: Optional<NSURLResponse>, parameters: Dictionary<String, AnyObject>) -> ()')

```swift
oauth.authorizeWithCallbackURL(
    NSURL(string: configuration.callbackUrl)!,
    scope: configuration.scope,
    state: configuration.state,
    params: configuration.parameters,
    success: {
        [weak self] (credential: OAuthSwiftCredential, response: NSURLResponse?, parameters: [String : String]) in
        // …
    },
    failure: {
        [weak self] (error: NSError) in
        // …
    })
```

**Comment by phimage** [comment]
parameters is no more String:String dictionary but String:AnyObject

**Comment by ianbytchek** [comment]
Oops, forgot to get back on this. Yes, thank you – `String:AnyObject` is the answer. Missed the obvious somehow.
