### ISSUE TITLE
OAuth1 is crashed (on self access)

### ISSUE THREAD

**Issue by NightBlaze** [OAuthSwift/OAuthSwift#262]
I use OAuthSwift to connect to Upwork API https://developers.upwork.com
Trying to authenticate

```
func authenticate() {
    let oauthswift = OAuth1Swift(
        consumerKey:     "key",
        consumerSecret:  "secret",
        requestTokenUrl: "https://www.upwork.com/api/auth/v1/oauth/token/request",
        authorizeUrl:    "https://www.upwork.com/services/api/auth",
        accessTokenUrl:  "https://www.upwork.com/api/auth/v1/oauth/token/access"
    )
    oauthswift.authorizeWithCallbackURL(
        NSURL(string: "my-scheme-upwork://oatuh-upwork")!,
        success: { credential, response, parameters in
            print(credential.oauth_token)
            print(credential.oauth_token_secret)
            print(parameters["user_id"])
        },
        failure: { error in
            print(error.localizedDescription)
        }             
    )
}
```

And I get the crash
![https://s10.postimg.org/al6csjjtl/2016_08_08_10_37_24.png](https://s10.postimg.org/al6csjjtl/2016_08_08_10_37_24.png)

- **OS targeted (with version):** ??
iOS 9.0
- **OAuth provider:** ??
Upwork
- **OAuthSwift version:** previous/last release, master head???
0.6.0

**Comment by phimage** [comment]
your oauthswift object is no more in memory I think ( self cannot be acceded)
keep it as variable of your class

N.B. maybe I can change unowned to weak for self
