### ISSUE TITLE
Swift 2.3 Support

### ISSUE THREAD

**Issue by cpinski** [OAuthSwift/OAuthSwift#263]
Could a Swift 2.3 branch be opened so that I can open a PR with full swift 2.3 support? I am currently on a project that would benefit greatly from having a dedicated Swift 2.3 branch.

**Comment by phimage** [comment]
Since #239 I have not updated xcode beta
There is other change ? Warnings or errors? If yes could be fixed or not using same method from #239

**Comment by cpinski** [comment]
There have been some modifications to the code which makes the diff a little different currently. Also I have updated the project settings to use the project settings recommended by Xcode. I believe the biggest change there is setting SWIFT_OPTIMIZATION_LEVEL = "-Owholemodule". This should speed up the execution of the code.

**Comment by cpinski** [comment]
@phimage I added you as a collaborator on my fork so you can see the changes [here](https://github.com/cpinski/OAuthSwift/commit/fd2ec2df7b2fe9a926eeacc04ff75736eede3957)

**Comment by phimage** [comment]
ok I simulate a PR and see the change
It's essentially xcode project file change.
So it's for compilation with carthage or xcode (cocoapod is not affected)
The other change seems to be conflict with new code

I will create a  swift 2.3 branch
But If you PR I want to see only one commit with only project file change (refork or rebase current branch to a new branch in your fork, make the change and commit)
Thanks in advance

**Comment by phimage** [comment]
fixed by  #264
