### ISSUE TITLE
Authorize with callback url never succeeds / fails

### ISSUE THREAD

**Issue by ianbytchek** [OAuthSwift/OAuthSwift#265]
After updating to 0.6.0 something stopped working on mac. I use custom web view controller for Dropbox and GoogleDrive only, none succeed nor fail at the moment. I narrowed it down to `OAuthSwift.handleOpenURL(url)` call, which doesn't seem to be doing anything any longer.

```swift
public func webView(webView: WKWebView, decidePolicyForNavigationAction navigationAction: WKNavigationAction, decisionHandler: (WKNavigationActionPolicy) -> Void) {
    if let url: NSURL = navigationAction.request.URL?.URLByDeletingLastPathComponent where url.path == "/integration/oauth" {
        decisionHandler(WKNavigationActionPolicy.Cancel)
        OAuthSwift.handleOpenURL(url)
    } else {
        decisionHandler(WKNavigationActionPolicy.Allow)
    }
}
```
Delegate recognises url correctly. I also receive notification emails from Dropbox / Google, so it actually works.

Did anything happen to the way how `handleOpenURL` works? Is something new must be taken into account now?

**Comment by phimage** [comment]
I try demo app on OS X with dropbox, and no problem for me

maybe call `OAuthSwift.handleOpenURL(url)` before `decisionHandler`

**Comment by ianbytchek** [comment]
Tried it both ways, no luck. I'll take a closer look then.

**Comment by ianbytchek** [comment]
> Did you retain your OAuthSwift object somewhere?

Shit… Would have saved me a lot of time if came with the email.

Yes, I see some changes around that – `OAuthSwift` was retained internally, I guess not intentionally, since that all changed, but that also automatically retained it for me. Thanks for pointing out.
