### ISSUE TITLE
Can not build with today's extension due to errors

### ISSUE THREAD

**Issue by manishm2000** [OAuthSwift/OAuthSwift#266]
Can't figure out where to set the flag OAUTH_APP_EXTENSIONS for Today's Extension in swift when using with cocoapods to avoid the compile errors. Can you please suggest. Thanks!!

**Comment by phimage** [comment]
Did you see https://github.com/OAuthSwift/OAuthSwift/wiki/Work-with-application-extension
I have not tested since the wiki page creation and cocopad have many updates since, so try to edit your Podfile and add the lines from wiki page
