### ISSUE TITLE
No http in Instagram uri field, what to use for value?

### ISSUE THREAD

**Issue by ejpusa** [OAuthSwift/OAuthSwift#268]
Ok, I'm sure this has been faced before. What uri should we be using for Instagram for the redirect back to my app? Thought at one point IG accepted: oauth-swift://oauth-callback/instagram

But that no longer seems to be the case.  Thanks for help.

<img width="859" alt="screen shot 2016-08-17 at 4 14 08 am" src="https://cloud.githubusercontent.com/assets/1279819/17729361/e190db2a-6431-11e6-9d23-832f85dee0fc.png">

**Comment by phimage** [comment]
#258

**Comment by ejpusa** [comment]
Thanks for quick response, IG does require a value there. I can't leave it blank it looks like.

> Handle a specific URL into delegate
Use an internal webview (UIWebView, WKWebView, ..)
by setting a controller as oauthswift.authorize_url_handler to load web pages into the webview
by implementing a web view delegate (UIWebViewDelegate, WKNavigationDelegate, ..) to handle the callback url and call OAuthSwift.handleOpenURL(url)

**Comment by ejpusa** [comment]
From this text, still not sure what URl is needed by instagram, since that URI now has to start with https://   

1. What is the one to use?
2. In the app, are there edits to the pList values?
3. How do they match with what is entered?

thanks

**Comment by phimage** [comment]
1: use what you want
2 no plist things to do
3 use same callback url that you set in instagram

read wiki more closely, see demo code in webview delegate (call of oauthswift.handle...)
