### ISSUE TITLE
Twitter OAuth on iOS

### ISSUE THREAD

**Issue by alexsanderkhitev** [OAuthSwift/OAuthSwift#270]
Hello! I need to register on our server via twitter. I made registration with help of OAuth. When we make any request on our server we check our token is active, if our token is expired we make resign on our server and I need to resign in Twitter session, I do logout, but session is active. Android team do it with help

TwitterCore.getInstance().getSessionManager().clearActiveSession();
TwitterCore.getInstance().logOut();
. How can I do it on iOS? I use Swift Please, help me.

**Comment by phimage** [comment]
Maybe this can help https://github.com/OAuthSwift/OAuthSwift/wiki/Logout
Then sometime api provider provide a request to delete the token remotely

**Comment by alexsanderkhitev** [comment]
@phimage thank you so much
