### ISSUE TITLE
Application Error on callback for Google Auth

### ISSUE THREAD

**Issue by jferdizzle** [OAuthSwift/OAuthSwift#271]
I'm using the provided function with the correct keys for my account. The callback (https://oauthswift.herokuapp.com/callback/google), which is registered in Google as the redirect_uri. 

Any ideas?

 == Describe here the steps to reproduce, with error message if any, and your code if relevant ==

- **OS targeted (with version):** 8.2
- **OAuth provider:** Google 
- **OAuthSwift version:** Last Release

Instead or returning to the app and doing the API call, I'm getting HTML that says:

Application Error

An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.

**Comment by jferdizzle** [comment]
I think https://oauthswift.herokuapp.com/callback/ is down since I get the same error when I go there.

**Comment by phimage** [comment]
https://oauthswift.herokuapp.com/callback/ is for test or demo purpose
Please read https://github.com/OAuthSwift/OAuthSwift/wiki/API-with-only-HTTP-scheme-into-callback-URL

**Comment by jferdizzle** [comment]
Thanks for the repo link. All set! 

In case anyone is confused like I was:

I just ran it on a new heroku instance and updated the index.erb file before uploading it to the server as follows:
From this:
<span class="highlight">http://oauthswift.herokuapp.com/callback/{app_name}</span>

To this:
<span class="highlight">http://{PUT YOUR HEROKU NAME}.herokuapp.com/callback/{app_name}</span>

Don't forget to update the redirect_uri so that they match.
