### ISSUE TITLE
IOS10 Crash of '[unowned self]'

### ISSUE THREAD

**Issue by zenyuhao** [OAuthSwift/OAuthSwift#276]
== Describe here the steps to reproduce, with error message if any, and your code if relevant ==

- **OS targeted (with version):10.0 (iphone6)
- **OAuth provider:twitter
- **OAuthSwift version:0.6.0

Hi, I found a bug (maybe) in IOS10

look at this line, the code `[unowned self]` may cause a crash in ios10 , it will not happen in ios9

~~~
    // 1. Request token
    func postOAuthRequestTokenWithCallbackURL(callbackURL: NSURL, success: TokenSuccessHandler, failure: FailureHandler?) {
        var parameters =  Dictionary<String, AnyObject>()
        if let callbackURLString: String = callbackURL.absoluteString {
            parameters["oauth_callback"] = callbackURLString
        }
        self.client.post(self.request_token_url, parameters: parameters, success: {
            [unowned self] data, response in  // <-- here
            let responseString = NSString(data: data, encoding: NSUTF8StringEncoding) as String!
            let parameters = responseString.parametersFromQueryString()
            if let oauthToken=parameters["oauth_token"] {
                self.client.credential.oauth_token = oauthToken.safeStringByRemovingPercentEncoding
            }
            if let oauthTokenSecret=parameters["oauth_token_secret"] {
                self.client.credential.oauth_token_secret = oauthTokenSecret.safeStringByRemovingPercentEncoding
            }
            success(credential: self.client.credential, response: response, parameters: parameters)
        }, failure: failure)
    }

~~~

and i debug it, the __self__ may be already released
It generally happens at app launch
and i try to delete the "unowned self"，it works well, no crash anymore。
dose any thing wrong with it?

forgive my poor english

**Comment by phimage** [comment]
"unowned self" must be replaced by "weak self" here
with 
"guard let this = self else { OAuthSwift.retainError(failure); return }"

keep a reference to your oauthSwift object and it will be not released

**Comment by zenyuhao** [comment]
3ks , got it, not notice that master has been repaired 
3ks again
