### ISSUE TITLE
Credentials are not cached

### ISSUE THREAD

**Issue by ivanruizscm** [OAuthSwift/OAuthSwift#281]
I have to call oauthswift.authorizeWithCallbackURL everytime before make an api call, so the users is redirected to the google allow access page everytime i instantiate a new OAuth2Swift object

- **OS targeted (with version) 10
- **OAuth provider: Google
- **OAuthSwift version: https://github.com/skedgo/OAuthSwift/ in swift3 branch

**Comment by phimage** [comment]
could you edit your comment and fill the template

**Comment by phimage** [comment]
please use master branch from now (swift 3 compatible)
function has been renamed to `oauthswift.authorize(withCallbackURL`

why did you create a new OAuth2Swift object, you must retain it and use it again and again
the credential is stored into it (`oauthswift.client.credential`)

**Comment by ivanruizscm** [comment]
and if i leave the app should i ask for permission again?

**Comment by ivanruizscm** [comment]
is this object serializable?

**Comment by ivanruizscm** [comment]
maybe this is what i was looking for -> https://github.com/OAuthSwift/OAuthSwift/wiki/Store-credential

**Comment by phimage** [comment]
yes this is the good page for that
