### ISSUE TITLE
Unable to Understand Header values. bellow is code i have used. Please suggest solution

### ISSUE THREAD

**Issue by Mahadev77** [OAuthSwift/OAuthSwift#282]
```swift
  oauthswift.client.request(
"api.tumblr.com/v2/blog/One_Touch_Share.tumblr.com/post", 
method: .POST, parameters: ["type":"text"], headers: ["Authorization":??????????????]
, success: {
                responce in
                print("Success..")
                },
 failure: { error in
            print("Failed.....")
            }
)
```

**Comment by phimage** [comment]
please don't remove the template...

`headers: ["Authorization":??????????????]` you don't have to fill header with "Authorization"
it is automatic if you are authentified
It's for additional headers that oauth provider need

**Comment by Mahadev77** [comment]
Dear,
you don't have to fill header with "Authorization"
it is automatic if you are authentified -- i am using
>> oauthswift.authorizeWithCallbackURL ( )  and then
>>  oauthswift.client.request ( ) methods.
Now getting error "HTTP Status 404"
Please suggest solution,


Thanks for your reply.

**Comment by phimage** [comment]
I can help more without more information
404 is a generic http error, in web view or in log?
- please add a breakpoint and see the full content of error if its an error in callback
- your callback url is ?

**Comment by Mahadev77** [comment]
Thank you for your reply.
I have sort out that problem.


Thanks,
Mahadev

**Comment by idelfonsog2** [comment]
Hi @phimage Im having the same issues and I get this as a response:

`Response-Body=Optional("{\"meta\":{\"status\":400,\"msg\":\"Bad Request\"},\"response\":{\"errors\":[\"Post cannot be empty.\"]}}")}]`

my code is the following

```
 @IBAction func postTextBlog(_ sender: AnyObject) {
        print(oauth1swift?.parameters)
        
        let headers = ["Accept": "application/json", "Content-Type":"application/json"]
        
        let parameters = [ParameterKeys.BlogType:ParameterValues.MarkdownType, ParameterKeys.Body:textBlog.text] as [String : Any]
        
        oauth1swift?.client.request(TMClient.sharedInstance().tumblrURL(withPathExtension: Methods.PostText), method: .POST, parameters: parameters, headers: headers, success: {
            (data, error) in
            let json = TMClient.sharedInstance().convertToJSONObject(data: data)
            print(json)
            print("hello")
            
            }, failure: {
                error in
                print(error)
        })
        

    }
```
(TMClient.sharedInstance().tumblrURL(withPathExtension: Methods.PostText) is essentially this: 
URL: https://api.tumblr.com/v2/blog/idelfonsog2.tumblr.com/post

you can also see it below
```
OAuthSwiftError.response=<NSHTTPURLResponse: 0x60000022dc80> { URL: https://api.tumblr.com/v2/blog/idelfonsog2.tumblr.com/post } { status code: 400, headers {
    Connection = "keep-alive";
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Tue, 18 Oct 2016 02:01:00 GMT";
    P3P = "CP=\"Tumblr's privacy policy is available here: https://www.tumblr.com/policy/en/privacy\"";
    Server = openresty;
    "Set-Cookie" = "tmgioct=5805825c60e2e80081398740; expires=Fri, 16-Oct-2026 02:01:00 GMT; Max-Age=315360000; path=/; domain=.tumblr.com; HttpOnly";
```

**Comment by phimage** [comment]
@idelfonsog2 please open a new issue
this one is closed and I see anything that can make us conclude easily that the issue is the same...

then I commit a tumblr test in demo app 
a GET not a POST request (so not same way to sign request)
a POST could be added (like /user/follow & /user/unfollow or /user/like & /user/unlike)
