### ISSUE TITLE
Headers get overwritten with nil

### ISSUE THREAD

**Issue by jwrigh26** [OAuthSwift/OAuthSwift#284]
1. Init an OAuth2Swift object
2. Set parameters for OAuth2Swift object
3. Call authorizeWithCallbackURL(_:scope:state:params:headers:success:failure)
4. Getting error back with status code: 403

This is caused because on line **203** of OAuth2Swift.swift:
`var headers: [String:String]? = nil`

The headers passed in the from the method get overwritten by the local variable *headers* and therefore are never used. By changing the code to

`var headers: [String:String]? = headers`

I was successful with getting OAuth to happen. 

- **OS targeted iOS: 9.3.5** 
- **OAuth provider: MapMyRun**
- **OAuthSwift version: master**

**Comment by phimage** [comment]
"var headers: [String:String]? = nil" is an old code
version 0.6 introduce the headers in function parameters
will be fixed

**Comment by jwrigh26** [comment]
I see. Yes my bad I thought our team was using **master** but it turns out we are still on the **swift3.0** branch. Do you know when this will be fixed for Swift3.0?

**Comment by phimage** [comment]
I have a probleme with my code now, I can compil due to segmentation fault 11 (and weird error dataTask ambigous, JSOnSErialisation.data not exist..)




The solution I want to commit when I can
var finalHeaders: [String:String]? = headers
then finalHeaders +=   instead of headers = 
then use finalHeads in request function

**Comment by jwrigh26** [comment]
Awesome! Looking forward to the solution. Thank you for the fast response. Sending positive energy your way on resolving the wonderful Xcode compile issues.
