### ISSUE TITLE
Feature request. Airbnb support in demo project

### ISSUE THREAD

**Issue by Gargo** [OAuthSwift/OAuthSwift#288]

**Comment by phimage** [comment]
Hi
you can propose pull request for it, but I will no add myself
there is a wiki page, which describe how to add a provider
https://github.com/OAuthSwift/OAuthSwift/wiki/Demo-application#add-a-new-service-in-demo-app
maybe someone will do it one day

then when asking for something, the minimum its to provide the link to the airbnb documentation about authentification with oauth
http://airbnbapi.org/
it seems weid, you must use facebook or google oauth, there is specific HTTP header "X-Airbnb-OAuth-Token: 9nwld6we4td9vkwj160teb49a". Not a real oauth ...
