### ISSUE TITLE
Expired token

### ISSUE THREAD

**Issue by ivanruizscm** [OAuthSwift/OAuthSwift#289]
I store the tokens (credentials.oauthToken, credentials.oauthTokenSecret), and before making a request i set them into oauthswift.client.credentials.oauthToken/oauthTokenSecret

Them i'm able to make request with those tokens (despite oauthTokenSecret is empty from server) for a period of time (one hour?)

    func get(urlString: String, params: [String: Any]?) -> Observable<Data?> {
        return Observable<Data?>.create({ (observer) -> Disposable in
            print("TOKEN: \(self.oauthswift.client.credential.oauthToken)")
            _ = self.oauthswift.client.get(urlString, parameters: params ?? [:], success: { (data, response) in
                observer.onNext(data)
                observer.onCompleted()
                }, failure: { (error) in
                    switch error {
                    case .tokenExpired:
                        print("Expired")
                    default:
                        break

                    }
                   // observer.onError(CustomError.unauthorized)
            })
            return Disposables.create()
        })
    }
    
Then i get .tokenExpired when i try to make those request.
As https://github.com/OAuthSwift/OAuthSwift/wiki/OAuth-2.0-Token-Expiration then you have to "reconnect", what this means? asking for the user authorizing again in google page?
I need a token for a long period of lifetime or some mechanism for token renewal

- **OS targeted (with version):** 9 / 10
- **OAuth provider:** Google
- **OAuthSwift version:** master branch

**Comment by phimage** [comment]
oauth1 or oauth2?

with oauth2 there is renew token mecanism
This is not automatically done ( #217 talk about this issue)
so you must call `renewAccessToken` (there is also a convenience temporary method `startAuthorizedRequest`)

then when asking for a token sometimes you can add a parameter to specify the period of token availability (for instance expiration=never) but not all provider allow that

**Comment by ivanruizscm** [comment]
http://stackoverflow.com/questions/26048945/oauth-v2-google-api-expiry-access-token
From here seems i need to save also the oauthRefreshToken to renew the previous token. (oauth2)

**Comment by ivanruizscm** [comment]
@phimage seems working, which makes me thing, if someone have your renewalToken, can always ask for valid tokens?

**Comment by iORichy** [comment]
Hi Team, sorry for another question here…
I do try to use the `renewAccessToken` function but not able to assign back the credentials to the client as I do get the following message: 

> Cannot assign to property: 'credential' setter is inaccessible

this is my code (I do have created a new REST client class to work with asynchronous requests and operations…):
`                    oauthswift.renewAccessToken(withRefreshToken: defaults.string(forKey: "oauthRefreshToken")!, success: { (OAuthSwiftCredential) in
                        oauthswift.client.credential = OAuthSwiftCredential
                        completion(self.oauthswift)
                        
                    }, failure: { (OAuthSwiftError) in
                       // …
                       // run full oauthswiftAuthorize.authorize(withCallbackURL: … ) with WebView in another ViewController
                       // …
                            completion(self.oauthswift)

                    })`

Does someone can lead me to the correct approach/usage?
Thanks in advance.

**Comment by yosoycody** [comment]
> oauth1 or oauth2?
> 
> with oauth2 there is renew token mecanism This is not automatically done ( #217 talk about this issue) so you must call `renewAccessToken` (there is also a convenience temporary method `startAuthorizedRequest` will do it automatically instead of using client function)
> 
> then when asking for a token sometimes you can add a parameter to specify the period of token availability (for instance expiration=never) but not all provider allow that

How do you do it for Oauth1?
