### ISSUE TITLE
not fully compatible with swift 3 released

### ISSUE THREAD

**Issue by tobatha** [OAuthSwift/OAuthSwift#290]
hi, 
trying to add the lib via cocoapods, but it'll popup legacy swift version error, and Xcode forces me to upgrade syntax to swift 3

and then i copy all the source folder directly to my project, a lot of compile errors and adjustments need to be done, anyone has the same problem yet?

**Comment by tobatha** [comment]
using carthage, and import the framework solved the problem.

**Comment by phimage** [comment]
legacy swift version error, it's a local problem in your workspace
cocoapod and xcode do some dirty things
many times you must go to your Build settings target and choose the swift version 
"Use legacy swift language version"
for 2.3 => Yes , for 3.0 => No
