### ISSUE TITLE
error.code is inaccessible due to 'fileprivate' protection level

### ISSUE THREAD

**Issue by dbmrq** [OAuthSwift/OAuthSwift#291]
When a request failed, I used to be able to check the error code, like this:

```swift
failure: { error in
    if error.code == 401 {
        //...
    }
}
```

Now with Swift 3 I can't do that anymore, I get that error: "'code' is inaccessible due to 'fileprivate' protection level".

**Comment by dbmrq** [comment]
That was fast. I'm already using Carthage, though, and still no luck. :/

**Comment by phimage** [comment]
see [OAuthSwiftError](https://github.com/OAuthSwift/OAuthSwift/blob/master/Sources/OAuthSwiftError.swift)

it could be an `.tokenExpired` or `.requestError` for code 401 (with last code, not released yet you have attribute `underlyingError`)

you can do a if
```swift
failure: { error in
    if case .tokenExpired == error {
        //...
    }
}
```
or a switch
```swift
failure: { error in
    switch error {
        case .tokenExpired (let underlyingError):
        //...
       case .requestError (let underlyingError):
        //...
       default:
    }
}
```

then you can cast to `NSError` or there is in swift `_code`

**Comment by dbmrq** [comment]
Ah, awesome, thanks!

**Comment by dbmrq** [comment]
@phimage So I was doing what you described in your last answer here, but now I updated to the latest version and I get "Enum case 'tokenExpired' not found in type 'Error'". Any ideas?

PS: You should consider adding a change log. It would be a huge help figuring out this sort of stuff.

**Comment by phimage** [comment]
please refer to [release](https://github.com/OAuthSwift/OAuthSwift/releases) for change log
