### ISSUE TITLE
Getting Error when hit the uber api in AngularJS

### ISSUE THREAD

**Issue by vishu3258** [OAuthSwift/OAuthSwift#292]
Getting error 401 while hitting the uber api in AngularJS. Please help me out here.
Object {message: "No authentication provided.", code: "unauthorized"}
code
:
"unauthorized"
message
:
"No authentication provided."

When i trying to hit the uber api i'll error mention above. Please help me out here.

$http.get('https://api.uber.com/v1/products?latitude=37.7759792&longitude=-122.41823',{
    headers:{
      'server_token': '',
      'client_id': '',
      'client_secret': ''

    }
  }).success(function(response){
    /*$scope.names=response.products;*/
    console.log(response);
  })
  .error(function(response) {
      console.log('error');
      console.log(response);
      $scope.names = 'Error: ' + response;
  });

**Comment by phimage** [comment]
AngularJS? here is a swift project... not javascript
