### ISSUE TITLE
POSTing a text blog to Tumblr

### ISSUE THREAD

**Issue by idelfonsog2** [OAuthSwift/OAuthSwift#293]
### Description:

Hi @phimage Im having the same issues and I get this as a response:

`Response-Body=Optional("{\"meta\":{\"status\":400,\"msg\":\"Bad Request\"},\"response\":{\"errors\":[\"Post cannot be empty.\"]}}")}]`

my code is the following

```
 @IBAction func postTextBlog(_ sender: AnyObject) {
        print(oauth1swift?.parameters)
        
        let headers = ["Accept": "application/json", "Content-Type":"application/json"]
        
        let parameters = [ParameterKeys.BlogType:ParameterValues.MarkdownType, ParameterKeys.Body:textBlog.text] as [String : Any]
        
        oauth1swift?.client.request(TMClient.sharedInstance().tumblrURL(withPathExtension: Methods.PostText), method: .POST, parameters: parameters, headers: headers, success: {
            (data, error) in
            let json = TMClient.sharedInstance().convertToJSONObject(data: data)
            print(json)
            print("hello")
            
            }, failure: {
                error in
                print(error)
        })
        

    }
```
(TMClient.sharedInstance().tumblrURL(withPathExtension: Methods.PostText) is essentially this: 
URL: https://api.tumblr.com/v2/blog/idelfonsog2.tumblr.com/post

you can also see it below
```
OAuthSwiftError.response=<NSHTTPURLResponse: 0x60000022dc80> { URL: https://api.tumblr.com/v2/blog/idelfonsog2.tumblr.com/post } { status code: 400, headers {
    Connection = "keep-alive";
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Tue, 18 Oct 2016 02:01:00 GMT";
    P3P = "CP=\"Tumblr's privacy policy is available here: https://www.tumblr.com/policy/en/privacy\"";
    Server = openresty;
    "Set-Cookie" = "tmgioct=5805825c60e2e80081398740; expires=Fri, 16-Oct-2026 02:01:00 GMT; Max-Age=315360000; path=/; domain=.tumblr.com; HttpOnly";
```

### OAuth Provider (Twitter, Github, ..): 
Tumblr

### OAuth Version:
- [x] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [x] Manually

### Library version:
- [ ] head
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
I think the OAuthSwiftErroris not fully paster here (but I can see before the \"Post cannot be empty.\")

I think you can try to remove the "headers" variable. I think it's for GET request, to specify the format you want in response

Then could you post the content of "parameters"? ParameterValues.MarkdownType == "text" ??

**Comment by idelfonsog2** [comment]
Thanks @phimage let me try that! 

the contents of ParameterValues.MarkdownType == "markdown"

**Comment by idelfonsog2** [comment]
Also, where should I include the "Title" and "Body text" in my request? essentially I'm trying to publish a new post in Tumblr

**Comment by phimage** [comment]
`parameters` is a good place to add that, that why I ask you to past yours here

```swift
let parameters = [
"type": "text",
"format": "markdown",
"body": "my blog text" // maybe "my%20blog%20text"
]
```

**Comment by idelfonsog2** [comment]
# Huge Thanks!!!!!! 🙇 

### that definitely worked!!!!

final code was: //future reference or help for anybody

```
oauth1swift?.client.request(TMClient.sharedInstance().tumblrURL(withPathExtension: Methods.PostText), method: .POST, parameters: parameters, headers: nil, success: {
            (data, error) in
            let json = TMClient.sharedInstance().convertToJSONObject(data: data)
            print(json)
            
            }, failure: {
                error in
                print(error)
        })
```
