### ISSUE TITLE
How to retrieve user email

### ISSUE THREAD

**Issue by ahmad-ishfaq** [OAuthSwift/OAuthSwift#294]
### Description:
When the library authenticates a user for facebook, it returns only user name and facebook id.I want to retrieve user email also

### OAuth Version:
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :

### Installation method:
- [x] CocoaPods

### Library version:
- [x] v1.0.0

### Xcode version:
- [x] 8.0 (Swift 3.0)

**Comment by phimage** [comment]
I think it's not a OAuthSwift issue, but a facebook api question...

ps: google is your friend : facebook api get user email
-> scope=email
