### ISSUE TITLE
Instagram login error: serverError("No access_token, no code and no error provided by server")

### ISSUE THREAD

**Issue by brdimattia** [OAuthSwift/OAuthSwift#295]
### Description:  Instagram login not working returns an error: 

serverError("No access_token, no code and no error provided by server")

after login and callback through heroku redirect

full code below: 

```
let oioswift = OAuth2Swift(
            consumerKey:    "********",
            consumerSecret: "*******",
            authorizeUrl:   "https://api.instagram.com/oauth/authorize",
            responseType:   "token"
        )
        
        let state = generateState(withLength: 20)
        oioswift.authorizeURLHandler = SafariURLHandler(viewController: self, oauthSwift: oioswift)
        let _ = oioswift.authorize(
            withCallbackURL: URL(string: "https://herokuappsitename.herokuapp.com/")!, scope: "relationships", state:state,
            success: { credential, response, parameters in
                print("Authenticted with Service <Instagram>")
            },
            failure: { error in
                print("Instagram error is: " , error)
            }
        )
```

### OAuth Provider (Twitter, Github, ..):
Instagram 

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [x] Manually

### Library version:
- [ ] head
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
Somewhere in your code you must have done  " OAuthSwift.handle(url: )"
The url is from provider redirection which add some info to your callbackurl
Can you check the value of this url. The query of this url must contain one of this parameters : access_token, code, error

Then you deploy your own herokuapp?

**Comment by phimage** [comment]
see #258 and https://github.com/OAuthSwift/OAuthSwift/wiki/Instagram
Did you follow this intruction? (Disable implicit OAuth)
