### ISSUE TITLE
Instagram authorizeWithCallbackURL never called

### ISSUE THREAD

**Issue by jjjeeerrr111** [OAuthSwift/OAuthSwift#297]
### Description:

 When trying to authenticate with Instagram, after typing in username and password I see successful login data but I am never redirected back to the app and the authorize completion block is never handled. Here is my code:

```
 @IBAction func loginButtonPressed(_ sender: UIButton) {
    let oauthswift = OAuth2Swift(
        consumerKey:    "***",
        consumerSecret: "****",
        authorizeUrl:   "https://api.instagram.com/oauth/authorize",
        responseType:   "code"
    )
    self.oauthswift = oauthswift
    //oauthswift.authorizeURLHandler = getURLHandler()
    let _ = oauthswift.authorize(
        withCallbackURL: URL(string: "http://54.213.72:8010/login")!,
        scope: "basic+public_content+follower_list+relationships", state:"INSTAGRAM",
        success: { credential, response, parameters in
            print("PRINT SUCCESS")
            print(credential.oauthToken)
        },
        failure: { error in
            print("PRINT ERROR")
            print(error.localizedDescription)
        }
    )

}
```
### OAuth Version:
- [ ] Version 1
- [x] Version 2
### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :
### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually
### Library version:
- [ ] head
- [x] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)
### Xcode version:
- [x] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)
- [ ] objective c

**Comment by phimage** [comment]
#295 just closed now but open when you creating this bug
before opening an issue read contribution guide  (link available when you create an issue)

**Comment by jjjeeerrr111** [comment]
@phimage Im not sure what this means. Are you saying we cannot use the explicit method (server-side)?

**Comment by phimage** [comment]
I don't know but last time I test, that doesn't work (maybe just momentary)

Then your issue title "Instagram authorizeWithCallbackURL never called " is wrong...
are you talking about success and failure block...

Did you call "OAuthSwift.handle(url: url)" somewhere in your code and how you do it? (application scheme, url detection in webview, ...)
