### ISSUE TITLE
I can't stub request with OHHTTPStubs

### ISSUE THREAD

**Issue by ivanruizscm** [OAuthSwift/OAuthSwift#298]
### Description:

Im trying in my test target to stub request made by OAuthSwift. I dont know why but i can't stub those requests. If i made a simply URLSession.dataTaskWithURL the stubs just works, but if i do the request with oauth no. I see in the code that internally those request are made with URLSession so its very strange
### OAuth Version:
- [ ] Version 1
- [x] Version 2
### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :
### Installation method:
- [ ] Carthage
- [x ] CocoaPods
- [ ] Manually
### Library version:
- [ ] head
- [x] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)
### Xcode version:
- [x ] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)
- [ ] objective c

**Comment by phimage** [comment]
no code provided
no error message
invalid
