### ISSUE TITLE
Missing CONTRIBUTING.md

### ISSUE THREAD

**Issue by mikegray** [OAuthSwift/OAuthSwift#299]
### Description:
The README.md file says "See CONTRIBUTING.md", but that file doesn't exist.

### OAuth Provider (Twitter, Github, ..):
None.

### OAuth Version:
- [ ] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [ ] Manually

### Library version:
- [x] head
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
file moved to new .github directory
then when you create issue you have a link ;)

**Comment by phimage** [comment]
fixed thx
