### ISSUE TITLE
WordPress support

### ISSUE THREAD

**Issue by phamdacloc** [OAuthSwift/OAuthSwift#303]
### Description:
Would it be possible to add Wordpress support in this plugin? There are quite a few number of wordpress website and it would be great to have client apps interfacing with wordpress websites.

### OAuth Provider (Twitter, Github, ..):
WP REST API - OAuth 1.0a Server

### OAuth Version:
- [x ] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [x] OSX :
- [x] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [x] Manually

**Comment by phimage** [comment]
Hi
Before asking did you try?
Did you read wordpress oauth documentation? could you provide a link?

If is not working, add information that prove it, error dump, etc.. ie. create a real issue, not a feature request
If it's work, then you can make a PR to add it into the demo app
 https://github.com/OAuthSwift/OAuthSwift/wiki/Demo-application#add-a-new-service-in-demo-app
