### ISSUE TITLE
No such module 'OAuthSwift' error

### ISSUE THREAD

**Issue by phamdacloc** [OAuthSwift/OAuthSwift#305]
I'm trying to use the OAuthSwift Framework in my swift app and I get the error "No such module 'OAuthSwift' " when I import OAuthSwift.

I followed the following instructions from the github read:

> Drag OAuthSwift.xcodeproj to your project in the Project Navigator.
> Select your project and then your app target. Open the Build Phases panel.
> Expand the Target Dependencies group, and add OAuthSwift framework.
> Import OAuthSwift whenever you want to use OAuthSwift.

I also tried using CocoaPod and it's having the same problem. I'm using XCode version 7.3.1

Thanks

**Comment by phimage** [comment]
why did you remove the issue template???
Now I must loose time and ask question
OAuthSwift master head version (1.0.0) is Xcode8 and swift 3. Try with older version (branch or tag)

**Comment by phamdacloc** [comment]
Upgraded to xCode 8.1 worked. Thanks
