### ISSUE TITLE
Error Info: Type 'OAuthSwift' has no member 'sessionConfiguration'

### ISSUE THREAD

**Issue by maundytime** [OAuthSwift/OAuthSwift#310]
### Description:

build error in these code lines
<img width="1171" alt="2016-11-12 1 58 04" src="https://cloud.githubusercontent.com/assets/3490007/20236022/1342557a-a8e0-11e6-95ba-58f7ae206d31.png">

#if os(iOS)
#if !OAUTH_APP_EXTENSIONS
UIApplication.shared.isNetworkActivityIndicatorVisible = OAuthSwift.sessionConfiguration.isNetworkActivityIndicatorVisible
#endif
#endif

Error Info: Type 'OAuthSwift' has no member 'sessionConfiguration'

### OAuth Provider (Twitter, Github, ..):
Nothing

### OAuth Version:
- [x] Version 1

### OS (Please fill the version) :
- [x] iOS :

### Installation method:
- [x] Manually

### Library version:
- [x] head

### Xcode version:
- [x] 8.1 (Swift 3.0)

**Comment by phimage** [comment]
my bad, has been renamed to `session`. Will fix now. thx
