### ISSUE TITLE
Can we tag latest commits?

### ISSUE THREAD

**Issue by robertmryan** [OAuthSwift/OAuthSwift#312]
### Description:

When I update via Carthage 0.18.1, I get the following error:

<pre>
$ carthage update --platform macOS
*** Fetching OAuthSwift
*** Checking out OAuthSwift at "1.1.0"
*** xcodebuild output can be found in /var/folders/jr/lhvt2ks57fg_fwtz8mnmwxr80000gn/T/carthage-xcodebuild.FHfXl7.log
*** Building scheme "OAuthSwiftOSX" in OAuthSwift.xcworkspace
/Users/rryan/.../Carthage/Checkouts/OAuthSwift/Sources/OAuthSwiftHTTPRequest.swift:142:42: warning: expression implicitly coerced from 'String?' to Any
/Users/rryan/.../Carthage/Checkouts/OAuthSwift/Sources/OAuthSwiftHTTPRequest.swift:143:55: warning: expression implicitly coerced from 'String?' to Any
/Users/rryan/.../Carthage/Checkouts/OAuthSwift/Sources/OAuthSwiftHTTPRequest.swift:142:42: warning: expression implicitly coerced from 'String?' to Any
/Users/rryan/.../Carthage/Checkouts/OAuthSwift/Sources/OAuthSwiftHTTPRequest.swift:143:55: warning: expression implicitly coerced from 'String?' to Any
/Users/rryan/.../Carthage/Checkouts/OAuthSwift/Sources/OAuthSwiftHTTPRequest.swift:142:42: warning: expression implicitly coerced from 'String?' to Any
/Users/rryan/.../Carthage/Checkouts/OAuthSwift/Sources/OAuthSwiftHTTPRequest.swift:143:55: warning: expression implicitly coerced from 'String?' to Any
/Users/rryan/.../Carthage/Checkouts/OAuthSwift/Sources/OAuthSwiftError.swift:137:53: warning: expression implicitly coerced from 'Error?' to Any
</pre>

In diagnosing this, it appears that these have been fixed in commits subsequent to the last tag. Can we please add a new tag when we do fixes so that Carthage will grab these. If you don't tag it, Carthage won't grab it.

When I forked it and added a tag bumping the revision number, as shown below, it got the latest and greatest:

<pre>
$ git tag -a 1.1.1 -m "Version 1.1.1"
$ git push --tags
</pre>

When I did that, and then changed the `Cartfile` to point to my fork, it worked fine.

I can submit this as a pull request, but it seems that incrementing the revision number should just be part of every commit.

### OAuth Provider (Twitter, Github, ..):

N/A 

### OAuth Version:
- [ ] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [ ] iOS :
- [x] macOS :
- [ ] tvOS :
- [ ] watchOS  :

### Installation method:
- [x] Carthage
- [ ] CocoaPods
- [ ] Manually

### Library version:
- [x] head
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 8.1 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)
- [ ] objective c

**Comment by phimage** [comment]
done
thx
