### ISSUE TITLE
Help needed with Multipart upload

### ISSUE THREAD

**Issue by antwerpenR** [OAuthSwift/OAuthSwift#313]
I have been using OAuthSwift for some time successfully to read data from meetup.com.  I can also do some simple .POST (eg comments upload).....but I am stuck on how to do Photo Upload.

Can you show some sample code for the MultiPart upload  and/or give any tips/suggestion for how to use OAuthSwift for this endpoint:  https://www.meetup.com/meetup_api/docs/2/member_photo/#create

### OAuth Version:
- [ XX] Version 2

### OS (Please fill the version) :
- [x] iOS :

### Installation method:
- [X ] CocoaPods

### Library version:
- [X ] head

### Xcode version:
- [X ] 8.0 (Swift 3.0)

**Comment by phimage** [comment]
I am sure how to achieve this, I don't use this functionality.
```swift
let fileData = OAuthSwiftMultipartData(name: "photo", data: data, fileName: fileName, mimeType: mimeType)
let multiparts = [fileData]
client.postMultiPartRequest(urlString, method: .post, multiparts: multiparts)
```
`data` is `Data' from file
if you can find mime type, put nil

I don't know if you can pass other parameters using `parameters` dictionary
For other parameters, try to put it in query

**Comment by antwerpenR** [comment]
Thanks!  That is what I needed.  The answer was staring me in the face!  The error message that I was getting was that field "photo" was required....but I could not think where to put it and then I realised that this is what the "name" parameter should be.   All working fine.  Thanks again
