### ISSUE TITLE
Instagram: No access_token, no code and no error provided by server

### ISSUE THREAD

**Issue by tecexpert** [OAuthSwift/OAuthSwift#315]
### Description:
Unable to login via Instagram. I installed the latest version of this library to see if it is resolved but it's not. So posting this issue again. Kindly refer me to the solution.

### OAuth Provider (Twitter, Github, ..):
Instagram

### OAuth Version:
- [o] Version 2

### OS (Please fill the version) :
- [10] iOS 

### Installation method:
- [o] Manually

### Library version:
- [1.1.1] other: (Please fill in the version you are using.)

### Xcode version:
- [o] 8.0 (Swift 3.0)

**Comment by phimage** [comment]
https://github.com/OAuthSwift/OAuthSwift/wiki/Instagram
 or read others issue by looking for keyword "instagram"
