### ISSUE TITLE
Missing renewAccessToken objc

### ISSUE THREAD

**Issue by Hendrik44** [OAuthSwift/OAuthSwift#316]
### Description:
The function "renewAccessToken" is missing when using OAuthSwift at Version 1.1.0 or later in an objective-c-project. Maybe it only need to be add in Objc.swift?

### OAuth Provider (Twitter, Github, ..):
OAuth2 Provider for own service, with Version 0.6.0 the function can call directly und OAuth workflow is fine.

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [x] Carthage
- [ ] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [ ] v1.0.0
- [ ] v0.6
- [x] other: 1.1.1

### Xcode version:
- [ ] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [x] other: 8.1

- [x] objective c

**Comment by phimage** [comment]
yes in objc.swift we must add
```swift
    open func objc_renewAccessToken(withRefreshToken refreshToken: String, headers: OAuthSwift.Headers? = nil, success: @escaping TokenSuccessHandler, failure: Obj_FailureHandler?) -> OAuthSwiftRequestHandle? {
  // here call renewAccessToken
}
```

**Comment by Hendrik44** [comment]
Will anyone merge it into the repo or should i do an pull-request?

**Comment by phimage** [comment]
please do the PR, thx in advance
write Fix #<this bug number> into the commit message
