### ISSUE TITLE
Appdelegate method support for obj-c

### ISSUE THREAD

**Issue by randradedasilva** [OAuthSwift/OAuthSwift#318]
### Description:
Appdelegate in my project was code with objective-c . How can i add appdelegate method into a appdelegate.m ?

### OAuth Version:
- [ ] Version 1
- [x] Version 2
### OS (Please fill the version) :
- [x] iOS 
### Installation method:
- [x] CocoaPods
### Library version:
- [x] v0.6
### Xcode version:
- [x] 7.3.1

- [x] objective c

**Comment by phimage** [comment]
Not OAuthSwift issue. Go to stackoverflow or let xcode create your appdelegate code
