### ISSUE TITLE
Unable to infer closure type in the current context

### ISSUE THREAD

**Issue by Aximem** [OAuthSwift/OAuthSwift#319]
Sorry if this is a dumb question (I'm a beginner) but I can't find a way to resolve this. TY

<img width="834" alt="capture d ecran 2016-12-08 a 20 40 43" src="https://cloud.githubusercontent.com/assets/18660012/21025068/508d4096-bd87-11e6-9457-62631d457c0c.png">

**Comment by phimage** [comment]
please next time do not remove the issue template
