### ISSUE TITLE
Unable to infer closure type in the current context

### ISSUE THREAD

**Issue by Aximem** [OAuthSwift/OAuthSwift#320]
### Description: 
Sorry for previous issue, I'm trying to set Auth2 for Facebook but I always get 

> unable to infer closure type in the current context

I have OAuthSwift at "1.1.1". If I do : 
`success: { response in`
I don't have the error. I'm a beginner, sorry if it is a dumb question.

<img width="834" alt="capture d ecran 2016-12-08 a 20 40 43" src="https://cloud.githubusercontent.com/assets/18660012/21031569/72068e18-bda4-11e6-8c1a-89be1a31d215.png">

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS : 10.1
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [x] Carthage
- [ ] CocoaPods
- [ ] Manually

### Library version:
- [x] head
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
in last/head version `oauth_version` is `oauthToken`

**Comment by Aximem** [comment]
Thanks @phimage ;) 

Btw this is oauth_token => oauthToken exactly.
