### ISSUE TITLE
Can someone help me with oauth 2 for yelp?

### ISSUE THREAD

**Issue by Hsanka6** [OAuthSwift/OAuthSwift#321]
### Description:
Need help setting oauth 2 for yelp
### OAuth Provider (Twitter, Github, ..):
yelp

### OAuth Version:
- [ ] Version 1
- [X] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [X] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [x] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [X ] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
first google yelp oauth and post yelp documentation link here

**Comment by phimage** [comment]
no answer, I close
