### ISSUE TITLE
Help required to get json response from wordpress URl

### ISSUE THREAD

**Issue by hemanth2k13** [OAuthSwift/OAuthSwift#322]
### Description:
 I need to send oauth1 authorization request to wordpress api, to get json response of products and so. I am not able to get the flow of implementation and make requests. I'm new to iOS/Swift. Need help.

### OAuth Version:
- [x] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
did you look into demo app code?

**Comment by hemanth2k13** [comment]
my wordpress/woocommerce url is http://lensinteractive.com/aranyani/wp-json/wc/v1/products. But I don't know about request, authorise and access token url. i tried http://lensinteractive.com/aranyani/oauth/request but i get 404 error.

**Comment by phimage** [comment]
You do not read my comment and answer my question
If you look for somewone who do the job for you, it's not here. I have already provided help. I close
