### ISSUE TITLE
Issue when trying to handle the callback is going to the failure callback everytime

### ISSUE THREAD

**Issue by Miguelme** [OAuthSwift/OAuthSwift#324]
### OAuth Provider (Twitter, Github, ..):
AirService

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [x] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

I'm having troubles with the function:  oauthswift.authorize

It's going to the failure  callback all the time and throwing the following error : 
(OAuthSwiftError error -10.) 

And I don't find any doc to know how to fix it or what is going wrong. Any help will be appreciated

PS: The App open url  in the AppDelegate Method is the following: 

```
func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
        print("In App open Url! with url.host = " + url.host!)
        print("options \(options)")
        if (url.host == "oauth2Callback") {
            print("Right host! calling handle!")
            OAuthSwift.handle(url: url)
        }
        return true
    }

```

**Comment by phimage** [comment]
https://github.com/OAuthSwift/OAuthSwift/blob/master/Sources/OAuthSwiftError.swift

10 - retain error

you do not retain oauthSwift object
