### ISSUE TITLE
Trying to authenticate GitHub API but success or failure doesn't run

### ISSUE THREAD

**Issue by dannymout** [OAuthSwift/OAuthSwift#328]
### Description:
This is the code I'm using:
````
        oauthswift = OAuth2Swift(consumerKey: "XXXXXXXXXXXXXXXXXXX", consumerSecret: "XXXXXXXXXXXXXXXXXXX", authorizeUrl: "https://github.com/login/oauth/authorize", responseType: "token")
        
        let handle = oauthswift.authorize(withCallbackURL: "app-name://oauth-callback?code=", scope: "user+repo", state: "", success: { credential, response, parameters in
            print(credential.oauthToken)
        }, failure: { error in
            print(error.localizedDescription)
        })
    }
````
When I run it nothing is happening. `success` doesn't run, neither does `failure`.

Also, `consumerKey` and 'consumerKey' are filled in with the client ID and client secret on my end. `app-name` is also the actual name of the app on my end.

### OAuth Provider (Twitter, Github, ..):
GitHub

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [ ] v1.0.0
- [ ] v0.6
- [x] other: (v1.1.0)

### Xcode version:
- [x] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
Try a no empty State
Try scope 'user', or encore scope (maybe there is an issue)

I don't know github callback URL recommandation but why there is "code="

**Comment by dannymout** [comment]
@phimage I'll give it a try. There is `?code=` because when I tested the link in my browser, the url looked like `app-name://oauth-callback?code=XXXXXXXXXX`

**Comment by dannymout** [comment]
@phimage So I did a bit more reading about the GitHub API. I feel like I've somewhat figured it out.

**Comment by dannymout** [comment]
@phimage OK, so I did a bit more reading on the GitHub API. So, I've figured out a bit more on how it works. First, the app needs to send the user to GitHub to sign in and grant permission to the app. After that, it redirects back to the app and returns something like this `app-name://oauth-callback?code=XXXXXXX`. The code provided is used to get an access token, so next the app has to make a request to a URL like this `https://github.com/login/oauth/access_token?client_id=XXXXXXX&client_secret=XXXXXXX&code=XXXXXXX&state=XXXXXXX`. Finally, the response would look like this `access_token=e72e16c7e42f292c6912e7710c838347ae178b4a&scope=user%2Cgist&token_type=bearer`, giving you the access token. How would I do this with OAuthSwift? The more detailed documentation on this is here: https://developer.github.com/v3/oauth/#1-redirect-users-to-request-github-access.

**Comment by phimage** [comment]
You describe normal oauth flow. So this must be done automatically by OAuthSwift

**Comment by dannymout** [comment]
So turns out, there is an example of how to use the GitHub API with OAuthSwift in the repo, but I'm now having difficulty with that, I'm going to start a new issue.

**Comment by dannymout** [comment]
@phimage  Updated the code, here it is:
````
let oauthswift = OAuth2Swift(
            consumerKey: "XXXXXXXXXXXXX",
            consumerSecret: "XXXXXXXXXXXXX",
            authorizeUrl: "https://github.com/login/oauth/authorize",
            accessTokenUrl: "https://github.com/login/oauth/access_token",
            responseType: "code"
        )
        
        self.oauthswift = oauthswift
        
        oauthswift.authorizeURLHandler = OAuthSwiftOpenURLExternally.sharedInstance
        
        let state = generateState(withLength: 20)
        
        let _ = oauthswift.authorize(withCallbackURL: "oauth-test://oauth-callback", scope: "user", state: state, success: { credential, response, parameters in
            print(credential.oauthToken)
        }, failure: { error in
            print(error.localizedDescription)
        })
````

It redirects to Safari and lets me sign-in to GitHub, but when it redirects to my app, nothing prints, no token or error. Neither `success` or `error` runs.  Also, this is in the [example code](https://github.com/OAuthSwift/OAuthSwift/blob/master/Demo/Common/ViewController.swift#L298), I'm using mostly the same code.

**Comment by dannymout** [comment]
Also, Xcode shows that there's no network activity from the app.

**Comment by kpfefferle** [comment]
@dannymout Did you set up the URL scheme to handle the GitHub redirect per the instructions [here](https://github.com/OAuthSwift/OAuthSwift#setting-url-schemes) and [here](https://github.com/OAuthSwift/OAuthSwift#handle-url-in-appdelegate)? This is required to handle the response from GitHub before either the success or failure closures will execute.

**Comment by dannymout** [comment]
@kpfefferle Yes, I setup the URL schemes and I put the code in the AppDelegate. I didn't add `if (options["UIApplicationOpenURLOptionsSourceApplicationKey"] as? String == "com.apple.SafariViewService") {` not sure if I need it. If so, where am I suppose to put that piece of code?

**Comment by dannymout** [comment]
@kpfefferle I forgot something in the AppDelegate, I put the if statement, but forgot to add something to the parameters.
