### ISSUE TITLE
Custom grant flow

### ISSUE THREAD

**Issue by aliasdoc** [OAuthSwift/OAuthSwift#329]
### Description:
Hi,

Is possible to use this library with a custom oath flow ?? For my personal needs, I have an oauth server with a custom grant flow for social login (like password grant flow but with custom params). I need to transmit these JSON params in body:
```

- grant_type = social
- client_id = ...
- client_secret = ...
- network = Facebook
- access_token ...

```
and receive a JSON response like this:
```

- token_type = Bearer
- expires_in = ...
- access_token = ...
- refresh_token = ...

```

Thanks.

### OAuth Provider (Twitter, Github, ..):

I use a custom provider with a custom grant flow (like password grant flow but with custom params) made for social login.

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [x] head
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
I think that it is not supported (only Authorization Code grant type or implicit is supported)
You can't provide a Doc link?

**Comment by aliasdoc** [comment]
Thank you @phimage, I don't have doc for this flow, it's just a password grant flow with username and password parameters renamed with network and access_token.

**Comment by phimage** [comment]
ok I see
until password grant flow is not supported, I can't provide a way to do this
but when someone or I implement it, I will remember that "username" and "password"  parameters name must be customisable

**Comment by aliasdoc** [comment]
Thank you @phimage.

**Comment by oshitub123** [comment]
i have a question  i need to do a implicit grant how i do it do you have any example code

**Comment by oshitub123** [comment]
??

**Comment by oshitub123** [comment]
thank you @phimage
