### ISSUE TITLE
Use custom HTTP header for Bearer token?

### ISSUE THREAD

**Issue by underbjerg** [OAuthSwift/OAuthSwift#330]
### Description:

We would like to be able to configure which header to use for passing the token in requests. Currently the OAuthSwiftClient is hardcoded to use the "Authorization" header. We would like to be able to use "X-Authorization" instead.

Other than modifying the framework code, can you suggest a solution? Or consider it as a feature request?

### OAuth Provider (Twitter, Github, ..):

Custom backend.

### OAuth Version:
- [ ] Version 1
- [X] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [X] Manually

### Library version:
- [ ] head
- [X] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [X] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
You can set into credential object a `OAuthSwiftCredentialHeadersFactory`
`oauthSwift.client.credential.headersFactory=<your custom object>`

get the token like this `oauthSwift.client.credential` or extends `OAuthSwiftCredential`

and in your custom object
`return token.isEmpty ? [:] : ["X-Authorization": "Bearer \(token)"]`

**Comment by underbjerg** [comment]
Perfect, just the answer I was looking for. I'll give it a try.

And thank you very much for the swift reply!

**Comment by phimage** [comment]
new wiki page
https://github.com/OAuthSwift/OAuthSwift/wiki/Custom-authentication-headers

**Comment by underbjerg** [comment]
Excellent! Much appreciated :)
