### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by nawar** [OAuthSwift/OAuthSwift#331]
### Description:
Change the user agent to that of Safari to bypass Google's check on browser
### OAuth Provider
Google

I'm just wondering why you are not enforcing the `User-Agent` to be that of Safari's to avoid having the final load request, after the login, to be redirected to the heroku app, and instead, intercept it using `shouldStartLoadWith:request:navigationType` of `UIWebViewDelegate` ?

**Comment by phimage** [comment]
I don"t understand very well your suggestion

First the choice of `authorizeURLHandler`is yours and could be a `SFSafariViewController`, a uiwebview, a wkwebview etc...
I think User Agent is also your choice, not OAuthSwift choice

demo app use `UIWebViewDelegate` and implement `shouldStartLoadWith:request:navigationType`
like I do in OSX code demo , yes you can intercept request to avoid URL scheme redirection method
there is a wiki page to explain that https://github.com/OAuthSwift/OAuthSwift/wiki/API-with-only-HTTP-scheme-into-callback-URL
 this is demo app so it's not the main framework

**Comment by nawar** [comment]
No worries. All that I was trying to say is, because how Google only accepts authentication requests coming from a browser, not a web view embedded within the app (I didn't try using WKWebView though), I feel that the web page redirection solution is not optimal. That's the reason I suggested to enforcing the UserAgent as it'll keep the authentication process within the app itself, without the need to spin-off a server just for that redirection. 

I'll just close this.
