### ISSUE TITLE
Don't work with swift 2.3

### ISSUE THREAD

**Issue by PaulLafitskyi** [OAuthSwift/OAuthSwift#333]
### OAuth Version:
- [ ] Version 1
- [x ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [x] head
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ ] 8.0 (Swift 3.0)
- [x] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

![screen shot 2017-02-03 at 5 17 32 pm](https://cloud.githubusercontent.com/assets/8931303/22596552/b96008f4-ea34-11e6-8513-14604d1f387e.png)

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'
        end
    end
end
```

**Comment by PaulLafitskyi** [comment]
![screen shot 2017-02-03 at 5 29 55 pm](https://cloud.githubusercontent.com/assets/8931303/22597009/75320b58-ea36-11e6-955d-0e41d59fe16e.png)
The same story if we try to use it like a Swift framework as in description.

**Comment by phimage** [comment]
Have you set the 2.3 branch in your podfile?
Issue description say 'head' version, not 0.6

**Comment by PaulLafitskyi** [comment]
Oh, my bad. I missed it.

**Comment by DebanjanChakrabortyCN** [comment]
I'm facing the same issue. 
Below is my podfile excerpt.


The project is being run in xcode 7.3, swift 2.3.
After downloading, build gives me an entire list of errors
target 'TestApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	pod 'Alamofire', '~> 3.5'
    pod 'OAuthSwift', '1.1.0'

  # Pods for PCC

end

**Comment by phimage** [comment]
@DebanjanChakrabortyCN 
same issue so, read the answer...

**Comment by PaulLafytskyi** [comment]
@DebanjanChakrabortyCN Select the branch with your swift version. 
For swift 2.3 try next.

```
platform :ios, '8.0'
use_frameworks!

pod 'OAuthSwift', '~> 0.5.0'
```
