### ISSUE TITLE
authorizeURLHandler: How do I know when OAuthSwift has sent the user to Safari?

### ISSUE THREAD

**Issue by dannymout** [OAuthSwift/OAuthSwift#338]
### Description:
In my app, I want to get a token, so I'll send my user to the OAuth provider, I'm doing this by redirecting them to Safari:

`OAuthSwift.authorizeURLHandler = OAuthSwiftOpenURLExternally.sharedInstance`

Everything works perfectly, but one question: How do I know when my app has sent the user to Safari?

### OAuth Provider (Twitter, Github, ..):
Not important.

### OAuth Version:
- [ ] Version 1
- [X] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [X] CocoaPods
- [ ] Manually

### Library version:
- [X] head
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [X] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
the oauth flow with `OAuthSwiftOpenURLExternally` :

- safari is launched
- safari open the login page for the specific provider
  - safari have its own cookies, so user could be already logged 
- after success full login, callback url is call (and must open your app using url scheme with token as  query or fragment parameters)

there is no user information sent from the app to safari

**Comment by dannymout** [comment]
@phimage Correct, but when using `OAuthSwiftOpenURLExternally`,  the app will automatically send the user to Safari, I don't need any user data. I just want to know when OAuthSwift has redirected to Safari. Is there a way to do that?

**Comment by phimage** [comment]
there is no "user" send to safari
just url open with on iOS : UIApplication.shared.openURL(url)

If you use OAuth version 2, just after calling `authorize` safari is open immediately
 So you know when it's done, because you call `authorize`

for oauth version 1 is more complicated, there is before a request to the server


Then if you want a clean way to do this, implement your own `OAuthSwiftURLHandlerType` and use it
```swift
open class MonitoredHandler: OAuthSwiftURLHandlerType {

    public static var sharedInstance : MonitoredHandler = MonitoredHandler()
        
    @objc open func handle(_ url: URL) {
        // TODO : here send event : safari will open
         OAuthSwiftOpenURLExternally.handle(url)
       // TODO : here send event : safari did open
    }
}
```


just for information, OAuthSwiftOpenURLExternally is not recommend, apple do not allow it I think
so for ios9 there is SafariURLHandler with a delegate to know where safari is initialized

**Comment by dannymout** [comment]
@phimage OK, so there is a way to open URLs in Safari, that would allow me to get approved by the App Store: 
````swift
UIApplication.shared.open(NSURL(string:"http://www.reddit.com/") as! URL, options: [:], completionHandler: nil)
````

How would I set the URL handler to work with that?

**Comment by phimage** [comment]
not in Safari but `SFSafariViewController` using OAuthSwift  `SafariURLHandler`

and for your question, I don't really understand why you want to open in safari a reddit url... nothing in relation with OAuth

`UIApplication.shared.open(url)` is equivalent to `OAuthSwiftOpenURLExternally.handle(url)`

**Comment by dannymout** [comment]
@phimage What would I put in `url`? The example I found had the reddit url in it.

**Comment by dannymout** [comment]
@phimage So I would do this, right?:
oauthswift.authorizeURLHandler = OAuthSwiftOpenURLExternally.handle(url)

but what would I put in URL?
