### ISSUE TITLE
'/' replaced with %252F in URL [Instagram]

### ISSUE THREAD

**Issue by f-holland** [OAuthSwift/OAuthSwift#339]
### Description:

My URL is being encoded and all the slashes ( / ) are being replaced with %252F.
Also, my colons ( : ) are being replaced with %253A. My code is just here:
https://hastebin.com/deninuloza.lua

### OAuth Provider (Twitter, Github, ..):
- Instagram

### OAuth Version:
- [ ] Version 1
- [X] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [X] Manually

### Library version:
- [ ] head
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [X] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by IMcD23** [comment]
I'm having a similar issue. Seems to be caused by [this commit.](https://github.com/OAuthSwift/OAuthSwift/commit/e56fafadc8a0db781ab51e45eb0522d70058026c)

**Comment by f-holland** [comment]
Managed to get it working by just deleting the .urlEncodedString
I just expanded the OAuthSwift.xcodeproj and simply deleted the line in Sources/OAuth2Swift.swift
Command+F to find the queryString and re-ran my project and it's worked!

**Comment by IMcD23** [comment]
Yeah I've reverted my project to before that commit and it's working fine. @phimage, let's get this reverted if possible. It's breaking for me specifically with GitHub and GitLab APIs. Haven't tested any more yet, but I'm assuming it's broken for others as well.

**Comment by phimage** [comment]
please don't close until issue fixed
yes I will revert (and put a boolean to encode)
