### ISSUE TITLE
SFSafariViewController dismisses two times after pressing Done

### ISSUE THREAD

**Issue by yjb94** [OAuthSwift/OAuthSwift#341]
### Description:
```
let handler = SafariURLHandler(viewController: vc, oauthSwift: instaOAuth)
handler.factory = { url in
     return SocialSafariViewController(url: url)
}
```
SocialSafariViewController has no other special function dismissing.

here is my logic

i open twitter to auth(with SFSafari) -> i press done(without authentication) -> i open twitter again -> i login to twitter account and finish authorize -> redirects to my app -> the SafariURLHandler dismisses my modal view as well(it occurs dismiss two times)

need fix

### OAuth Provider (Twitter, Github, ..):
twitter / instagram

### OAuth Version:
- [o] Version 1
- [o] Version 2

### OS (Please fill the version) :
- [o] iOS : 10.0.2
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [o] CocoaPods
- [ ] Manually

### Library version:
- [o ] head
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [o] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
You can call on your `SafariURLHandler` the function `clearObservers`
(there is also `cancel` method on `OAuthSwift` object)

Must be call automatically by `safariViewControllerDidFinish` in [OAuthSwiftURLHandlerType](https://github.com/OAuthSwift/OAuthSwift/blob/master/Sources/OAuthSwiftURLHandlerType.swift), but if there is some issue, you can put a break point
Pressing "Done" close the window without passing here?

**Comment by phimage** [comment]
I cannot reproduce it in demo app
I press Done for twitter first time
Then I retry twitter auth, and enter my user credential, authorize the app
I have only one dismiss
In demo a `SafariURLHandler` is created each time we try to connect

then `SocialSafariViewController` is unknown for me, you override `SFSafariViewController` ?

I close until there is more information
