### ISSUE TITLE
Issue revoking an access token

### ISSUE THREAD

**Issue by Miguelme** [OAuthSwift/OAuthSwift#343]
### Description:

Is there a way to revokke a token as there is a way to renew the token using the `renewToken` method?

### OAuth Provider (Twitter, Github, ..):

 AirService
### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x ] CocoaPods
- [ ] Manually

### Library version:
- [x ] head
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x ] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)
- [ ] objective c

**Comment by phimage** [comment]
https://github.com/OAuthSwift/OAuthSwift/wiki/OAuth-2.0-Token-Revocation
I think there is no universal way to do it
So you must look into your api provider documentation if there is an URL for that
