### ISSUE TITLE
Could you provide better explanations of the sequence of calls necessary to implement OAuth2 on a MacOS app with OAuthSwift?

### ISSUE THREAD

**Issue by shyamalschandra** [OAuthSwift/OAuthSwift#344]
### Description:

I looked at the demo and at the example code in the README.md but am having problem knowing if I am on the right track besides just "shooting in the dark" by repeatedly compiling and trying different things multiple times.  What should I do?

### OAuth Provider (Twitter, Github, ..):

Twitter

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [] iOS :
- [X] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [X] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [] v1.0.0
- [ ] v0.6
- [X] other: (Please fill in the version you are using.)

1.1.1

### Xcode version:
- [ ] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [X] other: (Please fill in the version you are using.)

8.2.1 with Swift 3.1

- [ ] objective c

**Comment by phimage** [comment]
you can start by posting your code or error message
(you must know closure and DispatchQueue/async to understand OAuthSwift)
