### ISSUE TITLE
Getting error (OAuthSwiftError error -10.) and doesn't open for authorization

### ISSUE THREAD

**Issue by kishore24794** [OAuthSwift/OAuthSwift#347]
Description: 
The operation couldn’t be completed. (OAuthSwiftError error -10.)

OS X Version = 10.10 above
OAuth Version = 1.0
 
Please help out with some steps for authorization.

**Comment by phimage** [comment]
please do not remove issue template

https://github.com/OAuthSwift/OAuthSwift/blob/master/Sources/OAuthSwiftError.swift -> 10 -> retain, retain your object
