### ISSUE TITLE
Error Info : The operation couldn’t be completed. (OAuthSwiftError error -10.)

### ISSUE THREAD

**Issue by megifernanda** [OAuthSwift/OAuthSwift#349]
### Description:

<img width="568" alt="screen shot 2017-03-10 at 4 14 49 pm" src="https://cloud.githubusercontent.com/assets/25347608/23790448/ab134138-05b1-11e7-922f-2991c0dd6e0b.png">

i want to test Authorize 

### OAuth Provider (Twitter, Github, ..):

no provider

### OAuth Version:
- [x] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [x] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [ ] v1.0.0
- [ ] v0.6
- [x] other: (i dont know what version.)

### Xcode version:
- [ ] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [x] other: (Version 8.2.1)

- [ ] objective c

**Comment by phimage** [comment]
http://cocoadocs.org/docsets/OAuthSwift/1.0.0/Enums/OAuthSwiftError.html
10 retain
you do not retain your oautswift object in memory

**Comment by megifernanda** [comment]
and then what must i do sir ?? im really dont know what must i do

**Comment by phimage** [comment]
keep a reference on `oauthswift` variable in your class

```swift
class ViewController: ... {
   var oauthswift: OAuth1Swift?

   func doAuXXX() {

        self.oauthswift = ...

```

ps: then screenshot is very bad in issue, always copy paste your code or error message
and use github markdown for code

**Comment by megifernanda** [comment]
sorry sir, i just see before me shared issue with screenshoot

and i already add variable and still -10

or this problem because my librabry get red sir
<img width="256" alt="screen shot 2017-03-10 at 5 02 07 pm" src="https://cloud.githubusercontent.com/assets/25347608/23790831/55da01d2-05b3-11e7-91b1-9c5b74b1ed0e.png">


`       import UIKit
         import OAuthSwift

       class ViewController: UIViewController {

    var oauthswift: OAuth1Swift?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doAuthPetani()
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }


    func doAuthPetani() {
        
        print ("hei")
       let oauthswift = OAuth1Swift(
        consumerKey:   "Sjt29_vS0RmK6t-QeXsieYn9Kq0.",
        consumerSecret: "YUVeUSiF_I5ZEoZLnD66dQ6pBu4Oi6D96NpyRbJ-Suo.",
        requestTokenUrl: "https://oauth.8villages.com/tokens/request-token",
        authorizeUrl:    "https://accounts.8villages.com/oauth/request-token",
        accessTokenUrl:  "https://accounts.8villages.com/oauth/access-token"
        )
        
        
        let handle = oauthswift.authorize(
            withCallbackURL: URL(string: "OauthTest://oauth-callback")!,
            success: { credential, response, parameters in
                    print ("menda")
        
        },
            failure: { error in
                print ("a")
                print(error.localizedDescription)
        }             
        )

      }
     }
`

**Comment by phimage** [comment]
not `let oauthswift = OAuth1Swift(`

but `self.oauthswift = OAuth1Swift(`
to use your class variable

**Comment by megifernanda** [comment]
its run sir, but i want ask. what is my urlcallback right?

**Comment by phimage** [comment]
please read the readme

your provider 8villages will return information to login using this url
when opening this url your app will call oauthswift.handle(url), and your login is done

**Comment by megifernanda** [comment]
oke sir, and where i can see code for access token?

**Comment by phimage** [comment]
why you want to see it?

in your code you receive `credential` object
```
 success: { credential, response, parameters in
                    print ("menda")
```

**Comment by megifernanda** [comment]
i means, what is code for access token. i can't find it. 

i can't find code for accesstoken in ViewController example

**Comment by phimage** [comment]
you don't need it...
or you want to use an other network framework
