### ISSUE TITLE
how to acces ouath without authorizeUrl

### ISSUE THREAD

**Issue by megifernanda** [OAuthSwift/OAuthSwift#350]
### Description:

before i tried to get token with this code but i just got oauth_token and work but actually my app wihout authorize, so how to make this code without authorizeUrl

if i make authorizeUrl: "https://accounts.8villages.com/oauth/request-token"
my app is work and get token in url browser
but in layout i get error like this

**MethodNotAllowedError**

my code : 

```swift
import UIKit
      import OAuthSwift

    class ViewController: UIViewController {

    var oauthswift: OAuth1Swift?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doAuthPetani()
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

    func doAuthPetani() {
        
        print ("hei")
        var is8VillagesInstalled: Bool = {
            let appUrl = URL(string: "8villages://app")
            return UIApplication.shared.canOpenURL(appUrl!)
        }()
        
        self.oauthswift = OAuth1Swift.init(consumerKey: "xxx.", consumerSecret: "xxx.", 
requestTokenUrl: "https://oauth.8villages.com/tokens/request-token", 
authorizeUrl: "8villages://app/?oauth_token_secret=", 
accessTokenUrl: "https://accounts.8villages.com/tokens/access-token")
        
        self.oauthswift?.authorizeURLHandler = OAuthSwiftOpenURLExternally.sharedInstance
        self.oauthswift?.allowMissingOAuthVerifier = true
        
        self.oauthswift?.authorize(
            withCallbackURL: "8villages://app/oauth-callback",
        success: { credentials, response, parameters in
            print("credentials", credentials)
            print("response =", response!)
            print("parameters=", parameters)
        }, failure: { error in
            print("the error is", error.description, error.errorCode)
        });
        
    
    }
    }


       extension ViewController: UIWebViewDelegate {
       func webView(_ webView: UIWebView, shouldStartLoadWith request: URLRequest,     navigationType: UIWebViewNavigationType) -> Bool {
        
        let urlString = request.url!.absoluteString
        let redirectUri = "YOUR_URL"
        if let _ =  urlString.range(of: "\(redirectUri)?code=") {
            OAuthSwift.handle(url: request.url!)
         //self.dismissWebViewController()
         }
         return true
     }
     }
```

### OAuth Provider (Twitter, Github, ..):

 https://accounts.8villages.com/authentication

### OAuth Version:
- [x] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [x] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [ ] v1.0.0
- [ ] v0.6
- [x] other: (i dont know.)

### Xcode version:
- [x] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
please provide a link to the provider api documentation

**Comment by megifernanda** [comment]
this  https://accounts.8villages.com/authentication

**Comment by phimage** [comment]
Maybe I must be logged somewhere because i receive
{"code":"MethodNotAllowedError","message":"GET is not allowed"}
Or this not a Doc link

**Comment by megifernanda** [comment]
yaaa because that i ask here how to make without authorize. because it skip auhtorize sir

**Comment by phimage** [comment]
So you DO NOT respond to my request, to provide a link to 8villages documentation

did you try https://oauth.8villages.com/tokens/authorize
or 
are you sure it's oauth version 1 ?

I can't help you more than that
