### ISSUE TITLE
How to skip authorizeURL

### ISSUE THREAD

**Issue by megifernanda** [OAuthSwift/OAuthSwift#352]
### Description:
hello sir, sorry to spam issue. 
i will build app with API and Oauth, but my API skipped authorizeURL
so, how to skip authorizeURL in oauth ?

my code : 

        `  import UIKit
           import OAuthSwift

       class ViewController: UIViewController {
    
    var oauthswift: OAuth1Swift?
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doAuthPetani()
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    
    func doAuthPetani() {
        
        print ("hei")
        self.oauthswift = OAuth1Swift(
            consumerKey:   "Sjt29_vS0RmK6t-QeXsieYn9Kq0.",
            consumerSecret: "YUVeUSiF_I5ZEoZLnD66dQ6pBu4Oi6D96NpyRbJ-Suo.",
            requestTokenUrl: "https://oauth.8villages.com/tokens/request-token",
            authorizeUrl:    **"my api without this",**
            accessTokenUrl:  "https://accounts.8villages.com/oauth/access-token"
        )
        
        
        let handle = oauthswift?.authorize(
            withCallbackURL: URL(string: "8villages://app/oauth-callback")!,
            success: { credential, response, parameters in
                print ("menda")
                
                self.oauthswift?.authorizeURLHandler = OAuthSwiftOpenURLExternally.sharedInstance
                self.oauthswift?.allowMissingOAuthVerifier = true

                
        },
            failure: { error in
                print ("a")
                print(error.localizedDescription)
        }
        )
        
    }
    }`

### OAuth Provider (Twitter, Github, ..):
8villages 
https://accounts.8villages.com/authentication

### OAuth Version:
- [x] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [x] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [ ] v1.0.0
- [ ] v0.6
- [x] other: (i don't know.)

### Xcode version:
- [ ] 8.0 (Swift 3.0)
- [x] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
Yes it's a spam
Duplicate of issue 350
Please do not close an issue to open a same one without answering questions...
