### ISSUE TITLE
postOAuthRequestToken is inaccesible due to 'internal' protection level

### ISSUE THREAD

**Issue by megifernanda** [OAuthSwift/OAuthSwift#359]
### Description:
help me sir, my project still work if i run but if i clean project i got sign red error 

> postOAuthRequestToken is inaccesible due to 'internal' protection level

      `self.oauthswift = OAuth1Swift.init(consumerKey: "****.",
                                           consumerSecret: "****",
                                           requestTokenUrl: "https://oauth.8villages.com/tokens/request-token",
                                           authorizeUrl: "8villages://app/?oauth_token_secret=",
                                           accessTokenUrl: "https://accounts.8villages.com/tokens/access-token")

        self.oauthswift?.authorizeURLHandler = OAuthSwiftOpenURLExternally.sharedInstance
        self.oauthswift?.allowMissingOAuthVerifier = true
        
        self.oauthswift?.postOAuthRequestToken(
            callbackURL: fileUrl as! URL,
            success: { credentials, response, parameters in`

       }, failure: { error in
            print("the error is", error.description, error.errorCode)
        });

i got error with this line

**_self.oauthswift?.postOAuthRequestToken(_**

before, i fork OAuthSwift.xcodeproject to edit OAuth1swift for Open Func postOAuthRequestToken

my problem is i got error **postOAuthRequestToken is inaccesible due to 'internal' protection level** if i clean project but if run my project still work

### OAuth Version:
- [x] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [x] Carthage
- [ ] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [ ] v1.0.0
- [ ] v0.6
- [x] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
internal method, don't call it
