### ISSUE TITLE
Example with authorize in class and not in ViewController

### ISSUE THREAD

**Issue by GlitchEclipse** [OAuthSwift/OAuthSwift#362]
### Description:
I have created a singleton of a custom class that holds the authorization and returns data fine, but I am trying to figure out with the provided examples how to use the authorizeURLHandler to create the webview when the authorization for the callback is not the ViewController since opening a separate Safari page will not be approved by the App Store. The example is everything done in the ViewController for these actions.  Are there any examples don't included everything in one ViewController? 

### OAuth Provider (Twitter, Github, ..):
Etsy

### OAuth Version:
- [x] Version 1
- [] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
for app store if your app is >= ios9 you have the SafariURLHandler

you need a view... to see a webview. so you have a parent view controller. could be one that already exist, a new one just to display the webview and anything else

**Comment by oshitub123** [comment]
it is okay but what happen when you use ios10 and xcode 8.3.2 we can't use correctly SafariUrlHandler because cause  this error : 
let url = URL(string: "https://www.apple.com")

**Comment by phimage** [comment]
look for the error in issue

the message is clear, you present it from a bad view controller
you make SFSafariViewController(viewController: XXX, and XXX is not the current view controller

**Comment by oshitub123** [comment]
i put this
code:



        let safari = SafariURLHandler(viewController: self,oauthSwift:oauthswift!)
        safari.delegate = self as! SFSafariViewControllerDelegate
        oauthswift.authorizeURLHandler = safari

**Comment by oshitub123** [comment]
but still don'
t work @phimage

**Comment by phimage** [comment]
I will not help
Please read all my advice

**Comment by phimage** [comment]
I try to explain again and close

`SafariURLHandler(viewController: VCXXX` : VCXXX must be the viewController on top of all view controllers, the one displayed when you make `authorize(...`,

**Comment by oshitub123** [comment]
i solve this , the problem was that i try to do it into viewdidload but when we use xcode 8.3.2 we have to do it into @IBAction or a func that its called into @ ibaction

**Comment by oshitub123** [comment]
some like this

@IBAction func check(_ sender: Any) {
        autorizathion { (bo) in
            self.reponseAuth = bo
            
            
        }
    }
    func autorizathion(completionHandler: @escaping (Bool) -> ()) {
       
        oauthswift = OAuth2Swift(
            consumerKey:    "************",
            consumerSecret: "",
            authorizeUrl:"https://accounts.spotify.com/authorize",
            responseType:"token"
        )
        
        let safari = SafariURLHandler(viewController: self,oauthSwift:oauthswift!)
        safari.delegate = self as!SFSafariViewControllerDelegate
        oauthswift?.authorizeURLHandler = safari
        oauthswift?.authorize(withCallbackURL: "DriverLocation://sputir/twitter", scope: "", state: "", success: { (credential, response,parameters) in
           self.userval.saveToken(tkn: credential.oauthToken)
            print(self.userval.queryToken())
            completionHandler(true)
        }, failure: { error in
            print(error._code)
            completionHandler(false)
        }
            
        )
        
    }

**Comment by oshitub123** [comment]
so thanks for all @phimage
