### ISSUE TITLE
doing a implicit grant 

### ISSUE THREAD

**Issue by oshitub123** [OAuthSwift/OAuthSwift#363]
### OAuth Version:
- [ ] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [x] Manually

### Library version:
- [ ] head
- [x] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by oshitub123** [comment]
I wants to do an authorization with OAuthSwift with a implicit grant
this is my code 


   let  oauthswift = OAuth2Swift(
            consumerKey:    "********",
            consumerSecret: "********",
            authorizeUrl:   "https://api.instagram.com/oauth/authorize",
            responseType:   "token"
        
        )
        let handle = oauthswift.authorize(
            withCallbackURL: URL(string: "oauth-swift://oauth-callback/instagram")!,
            scope: "likes+comments", state:"INSTAGRAM",
            success: { credential, response, parameters in
               
                print("\(credential.oauthToken) \n no chucha")
        },
            failure: { error in
                print(error.localizedDescription)
                
        }
        )
    
    
    }

**Comment by oshitub123** [comment]
I wants to do an authorization with OAuthSwift with a implicit grant
this is my code

let oauthswift = OAuth2Swift(
consumerKey: "",
consumerSecret: "",
authorizeUrl: "https://api.instagram.com/oauth/authorize",
responseType: "token"

    )
    let handle = oauthswift.authorize(
        withCallbackURL: URL(string: "oauth-swift://oauth-callback/instagram")!,
        scope: "likes+comments", state:"INSTAGRAM",
        success: { credential, response, parameters in
           
            print("\(credential.oauthToken) \")
    },
        failure: { error in
            print(error.localizedDescription)

**Comment by oshitub123** [comment]
I wants to do an authorization with OAuthSwift with a implicit grant
this is my code



import UIKit
import OAuthSwift
class ViewController: UIViewController,UIApplicationDelegate {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        
      let  oauthswift = OAuth2Swift(
            consumerKey:    "********",
            consumerSecret: "********",
            authorizeUrl:   "https://api.instagram.com/oauth/authorize",
            responseType:   "token"
        
        )
        let handle = oauthswift.authorize(
            withCallbackURL: URL(string: "oauth-swift://oauth-callback/instagram")!,
            scope: "likes+comments", state:"INSTAGRAM",
            success: { credential, response, parameters in
               
                print("\(credential.oauthToken) \n no chucha")
        },
            failure: { error in
                print(error.localizedDescription)
                
        }
        )
    
    
    }

    }

**Comment by oshitub123** [comment]
what i have to change  for to do a implicit grant and get my accestoken

**Comment by phimage** [comment]
Too much message...do only one . You must edit 

You have a bug 
Oauthswift object must be retain

**Comment by oshitub123** [comment]
i need to save my token  for to use an api rest  but i dont know how return from the broswer to the aplication and getting that token

**Comment by phimage** [comment]
so you do no read the readme...

look for "Make signed request" 
or use "credential.oauthToken" and sign your own request
