### ISSUE TITLE
Please help me, how to implement this Postman to OAuthSwift ?? 

### ISSUE THREAD

**Issue by fermendkis** [OAuthSwift/OAuthSwift#365]
### Description:

Sir, help me. i am really stuck make OAuth for my API. 
so how to implement this Postman to OAuth Swift? please, tell me how code to OAuth get data my API like this picture 

image removed

### OAuth Version:
- [x] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [x] Carthage
- [ ] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
do not put image with your secret informations....
I remove it

try, show your code

**Comment by fermendkis** [comment]
no problem sir, my secret informations is safe. i just want ask how to implement this structure postman in code OAuthSwift. i'm really stuck sir. 
<img width="946" alt="screen shot 2017-04-26 at 2 03 03 pm" src="https://cloud.githubusercontent.com/assets/17472847/25427068/8940f0aa-2a9b-11e7-812e-5ecaee77c8c7.png">

**Comment by phimage** [comment]
go to readme or demo and copy past
look for your provider doc for the url to use

**Comment by fermendkis** [comment]
your demo not tell how to add Token Key, Token Secret sir.

**Comment by phimage** [comment]
because that's not real oauth flow
oauth flow allow to obtains token key and secret

the oauth type could be changed to OAuth2?
if yes you do not need oauthSwift, just sign your request by adding a header to your HTTP request

else you can try this "Inject loaded token"
https://github.com/OAuthSwift/OAuthSwift/wiki/Store-credential
and just try to make request

**Comment by fermendkis** [comment]
oke sir, i'll try.


but how about this? i build code like this to get data and i don't know how next step to add credential into method get

> let credential = OAuthSwiftCredential(consumerKey: oauth_consumer_key, consumerSecret: oauth_consumer_secret)
        credential.oauthToken = oauth_token
        credential.oauthTokenSecret = oauth_token_secret

**Comment by phimage** [comment]
You must update the one in oauthswift.client
Then use client.get(..)

**Comment by fermendkis** [comment]
can you give example sir??

**Comment by phimage** [comment]
https://github.com/OAuthSwift/OAuthSwift#make-signed-request
say me if is not clear...

**Comment by fermendkis** [comment]
i has been tried like this sir

      > let headers = ["Authorization": "OAuth oauth_consumer_key=****,oauth_token=*****,oauth_signature_method=HMAC- 
           ,oauth_timestamp=****,oauth_nonce=KXTM16,oauth_version=1.0,oauth_signature=****",
            "Content-Type": "application/x-www-form-urlencoded"
        ]
        
    
        Alamofire.request("https://conversation.8villages.com/1.0/contents/articles?state=published", method: .get, headers: headers) .responseJSON { response in
            
            
                print("test", response.request!)  // original URL request
                print("ini responseny", response.response!) // HTTP URL response
                print("test", response.data!)     // server data
                print("test", response.result)   // result of response serialization
                debugPrint(response)
            
                if let JSON = response.result.value {
                    print("JSON: \(JSON)")
                }
            }

it's work, i can get my API. but it's juts manally im copas Method Signature from Postman. i don't know how to make automatic proccess.

sorry sri, i don't understand with your documentation signed request :(
