### ISSUE TITLE
help please i have to use a Handle authorize URL  in a UIWebView, WKWebView but with SafariURLHandler not function on code 8.3.2

### ISSUE THREAD

**Issue by oshitub123** [OAuthSwift/OAuthSwift#366]
### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [x] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
No information, log or error
Invalide issue - close

Show the other issue...

**Comment by oshitub123** [comment]
2017-04-25 12:05:03.680 pruebaslibrary[7476:136239] Warning: Attempt to present <SFSafariViewController: 0x7fdf8ef02960> on <pruebaslibrary.ViewController: 0x7fdf8ef07420> whose view is not in the window hierarchy!

**Comment by oshitub123** [comment]
an this is my code
let safari = SafariURLHandler(viewController: self,oauthSwift:oauthswift)
        safari.delegate = self as! SFSafariViewControllerDelegate
        oauthswift.authorizeURLHandler = safari

**Comment by phimage** [comment]
... edit your message 
And 
I have already answered
