### ISSUE TITLE
2-legged authorization

### ISSUE THREAD

**Issue by zishanj** [OAuthSwift/OAuthSwift#370]
### Description:
Any working example with 2-legged OAuth2 authorization of Google services account?

### OAuth Version:
- [ ] Version 1
- [x ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x ] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [x ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by zishanj** [comment]
the Google provide us with following JSON file:

{
  "type": "service_account",
  "project_id": "afsfsa",
  "private_key_id": "24324",
  "private_key": "-----BEGIN PRIVATE KEY-----\nsdfsafasf==\n-----END PRIVATE KEY-----\n",
  "client_email": "asdfsaf.iam.gserviceaccount.com",
  "client_id": "234324234242",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "http://asdfasfa.iam.gserviceaccount.com"
}

**Comment by oshitub123** [comment]
what it is, what is your question?

**Comment by phimage** [comment]
please give more informations
- your code which failed
- the documentation link
I close until you provide it

because I cannot guess if you are talking about jwt, server to server https://developers.google.com/identity/protocols/OAuth2ServiceAccount
