### ISSUE TITLE
please help, how i can use sfsafariviewcontroller with oauthswift using oauth2swift in xcode 8.3 and swift 3

### ISSUE THREAD

**Issue by oshitub123** [OAuthSwift/OAuthSwift#372]
### OAuth Version:
- [ ] Version 1
- [x ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [ x] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ x] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by oshitub123** [comment]
i have delagate like this


class ViewController: UIViewController,UIApplicationDelegate,UIWebViewDelegate,SFSafariViewControllerDelegate{

**Comment by oshitub123** [comment]
and use the next code 

but not function 

     oauthswift = OAuth2Swift(
            consumerKey:    "da0a78c40b5e4a2eb38d5ea03f32rw839feacf",
            consumerSecret: "",
            authorizeUrl:"https://accounts.spotify.com/authorize",
            responseType:"token"
       )
        let safari = SafariURLHandler( viewController: self ,oauthSwift:self.oauthswift!)
        safari.delegate = self
        oauthswift?.authorizeURLHandler = safari
        
        
        oauthswift?.authorize(withCallbackURL: "TestOauth://testoauth/twitte", scope: "", state: "", success: { (credential, response,parameters) in
            print(" token :\(credential.oauthToken)")
            print(credential.oauthVerifier)
            print(parameters)
            self.aux1token = credential.oauthToken
            self.defaults.set(self.aux1token, forKey: "pk")
            self.retrieve()
 
            
        }, failure: { error in
            print(error.localizedDescription)
        }
)

**Comment by phimage** [comment]
see my first comment
https://github.com/OAuthSwift/OAuthSwift/issues/366

same apply
I will not help If you doesn't read me
then read also https://github.com/OAuthSwift/OAuthSwift/blob/master/.github/CONTRIBUTING.md
