### ISSUE TITLE
No apparent way to make Oauth 1.a requests

### ISSUE THREAD

**Issue by josephquigley** [OAuthSwift/OAuthSwift#374]
### Description:
There doesn't seem to be any way to make OAuth 1.a requests in the wiki, example code, or in source. Are people supposed to use raw `OAuthSwiftHTTPRequest` requests?

### OAuth Version:
- [x] Version 1
- [ ] Version 2

**Comment by phimage** [comment]
I am a little confusing about why you did not find the code, maybe I do not understand your question
But there a lot of ´get´ in demo app
In readme there is an example of request

**Comment by josephquigley** [comment]
Thought I replied to you, but it looks like email reply-to didn't work. Sorry.

I'm new to OAuth, so forgive my questions. Are you referring to the signed request part of the readme? Because the OAuth1 section doesn't show any examples of a 1.0a request that only uses a public key and a secret key. It shows examples of tokens and authorize URLs. As far as I know, those don't apply to 1.0a.

**Comment by phimage** [comment]
I don't think so
1.0a also could use authorize
https://oauth.net/core/1.0a/

**Comment by josephquigley** [comment]
Authorize in OAuthSwift?

**Comment by phimage** [comment]
`oauthswift.authorize(...` , normal use of framwork, see readme...

**Comment by josephquigley** [comment]
Ok, I figured it out. The documentation on the Readme.md was not clear. You can init `OAuth1Swift` without the `requetTokenUrl`, `authorizeUrl`, and `accessTokenUrl` parameters.

Pull request: https://github.com/OAuthSwift/OAuthSwift/pull/378

**Comment by phimage** [comment]
@josephquigley do not close your issue next time if you make a PR
Just put Fix #issue_number in your PR title and the issue will be closed automatically when merging PR
