### ISSUE TITLE
Installing 'OAuthSwift', '~> 1.1.0' causes issues

### ISSUE THREAD

**Issue by AabanTariq** [OAuthSwift/OAuthSwift#375]
I am installing through pods as older version 0.5.0 giving me 160 compile time errors

pod 'OAuthSwift', '~> 1.1.0'

But i am not successfull.  Currently i am using xcode 8.2.1.

Error is

- `OAuthSwift (~> 1.1.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `OAuthSwift (~> 1.1.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

Please help.

**Comment by phimage** [comment]
why did you remove the issue template?

use last xcode and 'head' version

then that say 1.1.1
https://img.shields.io/cocoapods/v/OAuthSwift.svg?style=flat
http://cocoadocs.org/docsets/OAuthSwift/1.1.1/
but I don't see here
https://github.com/CocoaPods/Specs/tree/d0ec5a65e80656c8d78e12ff19f251df879e0bc2/Specs/b/c/6/OAuthSwift

**Comment by phimage** [comment]
pod trunk push of 1.1.2 
```
 🎉  Congrats

 🚀  OAuthSwift (1.1.2) successfully published
 📅  June 4th, 12:22
 🌎  https://cocoapods.org/pods/OAuthSwift
 👍  Tell your friends!
```
