### ISSUE TITLE
Make signed request nothing happens

### ISSUE THREAD

**Issue by jeffreyabarrios** [OAuthSwift/OAuthSwift#376]
Hello! I have a custom server with oauth 1, and im trying to make the authorization with these examples from the docs:
//this variable is declared on top of the class
var oauthswift: OAuthSwift? 

//then any of these example codes is what i used (with the correct parameters) on the action outlet for the login button
oauthswift.client.get("https://api.linkedin.com/v1/people/~",
      success: { response in
        let dataString = response.string
        print(dataString)
      },
      failure: { error in
        print(error)
      }
)
// same with request method
oauthswift.client.request("https://api.linkedin.com/v1/people/~", .GET,
      parameters: [:], headers: [:],
      success: { ...

This is attached to a login button, but when I click it nothing happens, and the object oauthswift appears as nil in console, can you help me please?

**Comment by phimage** [comment]
no issue template?
I will close
need help, please take your time to respond to template question

and read readme
