### ISSUE TITLE
Add client_credential grant_type

### ISSUE THREAD

**Issue by Joker-** [OAuthSwift/OAuthSwift#377]
### Description:
I'm developing iPhone SDK for my server with oauth and I need client_credentials authorization.

I found this method 
    open func authorize(deviceToken deviceCode: String, success: @escaping TokenRenewedHandler, failure: @escaping OAuthSwiftHTTPRequest.FailureHandler) -> OAuthSwiftRequestHandle? {
        var parameters = OAuthSwift.Parameters()
        parameters["client_id"] = self.consumerKey
        parameters["client_secret"] = self.consumerSecret
        parameters["code"] = deviceCode
        parameters["grant_type"] = "http://oauth.net/grant_type/device/1.0"
        
        return requestOAuthAccessToken(
            withParameters: parameters,
            success: { (credential, response, parameters) in
                success(credential)
            }, failure: failure
        )
    }
And if I change 
        parameters["grant_type"] = "http://oauth.net/grant_type/device/1.0"
to
        parameters["grant_type"] = "client_credentials"
authorization will work.
But since I want to distribute my SDK to another developers I need some way to add this functionality to master. Or can you offer me another way to set client_credentials into grant_type field?

### OAuth Provider (Twitter, Github, ..):
Other

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [x] head
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
you can know specify grantType in function parameters

next time try to make a PR
