### ISSUE TITLE
Access_token request headers get lost during request creation

### ISSUE THREAD

**Issue by ondrejhanak** [OAuthSwift/OAuthSwift#379]
### Description:

When `finalHeaders` are constructed in `OAuth2Swift.swift` on [line 225](https://github.com/OAuthSwift/OAuthSwift/blob/master/Sources/OAuth2Swift.swift#L225), original headers passed into the method get lost.

What about changing the line like following?
```
var finalHeaders: OAuthSwift.Headers? = headers
```

I am happy to submit PR if the solution gets approved.

**Comment by phimage** [comment]
thanks, yes you can PR
