### ISSUE TITLE
Making changes to SFSafariViewController class

### ISSUE THREAD

**Issue by dannymout** [OAuthSwift/OAuthSwift#386]
With the changes introduced to `SFSafariViewController` in iOS 10, it makes it possible to customize it a lot more. I'm using `SafariURLHandler`, but how can I access the SafariVC to make changes?

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  

### Library version:
- [ ] head
- [ ] v1.0.0
- [ ] v0.6
- [x] other: v1.1.2

### Xcode version:
- [ ] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [x] other: Xcode 9 and Swift 4

**Comment by phimage** [comment]
you can set a factory `SafariURLHandler#factory`
see https://github.com/OAuthSwift/OAuthSwift/blob/master/Sources/OAuthSwiftURLHandlerType.swift

then there is also
```swift
open var animated: Bool = true
open var presentCompletion: (() -> Void)?
open var dismissCompletion: (() -> Void)?
```

**Comment by dannymout** [comment]
@phimage OK, so how does `SafariURLHandler#factory` work? Do you have a short code example?

**Comment by phimage** [comment]
.factory = { safari in

}

Simple closure

**Comment by dannymout** [comment]
@phimage 'safari' is of type URL, that's why I was getting confused with `SafariURLHandler#factory`.

**Comment by phimage** [comment]
Sorry
, just read the closure type

.factory = { url  in
  return SafaryXxxxxx(url :url)
}

**Comment by dannymout** [comment]
@phimage Getting the following error: `Value of type '()' does not conform to 'OAuthSwiftURLHandlerType' in assignment`

**Comment by phimage** [comment]
ya but you not post your code, so how I can help? The error message is clear.

please look at demo code
https://github.com/OAuthSwift/OAuthSwift/commit/aceae6aaad5d3d5930f74119fadcdb4cdc2b5f52

**Comment by dannymout** [comment]
@phimage Nevermind Xcode seemed to be acting up. When I looked over the code, mine looked the same, so I tried uncommenting what I wrote, and everything is fine. Thanks!
