### ISSUE TITLE
watchOS documentation missing

### ISSUE THREAD

**Issue by matteobit** [OAuthSwift/OAuthSwift#389]
I don't understand how to use the framework with a watchOS app

**Comment by phimage** [comment]
Hi 
watchOS platform is not specified in readme 

Did you try to use it ? Have some issue?

**Comment by matteobit** [comment]
I tried it, the authorized request works fine, but I'd like to know if it supports the Limited-Input Devices UI like [this](https://developers.google.com/identity/protocols/OAuth2ForDevices).

For now the token is sent from iPhone to Watch and everything works fine.

**Comment by phimage** [comment]
there is a method that I have never tested on `OAuth2Swift`
` open func authorize(deviceToken deviceCode: String,`
this function seems to implement "Step 4: Poll Google's authorization server"
