### ISSUE TITLE
RenewAccessToken throwing AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext

### ISSUE THREAD

**Issue by sheetal-hemrom** [OAuthSwift/OAuthSwift#391]
### Description: 

AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext
 while calling renewAccessToken. 

The authorize is successful and I save the refreshToken from credentials in my UserDefaults.

```
        oauthswift.renewAccessToken(withRefreshToken: refreshToken, headers : nil ,success: { (credential, response, parameters) in
            print(credential.oauthToken)
            print(credential.oauthRefreshToken)
            completionHandler(true, credential.oauthToken,credential.oauthRefreshToken)
        } , failure: { (error) in
            print(error.localizedDescription)
            completionHandler(false, nil,nil)
        })
```
### OAuth Provider (Twitter, Github, ..):
- PCF 

### OAuth Version:
- [ ] Version 1
- [X] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [ ] v1.0.0
- [ ] v0.6
- [x] v1.1.1

### Xcode version:
- [x] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)
- [ ] objective c

**Comment by phimage** [comment]
you remove "OAuth Provider" from issue template
the main information I need to help you

Did you try to connect to a server that use spring?

**Comment by sheetal-hemrom** [comment]
@phimage Hi Eric I have bind an application hosted on PCF with their SSO service instance.

**Comment by phimage** [comment]
Hi, the normal authentification work well? or only renew failed?

I found in spring (java) the message `AbstractSecurityInterceptor.authenticationNotFound=An Authentication object was not found in the SecurityContext`

maybe some configuration must be done in server
I don`t think this is an OauthSwift issue

**Comment by sheetal-hemrom** [comment]
Hi. The normal authentication (authorize) do work and so I am able to receive token and refresh token at first place. But while renewing if I receive the issue which exactly does the same flow  just different POST parameters (as I debugged)  . I think it should not be a PCF issue but OAuth might be following different configuration for authorize and renew calls

**Comment by sheetal-hemrom** [comment]
I will also check with my server if that is the case

**Comment by sheetal-hemrom** [comment]
@phimage So I found out that renew works after sometime and not when I just log in . While I was trying renew I was trying to renew just under the completion block of authorize. When I saved the refresh token for later and hit renew it worked. It might be a PivotalCloudFoundary issue but I got a hint in this answer [her](https://stackoverflow.com/a/16727172/898057)
