### ISSUE TITLE
Woo commerce api does not permit to reach data when use the oauthswift 1.0

### ISSUE THREAD

**Issue by bkryslky** [OAuthSwift/OAuthSwift#392]
### Description:
Hi i am using oauthswift 1.0 to authorize woo commerce api but woo api services is giving 401 error and it says that  you can not list . I checked all woo commerce api docs reference i try different libraries . Anyone  has any idea to use woo commerce api? Thank you have nice day.  
### OAuth Provider (Twitter, Github, ..):
woo api services

### OAuth Version:
- [x] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [x] Manually

### Library version:
- [ ] head
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ ] 8.0 (Swift 3.0)
- [x] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
first please provide link to woo documentation

really use swift 2.3?

please give the full error message from api, without modifying any letter or word (this help to look for using google)

did you have some code to show. how you initialize the oauth1Swift for instance, and how you call authorize. Without that, it's very difficult to see the issue

**Comment by bkryslky** [comment]
![ekran resmi 2017-07-11 12 07 01](https://user-images.githubusercontent.com/20702828/28064895-fd77bc5e-663e-11e7-870f-c3a8fcd21857.png)
message says that sorry you can't list

for instance
![ekran resmi 2017-07-11 13 46 56](https://user-images.githubusercontent.com/20702828/28065004-776054cc-663f-11e7-9f17-9ba156d8d6bf.png)

Eric i saw your post about that but try different approach but it didn't  work

**Comment by bkryslky** [comment]
https://woocommerce.github.io/woocommerce-rest-api-docs/#introduction 
woocommerce api doc link

**Comment by phimage** [comment]
the error is woocommerce_rest_cannot_view
https://github.com/woocommerce/woocommerce/search?utf8=%E2%9C%93&q=woocommerce_rest_cannot_view&type=
a configuration issue, your user has no right to list resources

**Comment by bkryslky** [comment]
Woocommerce api service is working on postman and android platform. I am trying different
ways to solve problem.

**Comment by phimage** [comment]
your callbackurl is wrong in code. you do not get a token and secret I think
check readme to know what the purpose of callback url

**Comment by bkryslky** [comment]
I tried for authorization this url(http://magentotest.1ticaret.com/wordpress/wc-auth/v1/authorize) but it didn't work again. And i have not still  found a solution.

**Comment by phimage** [comment]
you do not read my message
your callback url is wrong

must be yourappscheme://callback.... or have a server to redirect or have a web view delegate and do the code
all is in readme

**Comment by nizzam** [comment]
@bkryslky Have you fixed the issue ? If yes, kindly share the solutions.

**Comment by oenama** [comment]
> @bkryslky Have you fixed the issue ? If yes, kindly share the solutions.

@bkryslky 

+1
