### ISSUE TITLE
Will it work for custom project?

### ISSUE THREAD

**Issue by sribharanidharan** [OAuthSwift/OAuthSwift#393]
Hi Author,

Please guide me whether this library work for other custom project than your mentioned list?

Please share the link how we can do it?

### OAuth Version:
- [x] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 8.0 (Swift 3.0)
- [x] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
Yes if your custom server/proviseur project follow the oauth protocol.
There is no link, just the read the readme, and for spécial case, see the wiki
