### ISSUE TITLE
How to hide consumer_secret in app?

### ISSUE THREAD

**Issue by trondkr** [OAuthSwift/OAuthSwift#395]
### Description:
How to hide consumer_secret in app?

### OAuth Provider (Twitter, Github, ..):
Twitter, Google...

### OAuth Version:
- [ ] Version 1
- [x ] Version 2

### OS (Please fill the version) :
- [] iOS :
- [x ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x ] CocoaPods
- [ ] Manually

### Library version:
- [x] head
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x ] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c
I understand that my question is not an issue but I still hope you can bear with me. I can not figure out how most people hide their consumer_secret (for Twitter, Google etc.) in an app (macos, iOS)? I have asked a question on [SO](https://stackoverflow.com/questions/45065984/how-to-keep-client-secret-for-oauth2-login-to-parse-server-secure) without any answers and I was hoping the OAuthSwift community might help. Do developers ship the Twitter, Google, etc. consumer_secret as a string or obfuscated string in their apps these days or is there a trick to this? I understand that storing the secret on a server may be the best, but using Swift I don't see how even that can be done securely as I would still have to retrieve the secret and add it to my OAuthSwift request which could then be intercepted and discovered. Any suggestions are very appreciated. Thank you. T

**Comment by phimage** [comment]
say how I do it could help someone to find how he can revert it but I will take the risk

I use crypto swift to encode it and keep in my code only this encrypted value and the key to decrypt
So the problem is reported to this two elements, If we find the key, the crypted value and the method used, we can decrypt, but this add some fun work for the hacker
You can the split this values in multiple variables in different files, reverse it, add multiple encryptions etc...

**Comment by trondkr** [comment]
It seems like this is the approach I will take myself. I am surprised it is so difficult to find information about beast approaches for this, but perhaps developers want their solution hidden as much as possible. I appreciate you taking the time to answer. Thanks. T
