### ISSUE TITLE
I cant login to facebook or google or linked in

### ISSUE THREAD

**Issue by nathankonrad1** [OAuthSwift/OAuthSwift#396]
Hey, first of all, really appreciate your huge work on this library. Thanks a lot

### Description:
I have these callbacks urls: (these are working perfectly on web)
http://staging.claimit-server.com/auth/facebook/callback
http://staging.claimit-server.com/auth/google/callback
http://staging.claimit-server.com/auth/linkedin/callback

And I am trying to login with FB, Google or LinkedIn, it works perfectly, but callback not working.
I can see JSON in SFSafariVC (see attach), but cant handle to get back to my app.

Its something wrong with my urls? Or may I missed something when setting up.

Can you please help?

Thanks in advance

 
![screen shot 2017-07-22 at 4 53 10 pm](https://user-images.githubusercontent.com/29920502/28491711-775cd654-6efe-11e7-9b22-e66f937f2103.png)

### OAuth Version:
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :

### Installation method:
- [x] CocoaPods

### Library version:
- [x] head

### Xcode version:
- [x] 8.3.2 (Swift 3.2)

**Comment by phimage** [comment]
https://github.com/OAuthSwift/OAuthSwift#how-to
a redirection must be done to call yourapp:://oauth-swift to call OAuthSwift.handle(url: url)

your claimit-server just display the information needed as json...
why you need it?
