### ISSUE TITLE
Is there a working sample out there of using this package and Instagram?

### ISSUE THREAD

**Issue by ejpusa** [OAuthSwift/OAuthSwift#399]
I'm sure it get be done, but with changes to Instagram, would love to see a super simple sample of OAuthSwift and Instagram working. To date, have not been able to find a working example. I'm sure there must be one out there.

Or does iOS11 make it all a new approach all together?

https://github.com/dvdhpkns/SFAuthenticationSession-Instagram-Oauth

My simple request. -)

**Comment by phimage** [comment]
Did you try the demo app?

**Comment by ejpusa** [comment]
Yes, using iOS11. Have a few errors. I'll poke around. thanks

<img width="271" alt="screen shot 2017-08-08 at 8 24 57 am" src="https://user-images.githubusercontent.com/1279819/29071838-45aedd88-7c13-11e7-83b0-1bcb919d8a61.png">
