### ISSUE TITLE
Getting OAuthSwiftError error -3 or -1

### ISSUE THREAD

**Issue by SergeiKu** [OAuthSwift/OAuthSwift#405]
### OAuth Version:
- [ ] Version 1
- [x ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x ] CocoaPods
- [ ] Manually

### Library version:
- [x ] head
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x ] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

I am getting OAuthSwiftError error (if allowMissingStateCheck = false)-3 or (if allowMissingStateCheck = true)-1. I am trying to authorize with Microsoft oneDrive. The call back is some-uri://somthing/auth?code=xxxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx and I think it returns the auth code. I have no idea why the errors happen. Please, help.

class SomeClass {
        
    var oauthswift: OAuth2Swift?
    
    override func startDirectoryScan() {
        
        
        oauthswift = OAuth2Swift(
            consumerKey:    AppOneDriveID,
            consumerSecret: "",
            authorizeUrl:   "https://login.live.com/oauth20_authorize.srf",
            responseType:   "code"
        )
        self.oauthswift!.allowMissingStateCheck = false
        self.oauthswift!.authorizeURLHandler = SafariURLHandler(viewController: self, oauthSwift: self.oauthswift!)
        self.oauthswift!.authorize(withCallbackURL: URL(string: "some-uri://somthing/auth")!,
            scope:  "onedrive.readonly offline_access", state:"",
            success: { credential, response, parameters in
                print("resp \(credential, response, parameters)")
                        // Do your request
                
                },
                    failure: { error in
                        print(error.localizedDescription)
                }
        )
    }
}

**Comment by phimage** [comment]
Errors code : https://github.com/OAuthSwift/OAuthSwift/blob/master/Sources/OAuthSwiftError.swift

Look at configurationError in code for -1
One cause is missing to define autorizeUrl

**Comment by SergeiKu** [comment]
Thank you, yes, you are right! Closed.
