### ISSUE TITLE
Xcode 9 Swift 4.0 support

### ISSUE THREAD

**Issue by neoneye** [OAuthSwift/OAuthSwift#409]
### Description:

Recently people have begun migrating their projects from Xcode8 to Xcode9 and from Swift3 to Swift4. OAuthSwift is an important component.

With Xcode9 and swift4 enabled, I'm getting errors like these:

```
var userInfo: [AnyHashable: Any] = [
    NSLocalizedDescriptionKey: localizedDescription
]
...
let error = NSError(domain: OAuthSwiftError.Domain, code: badRequestCode, userInfo: userInfo)
```
Here Xcode wants `AnyHashable` to be changed to `String`.

Xcode also wants `OAuthSwiftDataEncoding` to be changed from being internal to being public.

### OAuth Provider (Twitter, Github, ..):
none

### OAuth Version:
- [ ] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [x] head
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 9.0 (9A235) goldmaster (Swift 4.0)
- [ ] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1

- [ ] objective c

**Comment by phimage** [comment]
Hi, not released yet on cocoapod or tagged, but head code use swift 4 thanks to nighthawk 

A swift 3 branch is also created
