### ISSUE TITLE
Cann't use this framework with Xcode 9 & swift 4

### ISSUE THREAD

**Issue by BBHNation** [OAuthSwift/OAuthSwift#412]
### Description:
When I use the old project created by Xcode 8 & swift 3, it works with the new Xcode 9 & swift 4. 
But when I create a new project with Xcode 9 & swift 4 & the same .swift file, the code won't call back and the APP just show web content.

### OAuth Provider (Twitter, Github, ..):
Github

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [x] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 9.0 (Swift 4.0)
- [ ] 8.0 (Swift 3.0)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
Installation method?

**Comment by BBHNation** [comment]
install with CocoaPods

**Comment by phimage** [comment]
your url `authorizeURLHandler` is? 

then did you configure the project correctly, see readme to add scheme
https://github.com/OAuthSwift/OAuthSwift#setting-url-schemes

**Comment by BBHNation** [comment]
It's my bad, I didn't follow the steps one by one while I was creating the new project. I ignored to add scheme and the code in AppDelegate.swift .
Thank you so much for your reply!

**Comment by BBHNation** [comment]
Anyway, this issue shows OAuth can be used with Xcode 9 & Swift 4
