### ISSUE TITLE
Use the oAuth in Xcode 7.3

### ISSUE THREAD

**Issue by Gurmeetkaur5949** [OAuthSwift/OAuthSwift#414]
Hello Team, I am trying to add  the wechat oauth functionality in my app. I am using the xcode 7 and swift version is 2. I have checked that when i  open the demo in xcode 7.3 is shows me lots of error in code. So my question is, Is this library support the older version of swift or not.

**Comment by phimage** [comment]
There is some swift2xxx branches
You can try with them

**Comment by Gurmeetkaur5949** [comment]
Ok, Thanks for your quick response. One more question,  i cant see the name of wechat oauth in the "Support OAuth1.0, OAuth2.0" list . So is it possible to add the wechat oauth using this library??

**Comment by phimage** [comment]
To add it some code must be added to demo app in main branch
https://github.com/OAuthSwift/OAuthSwift/wiki/Demo-application#add-a-new-service-in-demo-app
That allow me to test the compatibility

**Comment by Gurmeetkaur5949** [comment]
Ok, Thank u so much for your help. I will try to implement it in my app.
