### ISSUE TITLE
Provide Linux Support 

### ISSUE THREAD

**Issue by mackoj** [OAuthSwift/OAuthSwift#417]
### Description:

It's could be great if this library works with SwiftPackageManager / Linux.

### OAuth Version:
- [x] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] Linux :

### Installation method:
- [x] SwiftPackageManager

### Library version:
- [x] 1.1.2

### Xcode version:
- [x] 9.0 (Swift 3.2)

**Comment by flangel** [comment]
What about Android support?
