### ISSUE TITLE
webViewController Dismiss animation Disable

### ISSUE THREAD

**Issue by rakeshgits** [OAuthSwift/OAuthSwift#420]
### Description:
There is no way to disable the animation while dismissing the webview controller, however there is one to disable it while presenting.

Can be resolved by adding animated parameter in the dismiss webview controller, or adding a globar animation variable like present.

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [x] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
I add `dismissViewControllerAnimated` boolean
