### ISSUE TITLE
Authorize handler not called - neither success or failure

### ISSUE THREAD

**Issue by markusstaas** [OAuthSwift/OAuthSwift#421]
### Description:
Hi there, I am connecting to Strava API and can authorize the app successfully, however, the success or failure handler never gets called. 

App Delegate Code:
` func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
        if (url.host == "oauth-callback") {
            OAuthSwift.handle(url: url)
        }
        return true
    }`

VC Code below:

`     func login(){

    // Create OAuth Object
    let oauthswift = OAuth2Swift(
        consumerKey:    "21913",
        consumerSecret: "a4bef18ded5104e4c6d00b37dfe40b2512b69730",
        authorizeUrl:   "https://www.strava.com/oauth/authorize",
        accessTokenUrl: "https://www.strava.com/oauth/token",
        responseType:   "code"
    )
    oauthswift.authorizeURLHandler = SafariURLHandler(viewController: self, oauthSwift: oauthswift)
    
        oauthswift.authorize(
            withCallbackURL: URL(string: "oauth-swift://oauth-callback/strava")!,
            scope: "write", state:"mystate",
            success: { credential, response, parameters in
                print(credential.oauthToken)
                // Do your request
        },
            failure: { error in
                print(error.localizedDescription)
        }
        )
}`

### OAuth Provider (Twitter, Github, ..):
Strava

### OAuth Version:
- [ ] Version 1
- [x ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x ] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [x ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x ] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by markusstaas** [comment]
If I just launch it in Safari and return the app I get the following error message: The operation couldn’t be completed. (OAuthSwiftError error -10.)

**Comment by phimage** [comment]
you must retain the `oauthswift`object in memory
-10 is retain error

**Comment by markusstaas** [comment]
Thanks! I appreciate your response! It works now if I use Safari, however, if I use  oauthswift.authorizeURLHandler = SafariURLHandler(viewController: self, oauthSwift: oauthswift) it won't call the breakpoints on the handlers. Do you have any advise?

Thanks so much! 
Markus

**Comment by phimage** [comment]
Any errors?

If not you can put a breakpoint in your `func application(_ app: UIApplication, open url: URL, ...` to see if ` OAuthSwift.handle(url: url)` called
