### ISSUE TITLE
How can I get authentication code to pass to backend?

### ISSUE THREAD

**Issue by najmul-csebuet** [OAuthSwift/OAuthSwift#423]
### Description:
When this library goes for authentication, it is returning me an access token, refresh token and an id token. But I just need auth code which I will pass to our backend. How will you do that using this library?
Thanks
### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [ ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [x] other: (Please fill in the version you are using.)

### Xcode version:
- [ ] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [x] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
Just a title?
Please give more information in description

**Comment by najmul-csebuet** [comment]
Hi @phimage, just updated issue with some description.

**Comment by phimage** [comment]
Create a new class which extends OAuth2Swift and override method postOAuthAccessTokenWithRequestToken(byCode....

**Comment by najmul-csebuet** [comment]
hmm, good idea. but seems overriding not possible. can you pls check also @phimage

**Comment by phimage** [comment]
The method is ´open’ , and the class I think too
