### ISSUE TITLE
Not able to sign in using the latest Google OAuth provider

### ISSUE THREAD

**Issue by mervyn777** [OAuthSwift/OAuthSwift#424]
### Description: 
OAuth SignIn doesn't work with the latest Google OAuth process. Now the iOS/Android OAuth clients don't provide the Client Secret without which the library does not successfully fetch the token. If we use Web client instead during registration on Google API console we cannot set the custom callback URI.(Even if we do it throws error during sign in process). Your demo example is outdated and shows a different http schemed redirect URI. Please let me know if I'm missing something.

#### URL received on app delegate:
```<app.bundle.id>:/oauth2redirect?code=4/2O3vlmmgWeJWUrrFSK3ygp3JtN5ioNb7LvHiYJYU&authuser=0&session_state=4d9f34f683268c9198ca81fe302031c1a212784d..70a8&prompt=consent#```

#### Error received:
```OAuthSwiftError error -3```

### OAuth Provider:
Google

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [x] head
- [ ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
error -3 maybe oauthswift.allowMissingStateCheck = true could help

**Comment by mervyn777** [comment]
Thanks that helped!

As for the `OAuthSwiftURLHandlerType` I'm using the built-in `SafariURLHandler` but how can I get notified if the user cancels the authorization process by pressing `Done` in the consent screen.

Is it possible to return back this action in the form of failure callback event while requesting authorization? Something like `failure?(OAuthSwiftError.cancelled)`?

The problem is I'm handling OAuth related functions in a non NSObject class and I cant implement the `SFSafariViewControllerDelegate` (I see I can set this delegate to `SafariURLHandler.#delegate`) to be notified about user dismissal actions.

**Comment by phimage** [comment]
@mervyn777 do not hesitate to PR if you need add `open` to some functions
