### ISSUE TITLE
Feature request: Coub support

### ISSUE THREAD

**Issue by gerchicov-bp** [OAuthSwift/OAuthSwift#425]

**Comment by phimage** [comment]
Hi
First you cannot make feature request on this open source project.

You must first try to use this project with coub, and if there is issue you must create an issue with all information needed to understand the problem (error log, link to the coub documentation about oauth)
Don't forget to read the readme to configure the project (the url scheme for instance), and put some break point to see if the callback is called

/!\ You must not remove the issue template -> so I close
