### ISSUE TITLE
Issues with LinkedIn redirect url. How to handle "http" based redirect URLs?

### ISSUE THREAD

**Issue by mervyn777** [OAuthSwift/OAuthSwift#426]
### Description:
Looking at your demo project you have used "http" based redirect url (i.e `http://oauthswift.herokuapp.com/callback/linkedin2`) to get token from LinkedIn. So how can we handle this scheme on our app when the oauth `code` is returned back by the `SFSafariViewController`?

Your documentation only specifies custom scheme that the app can handle.

I tried setting up a custom redirect uri on LinkedIn page but it doesn't provide that option. It only accepts `https` based uri.

### OAuth Provider (Twitter, Github, ..):
LinkedIn

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [x] head
- [ ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by mervyn777** [comment]
Found my solution here: https://github.com/OAuthSwift/OAuthSwift/wiki/API-with-only-HTTP-scheme-into-callback-URL

**Comment by dnawarrior** [comment]
Did you do with it Safari Controller or had to switch to webview?
