### ISSUE TITLE
1.2.0 is still not Swift 4

### ISSUE THREAD

**Issue by rcritz** [OAuthSwift/OAuthSwift#427]
### Description: 

Your documentation infers that 1.2.0 is for Swift 4 but it results in three deprecation warnings. These warnings are already fixed on the master branch which differs from what is in the 1.2.0 tag (e.g. Utils.swift). Can you please update tags so that it's possible to get a clean build with Swift 4?

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [x] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
issue title is wrong.
You can use branch head or a specific commit in your podfile 

I will release a 1.2.1 with other fix
