### ISSUE TITLE
I am using OAuthSwift lib to call web services. We are using OAuth 1 at server side for authentication. But every time I call services it creates a new session at server side. by using Cookies Jar, my android app able to maintain session and no new session is created at server for same. But this not a case in IOS. The Code I tried is as follows

### ISSUE THREAD

**Issue by Rupesh1234fbbf** [OAuthSwift/OAuthSwift#431]
let oauthswift = OAuth1Swift(
        consumerKey:"1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        consumerSecret:"5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
     )
    oauthswift.client.credential.oauthToken = "cxxxxxxxxxxxxxxxxxxxxxxxxx"
    oauthswift.client.credential.oauthTokenSecret = "xxxxxxxxxxxxxxxxxxxxxxxx"

    oauthswift.client.post(register_URL , parameters:requestDict, headers: ["Accept": "application/json", "Content-Type":"application/json"],success: { response in

        let dataString = response.string

        let data = dataString?.data(using: .utf8)
           do {
            //Parsing data & get the Array

        } catch let error as NSError {
            print("Failed to load: \(error.localizedDescription)")
            DispatchQueue.main.async {
                errorBlock(error.localizedDescription)
            }
        }
    },
            failure: { error in
            print(error)
    })

I also tried to keep the singleton pattern to keep oauthswift object same form to request but not helped. Also tried to set cookies in oAuthSwift Client as follows.

import Foundation
import OAuthSwift

class ClientHelper{

   static var oauthswift:OAuth1Swift?

    /* Create cookie and place in cookie storage */
    static let cookieStorage = HTTPCookieStorage.shared
    static func getInstance()->OAuth1Swift{

    if(oauthswift == nil){
    oauthswift = OAuth1Swift(
            consumerKey:"1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            consumerSecret:"5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
         )
        oauthswift?.client.credential.oauthToken = "cxxxxxxxxxxxxxxxxxxxxxxxxx"
        oauthswift?.client.credential.oauthTokenSecret = "xxxxxxxxxxxxxxxxxxxxxxxx"
        oauthswift?.client.sessionFactory.configuration.httpCookieStorage = cookieStorage
       oauthswift?.client.sessionFactory.configuration.httpShouldSetCookies = true

    }
        return oauthswift!;

   }

}

**Comment by phimage** [comment]
Title too long
Issue template deleted
I close
