### ISSUE TITLE
configuring OAuth2 bearer authentication 

### ISSUE THREAD

**Issue by MunaTayeb** [OAuthSwift/OAuthSwift#434]
### Description:

I'm required to use OAuth2 bearer authentication, which is when the user login successfuly, I got an access token and refresh token from the server. once the access token expires (code 401), I use the refresh token on some endpoint to get the new access and refresh tokens, I couldn't find any guide regarding this, is it possible using this library? if yes, how to make the refreshing process automatic?

### OAuth Provider (Twitter, Github, ..):
Bearer authentication 

### OAuth Version:
- [ ] Version 1
- [X] Version 2

### OS (Please fill the version) :
- [X] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [X] Manually

### Library version:
- [X] head
- [ ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ ] 9.0 (Swift 4.0)
- [X] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1

**Comment by phimage** [comment]
https://github.com/OAuthSwift/OAuthSwift/wiki/OAuth-2.0-Token-Expiration

**Comment by MunaTayeb** [comment]
I have acess token, refresh token and one endpoint which recives the refresh and send back new ones.
where should I add these three when creating an OAuth2Swift object and setting it's parameters?

**Comment by phimage** [comment]
no where, there is no standard

see startAuthorizedRequest signature, you have a callback to make the request your self

or see OAuthSwiftAlamofire project with request retrier

**Comment by phimage** [comment]
if requestError, you can take the underlying error as NSError or URLError
an example with NSError
https://github.com/OAuthSwift/OAuthSwift/blob/master/Sources/NSError%2BOAuthSwift.swift
