### ISSUE TITLE
How to get notified SafariViewController has been dismissed

### ISSUE THREAD

**Issue by shaibt** [OAuthSwift/OAuthSwift#436]
### Description:
Hi, 
How do I get notified the user hit "done" on the SF View Controller and never followed through (accept or deny) on the auth process?
I see that `SafariURLHandler` implements `safariViewControllerDidFinish` delegate function (which is used to cancel pending observers) but the auth process isn't failed nor is the finished event exposed to the `OAuth2Swift` object that initiated the flow.
I require this in order to present a specific UI when the user neither accepts or denies the auth request.

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [x] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
you can set a delegate to the `SafariURLHandler` and implement `safariViewControllerDidFinish`

**Comment by shaibt** [comment]
Oops. Missed that. Thanks for the quick reply!
