### ISSUE TITLE
Imgur Oauth2 Demo authorization not working

### ISSUE THREAD

**Issue by tomkaith13** [OAuthSwift/OAuthSwift#437]
### Description:
Unable to get access token and refresh token using the imgur selection in iOS demo app.
I get back this response in the POST from the authorization server:
```
{
	"data": {
		"error": "The redirect URI provided is missing or does not match",
		"request": "\/oauth2\/authorize",
		"method": "POST"
	},
	"success": false,
	"status": 400
}
```

It looks like this [issue](https://github.com/OAuthSwift/OAuthSwift/issues/401)  was also reported last year.

### OAuth Version:
- [ ] Version 1
- [x ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [ x] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x ] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
the message seems to be clear
"The redirect URI provided is missing or does not match"

Yo must configure in Imgur the authorized redirect URI (callback url)
