### ISSUE TITLE
Cocoapods doesn't seem to have the correct version of OAuthSwift.

### ISSUE THREAD

**Issue by marcotolman** [OAuthSwift/OAuthSwift#439]
### Description:
When compiling the project with OAuthSwift I see the following warnings three times:

"'characters' is deprecated: Please use String or Substring directly" 

When I look at the latest code here on Github, the code looks good, the 'characters' part is removed and the string is used directly. So I'm guessing that maybe the latest code wasn't pushed to the Cocoapods repository.
I've tried to update the cocoapods repo (pod repo update) but that didn't help.

I have the pod defined in the Podfile like this:
pod 'OAuthSwift', '~> 1.2.0'

### OAuth Version:
- [ ] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [x] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
Hi,
That's not an issue
You can use head code with cocoapods at your own risk, or you can specifity a git hash

I have no time to push a new tag for a new tested release
