### ISSUE TITLE
OAuthSwift Objective-C interface not generated with Swift 4

### ISSUE THREAD

**Issue by drakon-ag** [OAuthSwift/OAuthSwift#440]
Compiling the pod with Swift 4, the Objective-C interface is not generated.
When i try to build with Swift 3.2 the build fails because a missing `filter` function on a dictionary.
The fix is quite simple. In the file `OAuthSwiftHTTPRequest` we have to refactor the line `239`

`finalParameters = parameters.filter { key, _ in !key.hasPrefix("oauth_") }`

with something like this:

`parameters.filter { key, _ in !key.hasPrefix("oauth_") }.forEach { finalParameters[$0] = $1 }`

When the pod is compiled with Swift 3.2 the Objective-C interface is correctly generated.

Could I submit a pull request?

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS

### Installation method:
- [x] CocoaPods

### Library version:
- [x] v1.2 (Swift 4.0)

### Xcode version:
- [x] 9.0 (Swift 4.0)
- [x] 9.0 (Swift 3.2)

- [x] objective c

**Comment by phimage** [comment]
Hi

I prefer to keep clean swift 4 code, not restore tricky code.
So I make a Dictionary extension to add filter

let me know if this work for you

**Comment by drakon-ag** [comment]
Hi @phimage ,
It works perfectly! :-)

Thanks
