### ISSUE TITLE
Coub doesn't work

### ISSUE THREAD

**Issue by gerchicov-bp** [OAuthSwift/OAuthSwift#442]
### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [x] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [x] other: I don't know if it is correct - podspec contains 1.2.1 version but cocoapods download 1.2.0

### Xcode version:
- [x] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

my code:
```
class CBOAuthViewController: UIViewController {

    @IBOutlet weak var webView: WKWebView!
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        let oauthswift = OAuth2Swift(consumerKey: "60b88af1e39803f5f68716bc364a498f9d4e733a7f76735dc48729e697de3bd6", consumerSecret: "6f62d7366a58b07377a3046922d49c4f5ab882eebe322f50467856bb7b86e049", authorizeUrl: "http://coub.com/oauth/authorize", accessTokenUrl: "http://coub.com/oauth/token", responseType: "code")
        let redirectURL = "http://gargo.of.by"
        let handle = oauthswift.authorize(
            withCallbackURL: URL(string: redirectURL)!,
            scope: "like+recoub",
            state:"Coub",
            success: { credential, response, parameters in
                print(credential.oauthToken)
                // Do your request
            },
            failure: { error in
                print(error.localizedDescription)
            }
        )
    }
}
```

In app delegate:
```
func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
        if url.host == "oauth-callback" {
            OAuthSwift.handle(url: url)
        }
        return true
    }
```

The app goes in background and Safari appears. Tried to login into safari - no effect

**Comment by phimage** [comment]
`let oauthswift` is wrong
set as class attribute to retain it in memory

Then maybe you doesn't understand the purpose of redirect url and url scheme
Why  "http://gargo.of.by" ? This url does not redirect to your app, so why app delegate code must be called?
You must have an url scheme see readme, and the url must be like myappnamescheme://oauth-callback for instance

**Comment by gerchicov-bp** [comment]
@phimage coub has a webpage with option "Callback URL". How to fill it and specify URL scheme?
Note it seems it applies only http/https schemes

**Comment by phimage** [comment]
https://github.com/OAuthSwift/OAuthSwift/wiki/API-with-only-HTTP-scheme-into-callback-URL

**Comment by gerchicov-bp** [comment]
@phimage sorry but I still don't understand:
```
class CBOAuthViewController: UIViewController {

    @IBOutlet weak var webView: WKWebView!
    
    var oauthswift: OAuth2Swift?
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        oauthswift = OAuth2Swift(consumerKey: "60b88af1e39803f5f68716bc364a498f9d4e733a7f76735dc48729e697de3bd6", consumerSecret: "6f62d7366a58b07377a3046922d49c4f5ab882eebe322f50467856bb7b86e049", authorizeUrl: "http://coub.com/oauth/authorize", accessTokenUrl: "http://coub.com/oauth/token", responseType: "code")
        let redirectURL = "http://testcoub2.com/auth/callback"
        let handle = oauthswift?.authorize(
            withCallbackURL: URL(string: redirectURL)!,
            scope: "like+recoub",
            state:"Coub",
            success: { credential, response, parameters in
                print(credential.oauthToken)
            },
                failure: { error in
                    print(error.localizedDescription)
            }
        )
    }
}
```
It still doesn't return to the app.

Callback URL is set to "http://testcoub2.com/auth/callback" in coub settings.
If I try to use in code "testcoub2://auth/callback" - it writes that redirect url is incorrect (doesn't equal to the one set in settings).
If I try to set "testcoub2://auth/callback" in coub settings - it writes that this url is invalid.

**Comment by gerchicov-bp** [comment]
@phimage ok I understood that:
1)coub doesn't allow custom redirect url schemes
2)anyways I could use inner web browser

The one thing I still can't understand - `success` and `failure` blocks are not called. Anyways something is still incorrect with them - they should be called or if they are not necessary then there should be `authorize` method without these params (or success block should be marked as optional)

**Comment by phimage** [comment]
success or failure block are called if `OAuthSwift.handle(url: url)` is called 
according to the url query parameters

**Comment by gerchicov-bp** [comment]
@phimage Ok it seems I have found a mistake in your own code. Compare implementation for iOS:
```
func webView(_ webView: UIWebView, shouldStartLoadWith request: URLRequest, navigationType: UIWebViewNavigationType) -> Bool {
```
and OSX:
```
func webView(_ webView: WKWebView, decidePolicyFor navigationAction: WKNavigationAction, decisionHandler: @escaping (WKNavigationActionPolicy) -> Void) {
```

It seems these methods perform the same work but in OSX you call `AppDelegate.sharedInstance.applicationHandle(url: url)` but not in iOS. So in your example `success` and `failure` blocks will have never been called.
Additionally:
```
// Call here AppDelegate.sharedInstance.applicationHandleOpenURL(url) if necessary ie. if AppDelegate not configured to handle URL scheme
```
`applicationHandleOpenURL` method doesn't exist.

**Comment by phimage** [comment]
do you know that swift has been updated, so the signature change? this is a just a comment so no refactor...


and no there is no issue in code
just no implementation in demo app for iOS using the delegate, normal callback url is used using demo url scheme
