### ISSUE TITLE
WatchOS 4.3 series 3 

### ISSUE THREAD

**Issue by johnlietzke** [OAuthSwift/OAuthSwift#443]
### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [ ] iOS :
- [ ] OSX :
- [ ] TVOS :
- [x] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [ ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by johnlietzke** [comment]
Could you please give a working example of how to implement OauthSwifty for google in WatchOS.  I continue to get an error when executing the code I have tried to modify.

**Comment by phimage** [comment]
You get an error... umm...

Then no, watchOS is not really supported.
