### ISSUE TITLE
Objective C Example

### ISSUE THREAD

**Issue by lewis-smith** [OAuthSwift/OAuthSwift#445]
### Description:

I have a project which is mostly Objective C, but I am trying to do new work in Swift where possible.

I am adding an integration with Fitbit.

I have created a class in Swift to handle all the business logic, but I am looking to deal with the URL handler in `AppDelegate` which is an Objective C file.

I am not able to get the correct syntax for this.

The code (and this template!) implies support for Objective C, but a worked example for this would be hugely appreciated

Tried:

    @import OAuthSwift;

     // ...

    - (BOOL)application:(UIApplication *)application
                openURL:(NSURL *)url
      sourceApplication:(NSString *)sourceApplication
             annotation:(id)annotation {

        if ([url.host isEqualToString: @"oauth-callback"]) {
            [OAuthSwift handleUrl:url];
            return true;
        }
    }

Gets compile error:

    No known class method for selector handleUrl

### OAuth Provider (Twitter, Github, ..):

Fitbit

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [x] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [x] objective c

**Comment by phimage** [comment]
maybe try with swift 3.2 because I do not try objc since swift 4

I make some methods prefixed with objc_ to handle some compatibility issue with objective c
in Sources/Objc.swift
I think maybe some annotation must be added, like `@objc`

**Comment by lewis-smith** [comment]
Ok thanks :) 

As a work around I added a pass through method to my custom class:

    @objc func handle(url: URL) {
        OAuthSwift.handle(url: url)
    }

Which I can call from Objective C. If I am not missing something obvious I will leave this in place for now.

**Comment by ddaddy** [comment]
I know this is an old issue, but I am also having this problem.
I am using `1.4.1` as suggested by the readme, but it seems `OAuthSwift.handle(url: url)` is not exposed to `objc`
