### ISSUE TITLE
How do you run the unit test suite for this project?

### ISSUE THREAD

**Issue by djk12587** [OAuthSwift/OAuthSwift#447]
Whenever I try to run a test on an iOS simulator get 22 compile errors from Kanna. I did perform a pod install.

I noticed the podfile does not specify a version for Swifter or Erik. Did these libraries get updated recently and are no longer compatible with the project?

Not sure it matters, but I can build the project normally.

**Comment by phimage** [comment]
thanks for telling me
I make some update on dependencies and fix one test
