### ISSUE TITLE
startAuthorizedRequest() fails to refresh the access token on Google Api

### ISSUE THREAD

**Issue by mixable** [OAuthSwift/OAuthSwift#450]
### Description:

I use OAuth2Swift for authentication on Google. After updating from version 1.1.2 to version 1.2.0, requesting an access token is not possible anymore.

To call the Google api, I use startAuthorizedRequest() in the following way. In 1.1.2 this automatically handled the authorization:

    let oauthswift = OAuth2Swift(
        consumerKey:    "... .apps.googleusercontent.com",
        consumerSecret: "",
        authorizeUrl:   "https://accounts.google.com/o/oauth2/auth?access_type=offline&prompt=consent",
        accessTokenUrl: "https://accounts.google.com/o/oauth2/token",
        responseType:   "code"
    )
    oauthswift.client.credential = ...
    oauthswift.startAuthorizedRequest(
        "https://www.googleapis.com/gmail/v1/users/me/messages/send",
        method: .POST,
        parameters: [
            "raw": "..."
        ],
        headers: [
            "Content-Type": "application/json",
            "Accept": "application/json"
        ],
        onTokenRenewal: { (credential) in
            // ...
        },
        success: { (response) in
            // ...
        }
    ) { (error) in
        // ...
    }

The problem appears, when the current token expired and a new token is requested using the refresh token (inside the requestOAuthAccessToken() method). The error returned is:

    invalid_request: Invalid header Content Type
	
It turned out, that this is a problem of the header I use. The send API (3) requires "Content-Type: application/json" to work, the access token API (2) does not allow this Content-Type. But the method requestOAuthAccessToken() uses the same header for both requests.

The reason for the same header is line 239 (OAuth2Swift.swift), which was changed from (v1.1.2):

    var finalHeaders: OAuthSwift.Headers? = nil

to (v1.2.0):

    var finalHeaders: OAuthSwift.Headers? = headers

The code seems to be correct, but I was wondering if anybody else has this problem. Or are there any suggestions, how to deal with this behavior?

### OAuth Provider (Twitter, Github, ..):

Google, the API endpoints are:
(1) Authorize Url https://accounts.google.com/o/oauth2/auth?access_type=offline&prompt=consent
(2) Access Token Url: https://accounts.google.com/o/oauth2/token
(3) Send Email API:	https://www.googleapis.com/gmail/v1/users/me/messages/send

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [x] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ][x].6
- [ ][x]her: (Please fill in the version you are using.)

### Xcode version:
- [x] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
I think that the fix for 1.2 reveal a real issue
why use request issue for authentication

there is this code in startAuthorizedRequest
```swift
            case OAuthSwiftError.tokenExpired:
                _ = self.renewAccessToken(withRefreshToken: self.client.credential.oauthRefreshToken, headers: headers, ...
```
@mixable  maybe removing the header here will fix your issue
and if we want some specific header for renew, it must be another parameter

**Comment by mixable** [comment]
@phimage yes, using a different parameter for the renew request should fix the problem

**Comment by phimage** [comment]
I do want to change the behaviour if some people have provider that need some header so I add a new parameters called `renewHeaders`

So @mixable you can do 
```swift
oauthswift.startAuthorizedRequest(
    "https://www.googleapis.com/gmail/v1/users/me/messages/send",
    method: .POST,
    parameters: [
        "raw": "..."
    ],
    headers: [
        "Content-Type": "application/json",
        "Accept": "application/json"
    ],
    renewHeaders: [:], // here a empty header for renew request
    onTokenRenewal: { (credential) in
        // ...
    },
    success: { (response) in
        // ...
    }
) { (error) in
    // ...
}
```
