### ISSUE TITLE
possible retention loop with SafariURLHandler

### ISSUE THREAD

**Issue by shaibt** [OAuthSwift/OAuthSwift#451]
### Description:
Hi,
Seems that these 2 classes hold strong references to each other: 
- `SafariURLHandler` holds a strong reference to `OAuthSwift` through its `oauthSwift` property
-  `OAuthSwift` holds a strong reference to `SafariURLHandler` through its `authorizeURLHandler` property

Is this by design? when using the `SafariURLHandler` as shown in the docs I get a retention cycle and neither of the two get released as a result. 

### OAuth Version:
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :

### Installation method:
- [x] CocoaPods

### Library version:
- [x] v1.2 (Swift 4.0)

### Xcode version:
- [x] 9.3 (Swift 4.1)

**Comment by phimage** [comment]
by design...
But yes! we need a weak reference in SafariURLHandler to break the cycle

You could PR if you want

**Comment by phimage** [comment]
merged thanks you!
