### ISSUE TITLE
Failing on handle(url: url)

### ISSUE THREAD

**Issue by TannerJuby1** [OAuthSwift/OAuthSwift#454]
### Description:

All parts of the OAuth process is working as expected, except for the `OAuthSwift.handle(url: url)` piece in the app delegate on the `open url` function in the AppDelegate. I must be missing a piece of the set up that is not defined in the documentation. 

       let oauthswift = OAuth2Swift(
            consumerKey: "**************",
            consumerSecret: "",
            authorizeUrl: "<authorize url>",
            accessTokenUrl: "",
            responseType: "code"
        )
        
        oauthswift.allowMissingStateCheck = true
        
        oauthswift.authorizeURLHandler = SafariURLHandler(viewController: self, oauthSwift: oauthswift)
                        
        // Authorize
        oauthswift.authorize(withCallbackURL: "com.devetry.ytp:", scope: "profile", state: "Custom", success: { (credential, response, params) in
            print("SUCCESS")
            print(credential)
        }) { (error) in
            print("ERROR: \(error.localizedDescription)")
        }

I am using the ***SafariURLHandler*** due to the easy handling of the web view you have in place, and have followed all the steps. I have the `com.devetry.ytp` URL Scheme set up in my Info.plist, and the app is able to successfully open the SafariWebView, authenticate, then close. 

But in the AppDelegate, I have this piece of code: 

        func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
            print("Open Url: \(url)")
        
            OAuthSwift.handle(url: url)
        
            return true
        }

The url that is printed from my `print()` function is as expected, but the `handle()` function completes the `authorize` function in the failure block with a -11 error...

I assume my problem has something to do with my callback url (com.devetry.ytp:) but no matter where I look, I can't seem to find what I am missing. Can someone help me find out what going wrong? 

Thanks!

### OAuth Provider? (Twitter, Github, ..): 
custom oauth provider

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [ ] v1.2.1
- [x] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by TannerJuby1** [comment]
Sorry for the lack of vocabulary, but what do you mean by retain my OAuthSwift object?

And yes, I get a -11 error, not a -10. The OAuthSwiftError.response is a 403 HTTP error, so forbidden. But that makes zero sense to me, I've already handled the authorization, and it succeeded and sent me back a code in the url that the `handle()` function is attempting to handle

**Comment by phimage** [comment]
could you post here the url receive passed to OAuthSwift.handle(

**Comment by TannerJuby1** [comment]
Yeah of course. So with the callback url set to 'com.devetry.ytp://host/_oauth/drupal?close', the url that is being passed to the OAuth.handle() is: 

`com.devetry.ytp://host/_oauth/drupal?close&code=the_code`

**Comment by phimage** [comment]
Strange, if the code is in query...the serverError must not be thrown

**Comment by TannerJuby1** [comment]
I am getting back the serverError: [No access_token, no code and no error provided by server]

**Comment by phimage** [comment]
Difficult to help without debugging it

In OAuthSwift2.swift
there is `open func authorize(withCallbackURL callbackURL: URL, scope: String, state: String, parameters: Parameters = [:], headers: OAuthSwift.Headers? = nil, success: @escaping TokenSuccessHandler, failure: FailureHandler?) -> OAuthSwiftRequestHandle? {`

The code transform url to dictionary
```swift
if let query = url.query {
    responseParameters += query.parametersFromQueryString
}
```

Then your error must not be thrown if there is code inside query
```swift
if let code = responseParameters["code"]
```

So with debug we must look at the content of `responseParameters`

Maybe the "close" make an issue

**Comment by phimage** [comment]
I make a unit test and see the error
The "close" make the failure
close&toto=1&code= will work
I will fix

**Comment by TannerJuby1** [comment]
Thanks for the quick update!

After changing my callback url to  `com.devetry.ytp://host/_oauth/drupal?close=1` I am now getting a `retain (-11)` error. I remember you said something about I need to retain my oauthswift object, as a class attribute, so I assume that's what I need to do.. But what do you mean by this? Can you point me to an example?

Thanks!

**Comment by phimage** [comment]
See demo app

Let oauthswift = is forbidden 
Do
Self.oauthswift = ...

**Comment by TannerJuby1** [comment]
Okay, thanks!

So now I am getting a -11 error, which turns out to be a `403: Forbidden` error from the server. I believe the issue lies with headers. I am passing in a session cookie in the headers field in the `authorize()` function. When the handle() function is called with the callback url,  are these headers still being passed? I think that could be causing the forbidden piece...
