### ISSUE TITLE
Tumblr logout

### ISSUE THREAD

**Issue by DhavalUmraliya** [OAuthSwift/OAuthSwift#455]
### Description:
when I log out in safari. And re-login, I get dashboard instead of an authorized screen.
rest perfectly work for a single user. I need to authorize multiple accounts.

### OAuth Provider? (Twitter, Github, ..):
Tumblr

### OAuth Version:
- [] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [ ] v1.2.1
- [ ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ ] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)
-[X] 8.2 (8C38)

- [ ] objective c

**Comment by phimage** [comment]
Please set a correct name for your issue. I change it

Maybe this could help
https://github.com/OAuthSwift/OAuthSwift/wiki/Logout
