### ISSUE TITLE
Swift 4.1 warnings

### ISSUE THREAD

**Issue by aranasaurus** [OAuthSwift/OAuthSwift#462]
### Description:
When building OAuthSwift in Xcode 9.3 there are 4 deprecation warnings.

### OAuth Version:
- [ ] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [x] head
- [ ] v1.2.1
- [ ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by aranasaurus** [comment]
Any idea when there a might be a release that includes this? I'd like to get rid of these compiler warnings soon :)

**Comment by phimage** [comment]
Do not know, I need time to test before releasing. And I have not for the moment

You can edit your pod file to specify the git hash with your modification or the branch head.

**Comment by aranasaurus** [comment]
Yep, just wanted to check if there were plans for a release before doing that. Thanks for the quick response!
