### ISSUE TITLE
Support of Microsoft Azure AD

### ISSUE THREAD

**Issue by igoMobile** [OAuthSwift/OAuthSwift#465]
### Description:

Hi, 
is there a way to use OAuthSwift with Microsoft Azure AD and it's OAuth 2.0? The problem is, after registering the app in Azure portal one gets only client_id, but no client_secret... Can OAuthSwift handle this case?

### OAuth Provider? (Twitter, Github, ..):
Azure AD

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x ] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [x ] v1.2.1
- [ ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ x] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
Hi
Did you try with empty string?

**Comment by phimage** [comment]
closed, no response
