### ISSUE TITLE
Tag OAuthSwift with "1.2.2" and tag OAuthSwiftAlamofire with "0.2.0"

### ISSUE THREAD

**Issue by neoneye** [OAuthSwift/OAuthSwift#469]
### Description:

The latest release of [OAuthSwift is 1.2.1](https://github.com/OAuthSwift/OAuthSwift/releases/tag/1.2.1) was made 4 Feb 2018.

When I do `pod lib lint` with my own cocoapod, then I'm seeing warnings related to OAuthSwift and OAuthSwiftAlamofire.

    - WARN  | xcodebuild:  OAuthSwift/Sources/Int+OAuthSwift.swift:29:18: warning: 'deinitialize()' is deprecated: the default argument to deinitialize(count:) has been removed, please specify the count explicitly
    - WARN  | xcodebuild:  OAuthSwift/Sources/Int+OAuthSwift.swift:30:18: warning: 'deallocate(capacity:)' is deprecated: Swift currently only supports freeing entire heap blocks, use deallocate() instead
    - WARN  | xcodebuild:  OAuthSwift/Sources/String+OAuthSwift.swift:93:38: warning: 'IndexDistance' is deprecated: all index distances are now of type Int
    - WARN  | xcodebuild:  OAuthSwift/Sources/String+OAuthSwift.swift:98:40: warning: 'IndexDistance' is deprecated: all index distances are now of type Int
    - WARN  | xcodebuild:  OAuthSwift/Sources/SHA1.swift:142:104: warning: 'IndexDistance' is deprecated: all index distances are now of type Int
    - WARN  | xcodebuild:  OAuthSwift/Sources/SHA1.swift:142:140: warning: 'IndexDistance' is deprecated: all index distances are now of type Int
    - WARN  | xcodebuild:  OAuthSwift/Sources/SHA1.swift:144:22: warning: 'IndexDistance' is deprecated: all index distances are now of type Int
    - WARN  | xcodebuild:  OAuthSwift/Sources/String+OAuthSwift.swift:49:22: warning: 'init' is deprecated: Please use String or Substring directly
    - WARN  | xcodebuild:  OAuthSwift/Sources/String+OAuthSwift.swift:49:29: warning: 'characters' is deprecated: Please use String or Substring directly
    - WARN  | xcodebuild:  OAuthSwift/Sources/Utils.swift:13:33: warning: 'characters' is deprecated: Please use String or Substring directly
    - WARN  | xcodebuild:  OAuthSwift/Sources/Utils.swift:19:30: warning: 'characters' is deprecated: Please use String or Substring directly

In `my-own-pod.podspec` it looks like this:

    s.dependency 'OAuthSwift', '~> 1.2.0'
    s.dependency 'OAuthSwiftAlamofire'

I can't switch to `OAuthSwift` 1.2.1, because that breaks `OAuthSwiftAlamofire`.

I made another [issue on OAuthSwiftAlamofire](https://github.com/OAuthSwift/OAuthSwiftAlamofire/issues/10), where I'm more or less writing the same as in this issue.

### OAuth Provider? (Twitter, Github, ..):

3rd party provider

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [x] head
- [x] v1.2.1
- [ ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 9.4 (Swift 4.1)
- [ ] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by zapjonny** [comment]
Yes please, fix these deprecations/warnings 🙏🏻

![screen shot 2018-06-22 at 9 57 51](https://user-images.githubusercontent.com/20237481/41752492-c1449cbe-7602-11e8-9b93-b47e4fa3a5fa.png)

**Comment by phimage** [comment]
you can use any commit hash or head in your Podfile 

I cannot do it now (i am sick)

**Comment by phimage** [comment]
🎉  Congrats

 🚀  OAuthSwift (1.2.2) successfully published
 📅  June 26th, 11:55
 🌎  https://cocoapods.org/pods/OAuthSwift
 👍  Tell your friends!
