### ISSUE TITLE
Callback URL for Twitter?

### ISSUE THREAD

**Issue by jonnyijapan** [OAuthSwift/OAuthSwift#474]
What is the callback URL used for Twitter?

Recently Twitter has started to require a callback URL for OAuth 1.0a.

**Comment by phimage** [comment]
Recently? Callback url is necessary to get the access token to the api. 👿 
It is your own url to get it (http server or application url scheme)
Please read the README and wiki

**Comment by jonnyijapan** [comment]
I mean for the demo - I see now that the existing one is `http://oauthswift.herokuapp.com/callback/twitter`
but we have to set it to the app one, should be something like `oauth-swift://oauth-callback/twitter` ?

**Comment by phimage** [comment]
This one is for the demo app, an application with url scheme oauth-swift
You must have your own

and yes you must white list some urls for some providers, and twitter I think need it

**Comment by jonnyijapan** [comment]
The wiki says

> Some API does'nt accept custom url scheme (ex: myapp://) into callback URL (ex: Linkedin oauth v2, Twitter oauth v1), only http is accepted

which isn't really true anymore for Twitter. They now allow and require custom url schemes for apps. https://twittercommunity.com/t/action-required-sign-in-with-twitter-users-must-whitelist-callback-urls/105342

**Comment by phimage** [comment]
@jonnyijapan I do not see where custom url scheme must be used in the link
this talk only about white listed callback urls or I miss something

**Comment by phimage** [comment]
my app setup in twitter
![screen shot 2018-06-26 at 16 09 02](https://user-images.githubusercontent.com/8875768/41917736-54019470-795b-11e8-9678-6088ac42e1d9.png)
