### ISSUE TITLE
Can not get an access token using OAuth1Swift on Twitter.

### ISSUE THREAD

**Issue by lenlenlen** [OAuthSwift/OAuthSwift#476]
### Description:

can not get an access token using OAuth1Swift on Twitter.

Since Twitter started checking Callback, it can not be done (https://goo.gl/5qtH2j)

Callback is the same as the URL scheme of the application set on apps.twitter.com, and the setting is correct.

The error comes out as "The operation could not be completed. (OAuthSwiftError error - 10.)".

### OAuth Provider? (Twitter, Github, ..):
Twitter

### OAuth Version:
- [x ] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [x] Carthage
- [ ] CocoaPods
- [ ] Manually

### Library version:
- [x] head
- [ ] v1.2.1
- [ ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 9.4 (Swift 4.1.2)
- [] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
please make a search on your error
-10 =retain
