### ISSUE TITLE
Updated 1.2.2, encountering compile-time errors

### ISSUE THREAD

**Issue by garyhooper** [OAuthSwift/OAuthSwift#477]
### Description:
After updating to 1.2.2 from 1.2.0, I am encountering 2 compiler errors:

```
SHA1.swift:142: Binary operator '-' cannot be applied to operands of type 'D.IndexDistance' and 'Int'

Int+OAuth.swift:30: Missing argument for parameter 'capacity' in call
```

### OAuth Version:
- [x] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [x] v1.2.2
- [ ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ ] 9.3 (Swift 4.1)
- [x] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
Hi

As you can see after checking the Xcode and library version, you need to upgrade your Xcode and choose newer Swift if you want to update OAuthSwift

Alternatively, you can keep old version
I will not maintain a swift 4.0 version branch

Ps/ my bad to not make instead a 1.3 version

**Comment by garyhooper** [comment]
Understood. Thanks for the quick response.
