### ISSUE TITLE
Storing OAuthSwiftCredential in UserDefaults

### ISSUE THREAD

**Issue by mbrahimi617** [OAuthSwift/OAuthSwift#481]
So I'm using latest version of Xcode, Swift, and OAuthSwift with a custom PingFederate endpoint that implements OpenID Connect on top of OAuth2. This will generate refresh tokens in when using the returned credential in the success handler, so I would like to store this credential to create automatic login without having to sign in again.

To my knowledge, OAuthSwiftCredential is a Codable object, at least in newer versions of the framework which I have installed via CocoaPods. However, every time I try to store the credential from the success handler in the User Defaults I get a SIGABRT error. I would really appreciate some help.

**Comment by jrtibbetts** [comment]
I posted a similar issue (https://github.com/OAuthSwift/OAuthSwift/issues/453) in May, and it was fixed, but no release has been issued yet that includes it, not even 1.2.2, which is the latest one that's posted.

**Comment by phimage** [comment]
Closed because issue template removed
