### ISSUE TITLE
Callback for getting valid tokens or an error

### ISSUE THREAD

**Issue by gasparuff** [OAuthSwift/OAuthSwift#484]
### Description:
I was using https://github.com/openid/AppAuth-iOS in my current iOS project but now I want to switch to OAuthSwift for better customization of the shown webview to log in. I have my own Networkclient implementation with RxSwift and a lot of logic, so I'd like to wrap my existing request with a function from which I receive the valid token in a callback. I don't want to build another `oauthswift.client.request(...)`, instead I just want something like this:

```
oauthswift.client.getTokens { (accessToken, error) in
    // Here I would expect a valid accessToken, which I then can use in my own request. If the current accessToken is expired, I'm expecting a fresh one (refreshed with the refreshToken) or an error, in case the refreshToken is also expired already.
    let myRequest = MyRequest(url: "https://...")
    myRequest.setupToken(token: accessToken)
    myNetworkClient.execute(myRequest)
}

```

Is there any way to do that?

### OAuth Provider? (Twitter, Github, ..):
Custom OAuth provider

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [ ] v1.2.1
- [x] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by gasparuff** [comment]
Ok it's quite simple actually. Just wrote a small helper function for that, in case anyone needs it...

`    public func getTokens(completion: @escaping (_ token: String) -> Void, failCompletion: @escaping (Error?) -> Void) {
        if let credentials = self.oauthCredentials {
            if credentials.isTokenExpired() {
                debugPrint("token expired, going to refresh")
                self.oauthswift?.renewAccessToken(withRefreshToken: credentials.oauthRefreshToken, success: { (credential, response, parameters) in
                    debugPrint("token refreshed successfully")
                    self.oauthCredentials = credential
                    self.idToken = parameters["id_token"] as? String
                    completion(credential.oauthToken)
                }, failure: { (error) in
                    print("error refreshing token - probably refresh token expired: \(error)")
                    failCompletion(error)
                })
            } else {
                completion(credentials.oauthToken)
            }
        } else {
            failCompletion(nil)
        }
    }
`

**Comment by phimage** [comment]
Yes for oauth2 you can do that
Thanks to respond to yourself.
