### ISSUE TITLE
Can we use OAuthSwift for Google SignIn and Facebook?

### ISSUE THREAD

**Issue by TofPlay** [OAuthSwift/OAuthSwift#485]
### Description:

Can we use OAuthSwift for Google SignIn and Facebook?

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS 10
- [x] iOS 11
- [x] iOS 12

### Installation method:
- [x] Carthage

### Xcode version:
- [x] 9.4.1 (Swift 4.1.2)

**Comment by phimage** [comment]
I think you can
I do not know all the difference but have a token allow you to check that the user exist on Facebook or google
And if it just to login, use the minimum scope, no need to allow to post message for instance on Facebook
