### ISSUE TITLE
oauthswift.client.get using token

### ISSUE THREAD

**Issue by harryyuanfeng** [OAuthSwift/OAuthSwift#487]
### Description:
how do we make request with token?

Users authorize the app and the app got the token. Next time users open the app again, we want to use the token to make new request without brining users to authorization page.
### OAuth Provider? (Twitter, Github, ..):
fitbit2

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [x] v1.2.1
- [ ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
For that you must store the credential
then restore it when starting

https://github.com/OAuthSwift/OAuthSwift/wiki/Store-credential

**Comment by harryyuanfeng** [comment]
Thanks, 

It works.
