### ISSUE TITLE
Authorize throws error code -11(request error). However, same parameters work in REST Client.

### ISSUE THREAD

**Issue by Ujjwal-N** [OAuthSwift/OAuthSwift#491]
### OAuth Version:
- [ x] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [x ] Carthage
- [ ] CocoaPods
- [ ] Manually

### Library version:
- [x ] head
- [ ] v1.2.1
- [ ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ x] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

```
var oauthswift = OAuth1Swift(
            consumerKey:    "key",
            consumerSecret: "secret",
                        requestTokenUrl: "https://api.schoology.com/v1/oauth/request_token",
                    authorizeUrl:    "https://pausd.schoology.com/oauth/authorize?",
                    accessTokenUrl:  "https://api.schoology.com/v1/oauth/access_token"
        )
        oauthswift.allowMissingOAuthVerifier = true;
        let handle = oauthswift.authorize(
            withCallbackURL: URL(string: "oauth-swift://oauth-callback/twitter")!,
            success: { credential, response, parameters in
                print(credential.oauthToken)
                print(credential.oauthTokenSecret)
                print(parameters["user_id"])
                // Do your request
        },
            failure: { error in
                print(error.localizedDescription)
        }
  )
```
Here is a screenshot of Insomnia, the REST Client I was using:
![screen shot 76](https://user-images.githubusercontent.com/15056315/45406936-d09ba180-b61c-11e8-8d79-d83367d8f040.jpg)

Any help would be appreciated!
Thanks

**Comment by phimage** [comment]
Please read wiki or code

**Comment by Ujjwal-N** [comment]
@phimage, Sorry about that. Here is the full error code:
```
The operation couldn’t be completed. (OAuthSwiftError error -11.)
2018-09-11 23:51:46.092238-0700 SkoVikes[10965:4427205] TIC Read Status [1:0x0]: 1:57
2018-09-11 23:51:46.092329-0700 SkoVikes[10965:4427205] TIC Read Status [1:0x0]: 1:57
```

**Comment by phimage** [comment]
I do think that it is the full error
There is an error in requestError, si the enum

**Comment by Ujjwal-N** [comment]
@phimage Are you referring to this file: 
 https://github.com/OAuthSwift/OAuthSwift/blob/master/Sources/OAuthSwiftError.swift ?

**Comment by phimage** [comment]
Yes
You can get the underlyingError or message

**Comment by Ujjwal-N** [comment]
```    
case requestError(error: Error, request: URLRequest)
    /// Request cancelled
```
Why did the request get cancelled? I have no idea.

**Comment by phimage** [comment]
/// Request cancelled
is the message of the Error (NSError) ie. underlyingError??

I think it is more verbose, with error code... that just a network error full of information

**Comment by Anuj-Jha** [comment]
Hi @Ujjwal-N , did you get this error solved?
I am also facing same issue.
