### ISSUE TITLE
Does OAuthSwift support the Authorization code with proof key flow?  I am not seeing where we can send a code challenge.

### ISSUE THREAD

**Issue by scottblomquistjr** [OAuthSwift/OAuthSwift#501]
### Description:
I am trying to use this library with Okta Authorization code with proof key flow.  However I keep getting an error on my server "code_challenge is missing".  Is this flow not supported?

### OAuth Provider? (Twitter, Github, ..):
Okta

### OAuth Version:
- [ ] Version 1
- [x ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ x] CocoaPods
- [ ] Manually

### Library version:
- [ x] head
- [ ] v1.2.1
- [ ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ ] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [x ] other: (Please fill in the version you are using.)
10 (Swift 4.2)

- [ ] objective c

**Comment by BjoeBrunn** [comment]
I have the same issue. 
There is no way to insert a code_verifier parameter during the second step to get the access token with the code provided in the first step.
As a quick workaround I inserted a new variable codeVerifier in the OAuth2Swift code, a new initializer and modified the postOAuthAccessTokenWithRequestToken function in order to add this extra parameter as the parameters in the original function are limited to client_id, client_secret, code and grant_type.
This way, authentication with PKCE works.

**Comment by phimage** [comment]
https://tools.ietf.org/html/rfc7636

**Comment by mraible** [comment]
@BjoeBrunn I’d love to see your code too. I’m trying to make an Ionic 4 app work with Okta using https://github.com/moberwasserlechner/capacitor-oauth2 (which uses this library).

**Comment by phimage** [comment]
readme edited by #510
implementation done by #506

I close
If any issue, feel free to open a new github issue

**Comment by moberwasserlechner** [comment]
Hey,

It would be really appreciated if you create a release with PKCE in Cocoapods.

I develop a library so I have to use a version from cocoapods because other depends on it. For testing I could use the master directly but for a production release it's to risky.

Thanks & BR

**Comment by mraible** [comment]
I agree! A release with this feature would be awesome.

**Comment by phimage** [comment]
🎉  Congrats

 🚀  OAuthSwift (1.3.0) successfully published
 📅  February 21st
 🌎  https://cocoapods.org/pods/OAuthSwift
 👍  Tell your friends!
