### ISSUE TITLE
Fresh compile with Xcode 10.1 produces warning

### ISSUE THREAD

**Issue by EdwardD20** [OAuthSwift/OAuthSwift#502]
### Description:
Compile warnings...

/Users/ed/Downloads/OAuthSwift-master/OAuthSwift.xcodeproj The file “Pods-OAuthSwiftTests.debug.xcconfig” couldn’t be opened because there is no such file. (/Users/ed/Downloads/OAuthSwift-master/Pods/Target Support Files/Pods-OAuthSwiftTests/Pods-OAuthSwiftTests.debug.xcconfig)

/Users/ed/Downloads/OAuthSwift-master/OAuthSwift.xcodeproj The file “Pods-OAuthSwiftTests.release.xcconfig” couldn’t be opened because there is no such file. (/Users/ed/Downloads/OAuthSwift-master/Pods/Target Support Files/Pods-OAuthSwiftTests/Pods-OAuthSwiftTests.release.xcconfig)

### OAuth Provider? (Twitter, Github, ..):
Yahoo

### OAuth Version:
- [ ] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [ ] iOS :
- [X ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [X ] Manually

### Library version:
- [ X] head
- [ ] v1.2.1
- [ ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ ] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ X ] other: Xcode 10.1 (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
It is compile issue for test target, not for the framework
You can only test using the workspace not the project and make a a cocoadpod commande : pod update
