### ISSUE TITLE
oauthswift with facebook app

### ISSUE THREAD

**Issue by kunusiths** [OAuthSwift/OAuthSwift#508]
here is my code
with normal safari browser it is working but not with facebook app.i tried the process mentioned in native app thread which was opened 2 years before nut it didnt work.pls help

let oauthswift = OAuth2Swift(
consumerKey: "167108074192100", // [1] Enter google app settings
consumerSecret: "", // No secret required
authorizeUrl: "https://www.facebook.com/dialog/oauth",
accessTokenUrl: "https://graph.facebook.com/oauth/access_token",
responseType: "token"
)

    var isFacebookAppInstalled: Bool = {
        let appUrl = URL(string: "fbauth2://app")
        return UIApplication.shared.canOpenURL(appUrl!)
    }()
    
    oauthswift.allowMissingStateCheck = true
    oauthswift.authorizeURLHandler = NativeAppHandler.sharedInstance
    let state = generateState(withLength: 20)
    guard let rwURL = URL(string:"fbauth2://authorize?response_type=token&client_id=167108074192100&redirect_uri=fb167108074192100://oauth-callback") else { return }
    //https://graph.facebook.com/oauth/authorize?response_type=token&client_id=167108074192100&redirect_uri=fb167108074192100://oauth-callback

    let _ = oauthswift.authorize(withCallbackURL: rwURL, scope: "public_profile", state: state, success: { (credential, response, parameters) in
        print("\(credential)\(response)\(parameters)")
        let _ = oauthswift.client.get(
            "https://graph.facebook.com/me?",
            parameters: ["fields": "id, name, first_name, last_name, email"],
            success: { response in
                let dataString = response.string!
                print(dataString)
        }, failure: { error in
            print(error)
        })

    }) { (error) in
        self.presentAlert("error", message: error.localizedDescription)
    }
class NativeAppHandler: OAuthSwiftURLHandlerType {
public static var sharedInstance : NativeAppHandler = NativeAppHandler()

@objc open func handle(_ url: URL) {
    if #available(iOS 10.0, *) {
        UIApplication.shared.open(url, options: [:], completionHandler: nil)
    } else {
        // Fallback on earlier versions
    }
}
}

I got this message in webview even i want to open facebook app i got this webview only:
Can't Load ULR: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.

**Comment by phimage** [comment]
Stop posting new issue

**Comment by kunusiths** [comment]
?can u give me ur chat number or anything

________________________________

**Comment by phimage** [comment]
Nope, I do no work for you
Please read github term and condition or I will report abuse from you

And read me, go ask your question not on github please

**Comment by kunusiths** [comment]
how can u tell like that this is very important

**Comment by kunusiths** [comment]
if user everytime gets to browser its not good experience.please help

**Comment by kunusiths** [comment]
give me some way to go to facebook app please
