### ISSUE TITLE
Crash when trying to call authorize function with PKCE

### ISSUE THREAD

**Issue by troligtvis** [OAuthSwift/OAuthSwift#513]
### Description:
Recursion of same function (`OAuth2Swift:357`) and resulting in crashing the app. 
 
<img width="875" alt="screenshot 2019-02-13 at 08 20 36" src="https://user-images.githubusercontent.com/7541370/52697290-74450100-2f71-11e9-8d66-060a539f950a.png">

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [x] Manually

### Library version:
- [x] head
- [ ] v1.2.1
- [ ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
I do not test the last PR #511
Maybe it is a general issue with all methods
