### ISSUE TITLE
Setting Content-Type header for OAuth1 

### ISSUE THREAD

**Issue by csauvage** [OAuthSwift/OAuthSwift#515]
### Description:
Issue while authorizing

### OAuth Provider? (Twitter, Github, ..):
[Clever-cloud](https://clever-cloud.com)
📖Docs : [https://www.clever-cloud.com/doc/api/](https://www.clever-cloud.com/doc/api/)

### OAuth Version:
- [x] Version 1

### OS (Please fill the version) :
- [x] macOS :

### Installation method:
- [x] Carthage

### Library version:
- [x] v1.2 (Swift 4.0)

### Xcode version:
- [x] other: 10.1

*Issue*

```swift 

let oAuthConsumer = OAuth1Swift(
            consumerKey: consumerKey,
            consumerSecret: consumerSecret,
            requestTokenUrl: CleverAPIEndpoint.oAuthRequestToken.url(),
            authorizeUrl: CleverAPIEndpoint.oAuthAuthorize.url(),
            accessTokenUrl: CleverAPIEndpoint.oAuthAccessToken.url()
        );
        
        oAuthConsumer.authorize(
            withCallbackURL: "clever-mac://app/login",
            success: { (credentials, response, parameters) in
                print("success");
        }) { (error) in
            print(error)
            print(error.localizedDescription)
        }


```

I got an error 500 while authorizing

*Solving tip*
It seems that it's linked to the header `Content-Type`  of the `requestTokenUrl` request. It doesn't have the `application/x-www-form-urlencoded` required value. Where to set this header ? 

Moreover @phimage : Analysing the request on Charles, it seems that the **body of the resquest** is empty 

![image](https://user-images.githubusercontent.com/3155160/52975310-05addc00-3393-11e9-88c5-d10479f89331.png)

Any help will be appreciated ! Stucking around for a while now :/

**Comment by phimage** [comment]
There is an header optional parameter
But for Content-type I never tested it

**Comment by csauvage** [comment]
```swift
      
        oauthSwift = OAuth1Swift(
            consumerKey:    "GQldQj8WtdMTXmifxpyAQeOjr5v9UX",
            consumerSecret: "hZsfW3D6FPZK9qtV81wNsh9HrFJvE9",
            requestTokenUrl: "\(baseUrl)/oauth/request_token_query",
            authorizeUrl:    "\(baseUrl)/oauth/authorize",
            accessTokenUrl:  "\(baseUrl)/oauth/access_token"
            header: ["Content-Type": "application/x-www-form-urlencoded"]
        );

```

Triggers a compilation error :

Cannot invoke initializer for type 'OAuth1Swift' with an argument list of type '(consumerKey: String, consumerSecret: String, requestTokenUrl: String, authorizeUrl: String, accessTokenUrl: String, header: [String : String])'

**Comment by phimage** [comment]
there is no network call when you initialize the object, you must use authorize
maybe there is nothing for oauth1 because that is not standard
for oauth 2 there is an header parameters https://github.com/OAuthSwift/OAuthSwift/blob/master/Sources/OAuth2Swift.swift#L83

**Comment by csauvage** [comment]
Yeah, of course, I mean doing this don't produce a request body

```
        oAuthConsumer.authorize(
            withCallbackURL: "myCustomURL://",
            success: { (credentials, response, parameters) in
                print("success");
        }) { (error) in
            print(error)
            print(error.localizedDescription)
        }
```

**Comment by csauvage** [comment]
Made #517 to fix the last method with header. It didn’t goes though CI. I guess you haven’t exposed Danger API Key.
