### ISSUE TITLE
What are the step-by-step instructions to use this library with Twitter (authenticate, and grab the json file)

### ISSUE THREAD

**Issue by shyamalschandra** [OAuthSwift/OAuthSwift#518]
What are the step-by-step instructions to use this library with Twitter (authenticate, and grab the json file)

**Comment by phimage** [comment]
jut read the readme

**Comment by shyamalschandra** [comment]
That wasn't the answer I was looking for because the README is incomplete.

For more information, see the following:

https://stackoverflow.com/questions/54991225/what-is-the-most-quickest-oauth-framework-to-use-for-swift-4-2-for-twitter-in-nu

**Comment by phimage** [comment]
This is the answer @shyamalschandra  of your generic question without any code etc...

```
 func doOAuthTwitter(serviceParameters: [String:String]){
        let oauthswift = OAuth1Swift(
```
bad -> oauthswift must be affected to a variable somewhere to be used later
not only just after the connection

as you can see in the demo app

**Comment by shyamalschandra** [comment]
This is not a valid answer.  Could you please give step-by-step instructions?

**Comment by phimage** [comment]
@shyamalschandra stop rate the quality of answer...
your are not on stackoverflow. 

so stop asking here, go to stackoverflow

you are not asking step by step but that someone do your job ;)
