### ISSUE TITLE
Retain Error

### ISSUE THREAD

**Issue by kunusiths** [OAuthSwift/OAuthSwift#519]
switch error {

            case OAuthSwiftError.tokenExpired:
                _ = self.renewAccessToken(withRefreshToken: self.client.credential.oauthRefreshToken, headers: renewHeaders ?? headers, success: { (credential, _, _) in
                    // Ommit response parameters so they don't override the original ones
                    // We have successfully renewed the access token.

                    // If provided, fire the onRenewal closure
                    if let renewalCallBack = onTokenRenewal {
                        renewalCallBack(credential)
                    }

in this function when error is tokenExpired it goes into renewAccessToken function but self.client.credential.oauthRefreshToken = "".Please Help

**Comment by phimage** [comment]
if you can debug the connection this can help

a breakpoint here 
https://github.com/OAuthSwift/OAuthSwift/blob/1ba85d0837fa052ea556acd925a7c4ae8beec42a/Sources/OAuth2Swift.swift#L227
```swift
if let refreshToken = responseParameters["refresh_token"] as? String {
                this.client.credential.oauthRefreshToken = refreshToken.safeStringByRemovingPercentEncoding
            }
````
to see if there is in `responseParameters` the "refresh_token" or not, or maybe named


You remove all issue template with many questions I ask, next time I close the issue without helping
Because I need to know the oauth provider for instance

**Comment by kunusiths** [comment]
fileprivate func requestOAuthAccessToken(withParameters parameters: OAuthSwift.Parameters, headers: OAuthSwift.Headers? = nil, success: @escaping TokenSuccessHandler, failure: FailureHandler?) -> OAuthSwiftRequestHandle? {
        let successHandler: OAuthSwiftHTTPRequest.SuccessHandler = { [weak self] response in
            guard let this = self else {
                OAuthSwift.retainError(failure)
                return
            }

here self is nil every time it goes into else only i added refresh token.please help

**Comment by kunusiths** [comment]
> if you can debug the connection this can help
> 
> a breakpoint here
> [OAuthSwift/Sources/OAuth2Swift.swift](https://github.com/OAuthSwift/OAuthSwift/blob/1ba85d0837fa052ea556acd925a7c4ae8beec42a/Sources/OAuth2Swift.swift#L227)
> 
> Line 227 in [1ba85d0](/OAuthSwift/OAuthSwift/commit/1ba85d0837fa052ea556acd925a7c4ae8beec42a)
> 
>  if let refreshToken = responseParameters["refresh_token"] as? String { 
> ```swift
> if let refreshToken = responseParameters["refresh_token"] as? String {
>                 this.client.credential.oauthRefreshToken = refreshToken.safeStringByRemovingPercentEncoding
>             }
> ```
> 
> to see if there is in `responseParameters` the "refresh_token" or not, or maybe named
> 
> You remove all issue template with many questions I ask, next time I close the issue without helping
> Because I need to know the oauth provider for instance

i kept a break point here its not executing this part of code

**Comment by kunusiths** [comment]
not executing the line 227 because of this retainerror self is nil.please help.\

fileprivate func requestOAuthAccessToken(withParameters parameters: OAuthSwift.Parameters, headers: OAuthSwift.Headers? = nil, success: @escaping TokenSuccessHandler, failure: FailureHandler?) -> OAuthSwiftRequestHandle? {
    let successHandler: OAuthSwiftHTTPRequest.SuccessHandler = { [weak self] response in
        guard let this = self else {
            OAuthSwift.retainError(failure)
            return
        }

**Comment by kunusiths** [comment]
please explain how can i retain and close this issue

**Comment by phimage** [comment]
you call `authorize` to login
then the url handler (browser etc.. open an url and you log)

the callback is called after that
https://github.com/OAuthSwift/OAuthSwift/blob/1ba85d0837fa052ea556acd925a7c4ae8beec42a/Sources/OAuth2Swift.swift#L89

did you receive access token directly?
https://github.com/OAuthSwift/OAuthSwift/blob/1ba85d0837fa052ea556acd925a7c4ae8beec42a/Sources/OAuth2Swift.swift#L101
I think some is missing here

if not post function is called
https://github.com/OAuthSwift/OAuthSwift/blob/1ba85d0837fa052ea556acd925a7c4ae8beec42a/Sources/OAuth2Swift.swift#L123
which call the method I ask to add debug point
https://github.com/OAuthSwift/OAuthSwift/blob/1ba85d0837fa052ea556acd925a7c4ae8beec42a/Sources/OAuth2Swift.swift#L205

**Comment by phimage** [comment]
yo retain do not do
var oauthswift = ... or let oauthswift = ...

but create a var oauthswift: OAuthSwift?  in your controller

and do 
self.oauthswift = OAuth....

**Comment by kunusiths** [comment]
sir, i dont want to login with browser
 
so i didnt use authorize method

Instead i used startAuthorizedRequest and passed token url parameters

so in this case oauthRefreshToken is not getting assigned in your library

**Comment by kunusiths** [comment]
i got refresh token now but not able to solve this retain error

fileprivate func requestOAuthAccessToken(withParameters parameters: OAuthSwift.Parameters, headers: OAuthSwift.Headers? = nil, success: @escaping TokenSuccessHandler, failure: FailureHandler?) -> OAuthSwiftRequestHandle? {
let successHandler: OAuthSwiftHTTPRequest.SuccessHandler = { [weak self] response in
guard let this = self else {
OAuthSwift.retainError(failure)
return
}

every time this self is becoming nil.please help with this

**Comment by kunusiths** [comment]
> yo retain do not do
> var oauthswift = ... or let oauthswift = ...
> 
> but create a var oauthswift: OAuthSwift? in your controller
> 
> and do
> self.oauthswift = OAuth....

tried this do you want me to add weak or anything while declaring?

**Comment by kunusiths** [comment]
i think problem is

**Comment by phimage** [comment]
yes you can keep in your manager class, it is better!
if your cloud manager is not released in memory (there is an instance somewhere, singleton or controller or app delelegate or anywhere)

**Comment by kunusiths** [comment]
i kept in cloud manager class retain error is still coming please help.should i share screen

**Comment by phimage** [comment]
little tip: avoid using `!` (see force_cast in swiftlint)

I cannot help without the code and do want to do share screen

your cloud manager is retained by what?
where did you create it and where did you affect it
did you make for instance a singleton and use CloudManager.instance.auth() like that

```swift
class CloudManager {
 static let instance = CloudManager()

 func auth() {
  self.oauthswift = OAth()...

  oauth.authorize()
}

}
```

**Comment by kunusiths** [comment]
> little tip: avoid using `!` (see force_cast in swiftlint)
> 
> I cannot help without the code and do want to do share screen
> 
> your cloud manager is retained by what?
> where did you create it and where did you affect it
> did you make for instance a singleton and use CloudManager.instance.auth() like that
> 
> ```swift
> class CloudManager {
>  static let instance = CloudManager()
> 
>  func auth() {
>   self.oauthswift = OAth()...
> 
>   oauth.authorize()
> }
> 
> }
> ```

**Comment by kunusiths** [comment]
![screen shot 2019-03-05 at 10 14 41 pm](https://user-images.githubusercontent.com/46209817/53821764-6b55b700-3f94-11e9-9512-a3ea7d2b7966.png)
![screen shot 2019-03-05 at 10 15 07 pm](https://user-images.githubusercontent.com/46209817/53821777-70b30180-3f94-11e9-9c85-4364d4a37385.png)
see these two screeen shots self is becoming nil

**Comment by kunusiths** [comment]
> > little tip: avoid using `!` (see force_cast in swiftlint)
> > I cannot help without the code and do want to do share screen
> > your cloud manager is retained by what?
> > where did you create it and where did you affect it
> > did you make for instance a singleton and use CloudManager.instance.auth() like that
> > ```swift
> > class CloudManager {
> >  static let instance = CloudManager()
> > 
> >  func auth() {
> >   self.oauthswift = OAth()...
> > 
> >   oauth.authorize()
> > }
> > 
> > }
> > ```

without ! getting error

**Comment by kunusiths** [comment]
My Cloud MAnager class is like this

import OAuthSwift
import ObjectMapper

class CloudManager {
    
    let errorResponse:DataResponse<Any>? = nil
    let stringErrorResponse: DataResponse<String>? = nil
    
    var accessToken: String?
    var oauthswift: OAuth2Swift?
    func makeCloudRequest(url:String,parameter:[String:Any],headers:[String:String],requestType:HTTPMethod ,completionHandler: @escaping (DataResponse<Any>?) -> Void ){
        var method:OAuthSwiftHTTPRequest.Method?
        var parameters:[String:Any] = parameter
        if requestType == .post{
            method = .POST
        }else if requestType == .get{
            method = .GET
            parameters = [:]
        }else if requestType == .put{
            method = .PUT
        }
        self.oauthswift = OAuth2Swift(
            consumerKey: StringConstant.oauth_client_id,         // [1] Enter google app settings
            consumerSecret: KeychainService.shared[KEY_GOOGLE.KEY_NAME_OAUTH_CLIENT_SECRET]!,        // No secret required
            authorizeUrl: RequestURL.URL_OAUTH_ACCESS_TOKEN.rawValue,
            accessTokenUrl: RequestURL.URL_OAUTH_ACCESS_TOKEN.rawValue,
            responseType: StringConstant.token
        )
        if NetworkCheck.isNetwork() {
            let queue = DispatchQueue(label: "com.test.api", qos: .background, attributes: .concurrent)
            queue.async {
                self.oauthswift!.client.credential.oauthRefreshToken = MyDefaults.getData(key: DefaultKeys.KEY_REFRESH_TOKEN) as! String
                self.oauthswift!.startAuthorizedRequest(url, method: method!, parameters: parameters,headers:headers,onTokenRenewal: { (credential) in
                        print(credential)
                        MyDefaults.setData(value: credential.oauthToken, key: DefaultKeys.KEY_TOKEN)
                        MyDefaults.setData(value:credential.oauthRefreshToken,key:DefaultKeys.KEY_REFRESH_TOKEN)
                    }, success: { (response) in
                        try? completionHandler(DataResponse(request: response.request, response: response.response, data: response.data, result: .success(try response.jsonObject())))
                        if url == RequestURL.URL_OAUTH_ACCESS_TOKEN.rawValue{
//                            if let responseParameters = try? response.jsonObject() as! [String:Any]{
//                                if let expiresIn = responseParameters["expires_in"] as? String, let offset = Double(expiresIn) {
//                                    self.oauthswift.client.credential.oauthTokenExpiresAt = Date(timeInterval: offset, since: Date())
//                                } else if let expiresIn = responseParameters["expires_in"] as? Double {
//                                    self.oauthswift.client.credential.oauthTokenExpiresAt = Date(timeInterval: expiresIn, since: Date())
//                                }
//                            }
                            
                            
                            
                            self.oauthswift!.renewAccessToken(withRefreshToken: MyDefaults.getData(key: DefaultKeys.KEY_REFRESH_TOKEN) as! String,
                                success: { (OAuthSwiftCredential, OAuthSwiftResponse, OAuthSwiftParameters) in
                                MyDefaults.setData(value: OAuthSwiftCredential.oauthToken, key: DefaultKeys.KEY_TOKEN)
                            },
                                failure: { (OAuthSwiftError) in

                            })
                        }
                    }, failure: { (OAuthSwiftError) in
                        do{
                            let error = (OAuthSwiftError.errorUserInfo["error"] as! NSError).userInfo as! [String:Any]
                            if let data = error[StringConstant.responseDataKey]{
                                let response = try JSONSerialization.jsonObject(with: data  as! Data, options: [])
                                completionHandler(DataResponse(request: OAuthSwiftError.errorUserInfo[StringConstant.request] as? URLRequest, response: error[StringConstant.responseKey] as? HTTPURLResponse, data: data as? Data, result: .success(response)))
                            }else{
                                completionHandler(self.errorResponse)
                            }
                        } catch let error as NSError {
                            print(error)
                        }
                    })
            }
        }else{
            
            if let view = Constants.appDelegate?.window?.rootView(){
                ToastPopUp.showNetworkPOPup(message:ToastMsgConstant.network ,view: view)
            }
            completionHandler(errorResponse)
        }
    }

**Comment by kunusiths** [comment]
Please help

**Comment by kunusiths** [comment]
please help

**Comment by kunusiths** [comment]
> ![screen shot 2019-03-05 at 10 14 41 pm](https://user-images.githubusercontent.com/46209817/53821764-6b55b700-3f94-11e9-9512-a3ea7d2b7966.png)
> ![screen shot 2019-03-05 at 10 15 07 pm](https://user-images.githubusercontent.com/46209817/53821777-70b30180-3f94-11e9-9c85-4364d4a37385.png)
> see these two screeen shots self is becoming nil

i am getting request response also but self is becoming nil

**Comment by kunusiths** [comment]
No I didn't use instance of cloud manager like what I told but when I make request I am calling like Cloud manager().makeRequest()

On 05-Mar-2019 10:15 PM, Eric Marchand <notifications@github.com> wrote:

little tip: avoid using ! (see force_cast in swiftlint)

I cannot help without the code and do want to do share screen

your cloud manager is retained by what?
where did you create it and where did you affect it
did you make for instance a singleton and use CloudManager.instance.auth() like that

class CloudManager {
 static let instance = CloudManager()

 func auth() {
  self.oauthswift = OAth()...

  oauth.authorize()
}

}

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOAuthSwift%2FOAuthSwift%2Fissues%2F519%23issuecomment-469755860&data=02%7C01%7CKunusoth.Sandeep%40kpit.com%7C0cb49dab636f4845f58d08d6a18a013a%7C3539451eb46e4a26a242ff61502855c7%7C0%7C1%7C636874011434967296&sdata=TXSA6iF4U2elvKXEMVOfUV17c5YYOvBPcmEmztJtwaE%3D&reserved=0>, or mute the thread<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAsEbGYBA6Xngz48G9fxUt-FYAnw1vOveks5vTp8zgaJpZM4be289&data=02%7C01%7CKunusoth.Sandeep%40kpit.com%7C0cb49dab636f4845f58d08d6a18a013a%7C3539451eb46e4a26a242ff61502855c7%7C0%7C1%7C636874011434977303&sdata=cvsqT1w%2FqeIDL4olJ%2BVsxNdp2loRHNzED%2B9QKfqqtJI%3D&reserved=0>.

This message contains information that may be privileged or confidential and is the property of the KPIT Technologies Ltd. It is intended only for the person to whom it is addressed. If you are not the intended recipient, you are not authorized to read, print, retain copy, disseminate, distribute, or use this message or any part thereof. If you receive this message in error, please notify the sender immediately and delete all copies of this message. KPIT Technologies Ltd. does not accept any liability for virus infected mails.

**Comment by kunusiths** [comment]
Please help

On 06-Mar-2019 12:33 AM, Kunusoth.Sandeep@kpit.com wrote:
No I didn't use instance of cloud manager like what I told but when I make request I am calling like Cloud manager().makeRequest()

On 05-Mar-2019 10:15 PM, Eric Marchand <notifications@github.com> wrote:

little tip: avoid using ! (see force_cast in swiftlint)

I cannot help without the code and do want to do share screen

your cloud manager is retained by what?
where did you create it and where did you affect it
did you make for instance a singleton and use CloudManager.instance.auth() like that

class CloudManager {
 static let instance = CloudManager()

 func auth() {
  self.oauthswift = OAth()...

  oauth.authorize()
}

}

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOAuthSwift%2FOAuthSwift%2Fissues%2F519%23issuecomment-469755860&data=02%7C01%7CKunusoth.Sandeep%40kpit.com%7C0cb49dab636f4845f58d08d6a18a013a%7C3539451eb46e4a26a242ff61502855c7%7C0%7C1%7C636874011434967296&sdata=TXSA6iF4U2elvKXEMVOfUV17c5YYOvBPcmEmztJtwaE%3D&reserved=0>, or mute the thread<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAsEbGYBA6Xngz48G9fxUt-FYAnw1vOveks5vTp8zgaJpZM4be289&data=02%7C01%7CKunusoth.Sandeep%40kpit.com%7C0cb49dab636f4845f58d08d6a18a013a%7C3539451eb46e4a26a242ff61502855c7%7C0%7C1%7C636874011434977303&sdata=cvsqT1w%2FqeIDL4olJ%2BVsxNdp2loRHNzED%2B9QKfqqtJI%3D&reserved=0>.


This message contains information that may be privileged or confidential and is the property of the KPIT Technologies Ltd. It is intended only for the person to whom it is addressed. If you are not the intended recipient, you are not authorized to read, print, retain copy, disseminate, distribute, or use this message or any part thereof. If you receive this message in error, please notify the sender immediately and delete all copies of this message. KPIT Technologies Ltd. does not accept any liability for virus infected mails.

**Comment by phimage** [comment]
> No I didn't use instance of cloud manager like what I told but when I make request I am calling like Cloud manager().makeRequest()

so you do not retain any information, do not create the classe and lose it

please learn iOS memory management or do like I say with a singleton (event if it is not a good architecture)
