### ISSUE TITLE
accesstoken in headers is not getting updated when token is renewed

### ISSUE THREAD

**Issue by kunusiths** [OAuthSwift/OAuthSwift#520]
open func startAuthorizedRequest(_ url: String, method: OAuthSwiftHTTPRequest.Method, parameters: OAuthSwift.Parameters, headers: OAuthSwift.Headers? = nil...) {
             return self.client.request(url, method: method, parameters: parameters, headers: headers, body: body, success: success) { (error) in
            switch error {

            case OAuthSwiftError.tokenExpired:
                _ = self.renewAccessToken(withRefreshToken: self.client.credential.oauthRefreshToken, headers: renewHeaders ?? headers, success: { (credential, _, _) in
                    // Ommit response parameters so they don't override the original ones
                    // We have successfully renewed the access token.

                    // If provided, fire the onRenewal closure
                    if let renewalCallBack = onTokenRenewal {
                        renewalCallBack(credential)
                    }
                 
                    // Reauthorize the request again, this time with a brand new access token ready to be used.
                    _ = self.startAuthorizedRequest(url, method: method, parameters: parameters, headers: headers, body: body, onTokenRenewal: onTokenRenewal, success: success, failure: failure)
                },
                                          failure: failure)
}

here after token renewing previous token is used in headers(i mean same headers of first request are getting passed in 2nd request) in -=self.startAuthorized() request

first request after token renewal is failing every time and getting 
OAuthSwiftResponse:{
    error = "invalid_request";
    "error_description" = "Missing form parameter: grant_type";
}

This problem i am getting only when token expiration is handled by library when i am checking token expiration and sending request no error like this is coming.Please help.

**Comment by kunusiths** [comment]
i think this is because in OAuthSwiftHTTPRequest.swift
public mutating func updateRequest(credential: OAuthSwiftCredential) 
line 406  self.urlRequest.allHTTPHeaderFields = requestHeaders + headers
requestHeaders contains Authorization:Bearer already and in headers also Authorization Bearer is present in library both are getting added .Please Help

**Comment by kunusiths** [comment]
Please help I am stuck only in this except this everything is working

**Comment by kunusiths** [comment]
hello sir,

i got this solved by adding this 
 if requestHeaders.count > 0{
                headers.removeValue(forKey: "Authorization")
            }
            self.urlRequest.allHTTPHeaderFields = requestHeaders + headers

in public mutating func updateRequest(credential: OAuthSwiftCredential) {
}

**Comment by phimage** [comment]
Please do not add new message asking just for help. Do u know that people sleep and work :p

So you want authorization from requestHeaders, not headers with priority now
The question is why there is redundant header. I need to read the code later

**Comment by kunusiths** [comment]
hi i want to know whether this function will be called for making all headers or only when token is refreshed 

/// Allow to customize computed headers
public protocol OAuthSwiftCredentialHeadersFactory {
    func make(_ url: URL, method: OAuthSwiftHTTPRequest.Method, parameters: OAuthSwift.Parameters, body: Data?) -> [String: String]
}
