### ISSUE TITLE
Properly logging out

### ISSUE THREAD

**Issue by nodediggity** [OAuthSwift/OAuthSwift#521]
### Description:
Forgive me if I'm missing something obvious, once I have an authenticated session, how can I instruct `OAuthSwift`  that I would like to log out a user out?

I was expecting to find a method somewhere that is almost the opposite of `authorize` so I may revoke tokens / clear state and redirect the user as appropriate.

### OAuth Provider? (Twitter, Github, ..):
Custom - [Microsoft Identity Server](http://docs.identityserver.io/en/latest/)

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [x] head
- [ ] v1.2.1
- [ ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ ] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [x] other: 10.1 (Swift 4.2)

- [ ] objective c

**Comment by nodediggity** [comment]
Please close this issue, I have found exactly what I needed, thank you.

**Comment by phimage** [comment]
There is no standard I think for that , depend on the provider.
See Wiki page about it
