### ISSUE TITLE
authorizeURLHandler is not weak, prevents view controller from being deallocated

### ISSUE THREAD

**Issue by miktav** [OAuthSwift/OAuthSwift#522]
Once I set OAuth2Swift authorizeURLHandler to my view controller, my view controller is never getting deallocated.

I believe this is happening because authorizeURLHandler is not declared as weak:

open var authorizeURLHandler: OAuthSwiftURLHandlerType

My view controller's deinit is never called.

**Comment by phimage** [comment]
possible workaround
oauthswift object as week in controller
or restore default authorizeURLHandler

**Comment by phimage** [comment]
I will propose a new solution in next version with explicit code to make weak
Because make weak for everybody could create some bugs like #526

**Comment by phimage** [comment]
The solution to make weak by code
```swift
oauthswift.authorizeURLHandler = YourVariable.weak()
```
This will a proxy with weak reference
