### ISSUE TITLE
Please make tag for 1.4 version

### ISSUE THREAD

**Issue by vg-identance** [OAuthSwift/OAuthSwift#525]
Please make tag for 1.4 version and push to cocoapods please. I see commit https://github.com/OAuthSwift/OAuthSwift/commit/c86b94c1df595d6529f50aaf4e0ff4422f4d68b7 where version updated in podspec file but without tag. Also .swift-version should be updated to 5 version.

**Comment by phimage** [comment]
I make a tag 1.4
but I have issue to publish on Cocoapods

```
$ pod trunk push 

[!] Found podspec `OAuthSwift.podspec`
Updating spec repo `master`
Validating podspec
 -> OAuthSwift (1.4.0)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Planning build
    - NOTE  | xcodebuild:  note: Constructing build description
    - NOTE  | xcodebuild:  warning: Capabilities for App may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the build settings editor. (in target 'App')

[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.
```
same on website https://cocoapods.org/pods/OAuthSwift

I do not know where to ask support

---

However you can in your podfile set the git url and tag

**Comment by vg-identance** [comment]
Did you try to install latest cocoapods? They are released the new version recently.

**Comment by vg-identance** [comment]
...also try to run it with `--verbose`. If nothing help try to write them directly in https://github.com/CocoaPods/CocoaPods/issues/8200

**Comment by phimage** [comment]
I use the last version, no more information with verbose
```
reading 141 bytes...
-> "{\"error\":\"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.\"}"
read 141 bytes
Conn keep-alive
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.
```

---

I am working also on a breaking change version 2.0 with `Result`

**Comment by phimage** [comment]
I make a new version 1.4.1
It seems to be ok
