### ISSUE TITLE
Safari View Controller Failed to dismiss automatically

### ISSUE THREAD

**Issue by emiltsang** [OAuthSwift/OAuthSwift#526]
### Description:
After updated to OAuthSwift version 1.4.0 from 1.2.2, the Safari View Controller failed to dismiss automatically after successful login to Meetup.com.

Is there any methods to make the Safari View Controller dismiss automatically?

### OAuth Provider? (Twitter, Github, ..):
Meetup.com

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS : 11.2

### Installation method:
- [x] CocoaPods

### Library version:
- [x] v1.4.0

### Xcode version:
- [x] 10.2.1 (Swift 5.0)

**Comment by phimage** [comment]
Maybe its because of my fix #522
Could you try by keeping a hard reference on your object set to  `authorizeURLHandler` variable

**Comment by phimage** [comment]
I will make a new release 1.4.1 to revert the change
and propose a new solution when needed to create a weak instead

**Comment by phimage** [comment]
1.4.1 created
I expect you have no more issue
