### ISSUE TITLE
Build Error under Swift Package Manager in Xcode 11 Beta

### ISSUE THREAD

**Issue by paulhimes** [OAuthSwift/OAuthSwift#528]
### Description:

When the library is imported into an Xcode 11 Beta project using the new built-in swift package manager, it fails to compile with the following errors in OAuthSiftHTTPRequest.swift:

.../SourcePackages/checkouts/OAuthSwift/Sources/OAuthSwiftHTTPRequest.swift:99:21: Use of unresolved identifier 'UIApplication'

.../SourcePackages/checkouts/OAuthSwift/Sources/OAuthSwiftHTTPRequest.swift:109:9: Use of unresolved identifier 'UIApplication'

The relevant code snippet: 

```
            #if os(iOS)
                #if !OAUTH_APP_EXTENSIONS
                    UIApplication.shared.isNetworkActivityIndicatorVisible = self.config.sessionFactory.isNetworkActivityIndicatorVisible
                #endif
            #endif
        }
    }

    /// Function called when receiving data from server.
    public static func completionHandler(completionHandler completion: CompletionHandler?, request: URLRequest, data: Data?, resp: URLResponse?, error: Error?) {
        #if os(iOS)
        #if !OAUTH_APP_EXTENSIONS
        UIApplication.shared.isNetworkActivityIndicatorVisible = false
        #endif
        #endif
```

### OAuth Version:
- [ ] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [ ] Manually
- [x] Swift Package Manager (Xcode 11 Beta)

### Library version:
- [x] head
- [ ] v1.2.1
- [ ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 11.0 (Swift 5.0)
- [ ] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
Just to check, on Mojave or Catalina beta?
I have. It tested yet

Then this error exist when OauthSwift is used has app extension without the compilation flag set

**Comment by paulhimes** [comment]
This was on Mojave. The app has no extensions.

**Comment by phimage** [comment]
I add a missing import of `UIKit`
compilator is more strict I think

There is also some issue on macOS in `OAuthWebViewController`
It seems to have some issue to check swift version to make version compatible code
```swift
#if swift(>=5.1)
p.presentViewControllerAsSheet(self) // renamed 
#else
p.presentAsSheet(self)
#endif
```

**Comment by paulhimes** [comment]
Your changes fixed the problem for me. Thanks!

**Comment by objectivechris** [comment]
This issue is still persisting on Xcode 11 beta 6

> ### Description:
> When the library is imported into an Xcode 11 Beta project using the new built-in swift package manager, it fails to compile with the following errors in OAuthSiftHTTPRequest.swift:
> 
> .../SourcePackages/checkouts/OAuthSwift/Sources/OAuthSwiftHTTPRequest.swift:99:21: Use of unresolved identifier 'UIApplication'
> 
> .../SourcePackages/checkouts/OAuthSwift/Sources/OAuthSwiftHTTPRequest.swift:109:9: Use of unresolved identifier 'UIApplication'
> 
> The relevant code snippet:
> 
> ```
>             #if os(iOS)
>                 #if !OAUTH_APP_EXTENSIONS
>                     UIApplication.shared.isNetworkActivityIndicatorVisible = self.config.sessionFactory.isNetworkActivityIndicatorVisible
>                 #endif
>             #endif
>         }
>     }
> 
>     /// Function called when receiving data from server.
>     public static func completionHandler(completionHandler completion: CompletionHandler?, request: URLRequest, data: Data?, resp: URLResponse?, error: Error?) {
>         #if os(iOS)
>         #if !OAUTH_APP_EXTENSIONS
>         UIApplication.shared.isNetworkActivityIndicatorVisible = false
>         #endif
>         #endif
> ```
> 
> ### OAuth Provider? (Twitter, Github, ..):
> ### OAuth Version:
> * [ ]  Version 1
> * [ ]  Version 2
> 
> ### OS (Please fill the version) :
> * [x]  iOS :
> * [ ]  OSX :
> * [ ]  TVOS :
> * [ ]  WatchOS  :
> 
> ### Installation method:
> * [ ]  Carthage
> * [ ]  CocoaPods
> * [ ]  Manually
> * [x]  Swift Package Manager (Xcode 11 Beta)
> 
> ### Library version:
> * [x]  head
> * [ ]  v1.2.1
> * [ ]  v1.2 (Swift 4.0)
> * [ ]  v1.0.0
> * [ ]  v0.6
> * [ ]  other: (Please fill in the version you are using.)
> 
> ### Xcode version:
> * [x]  11.0 (Swift 5.0)
> * [ ]  9.3 (Swift 4.1)
> * [ ]  9.0 (Swift 4.0)
> * [ ]  9.0 (Swift 3.2)
> * [ ]  8.x (Swift 3.x)
> * [ ]  8.0 (Swift 2.3)
> * [ ]  7.3.1
> * [ ]  other: (Please fill in the version you are using.)
> * [ ]  objective c

This is issue is still happening on Xcode 11 beta 6
