### ISSUE TITLE
Sonos API

### ISSUE THREAD

**Issue by paulboyce10** [OAuthSwift/OAuthSwift#529]
Can OAuthSwift be used with Sonos API. I have installed it as per the instructions but cannot get the token back. My app is wrote in Swift 5.

Any help is appreciated.

**Comment by phimage** [comment]
For this kind of question without any code or error message, please go to stackoverflow.
Then you do not provide any link to sonos api, which talk about oauth...
You can upload project to your github or clone this repository, add sonos in demo app , then I can see if there is an issue

**Comment by paulboyce10** [comment]
Thanks phimage, I'll add to stackoverflow. Here is the link to Sonos Developer site anyway. https://developer.sonos.com/reference/authorization-api/ 

I'm probably missing something simple. If I get it working I'll report back. Thanks
