### ISSUE TITLE
Build error when the `OAUTH_APP_EXTENSIONS` flag is enabled

### ISSUE THREAD

**Issue by shadyoak** [OAuthSwift/OAuthSwift#530]
### Description:
I am unable to integrate v2.0.0 into my iOS app extension. The project will not compile for me with the `OAUTH_APP_EXTENSIONS` flag enabled. The problem is the`UIApplication.shared` calls that were introduced as part of PR #516. Previously, I was using v1.3.0 which worked fine.

### OAuth Version:
- [x] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually

### Library version:
- [ ] head
- [x] v2.0.0
- [ ] v1.4.1
- [ ] v1.2.1
- [ ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ ] 11.x (Swift 5.1)
- [x] 10.x (Swift 5.0)
- [ ] 10.x (Swift 4.1)
- [ ] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
thanks for looking in code history ;)
pr merged
