### ISSUE TITLE
Please add log for request/response like p2/oauth2 library

### ISSUE THREAD

**Issue by iam-manikandan** [OAuthSwift/OAuthSwift#534]
**Feature request**

1 ) Is this library have any logging solution like p2/oauth2 library?
2) Please make client secret as optional in oauth2swift class because some of oauth2 provider doesn't need client secret in the request.

Please concentrate on logging the request/response details, that will be really good. Thanks

**Comment by phimage** [comment]
1/ I will not study another library, please describe the eventual missing feature 
2/ There is a github template for issue. This is important to not loose time. Here I need to ask a question that is already asked.. the oauth provider?

**Comment by iam-manikandan** [comment]
1) I have been working on integrating the cloud storages (drive,box,dropbox) in my app, for that I have went through libraries that handle all accounts authentication and authorization and I have found yours and p2/oauth2. Initially I have chosen yours for my app but really tedious to find what's happening in the request/response flow and debug the errors. p2/oauth2 has logging property, so we can enable/disable the logging.

2) Google drive doesn't need client secret for authorize and getting access token, thats what i asked to make that client secret parameter as optional.

Sorry for mentioning other libraries here, I have just saying what I felt.

**Comment by slizeray** [comment]
you can use an empty string for the client secret...I agree nil would be better though....But an empty string works fine.

**Comment by iam-manikandan** [comment]
Yes I tried empty string,but I had some issue. Will try again and let you know. Thanks

**Comment by slizeray** [comment]
FYI, I integrate with Google Drive using OAuthSwift....

**Comment by svoip** [comment]
I agree with the thread author on having a logging solution for this library would be great. 
For example, under a logging flag, the library adds more print statements, in all or most of the flows (be it a presentation/dismiss of Safari, or network request or encoding, etc).
Can I participate in adding such a feature?

**Comment by phimage** [comment]
@svoip yes you can PR

instead of printing directly, better implementation will be to have a protocol to log, replacable with debug, error, warning log level

**Comment by svoip** [comment]
@phimage I have created pull request
https://github.com/OAuthSwift/OAuthSwift/pull/586
Could you review it please?
