### ISSUE TITLE
cannot detect dismiss when using SafariURLHandler 

### ISSUE THREAD

**Issue by garyhooper** [OAuthSwift/OAuthSwift#537]
### Description:

I am using SafariURLHandler as my handler. The handler's presentCompletion() is correctly detected and invoked when the Safari page is displayed.

However, if the user presses Done without entering credentials, dismissCompletion() is not being called. How can I detect that Done was pressed?

### OAuth Provider? (Twitter, Github, ..):
- TripIt

### OAuth Version:
- [X] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [X] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually

### Library version:
- [ ] head
- [ ] v2.0.0
- [ ] v1.4.1
- [ ] v1.2.1
- [X] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ ] 11.x (Swift 5.1)
- [X] 10.x (Swift 5.0)
- [ ] 10.x (Swift 4.1)
- [ ] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
in `SafariURLHandler` you can add a delegate of type `SFSafariViewControllerDelegate `
https://github.com/OAuthSwift/OAuthSwift/blob/ec656d9ab13193702ef4ca79c1f9a42fc2be7316/Sources/OAuthSwiftURLHandlerType.swift#L126

**Comment by garyhooper** [comment]
Thank you!
