### ISSUE TITLE
Is there any way to get progress data during a multipart post?

### ISSUE THREAD

**Issue by MickeDG** [OAuthSwift/OAuthSwift#541]
### Description:
I'm successfully doing a multipart post of a video and would like to show a progress bar to the user...

### OAuth Version:
- [x] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually

### Library version:
- [ ] head
- [x] v2.0.0
- [ ] v1.4.1
- [ ] v1.2.1
- [ ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ ] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [x] 10.x (Swift 4.1)
- [ ] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
here https://github.com/OAuthSwift/OAuthSwift/blob/a471698f0b200a9ffe5572662a7b7a411f2511fc/Sources/OAuthSwiftClient.swift#L22
there is an `URLSessionFactory`

inside you could put a delegate to associate with the URLSession
for instance one with 
https://developer.apple.com/documentation/foundation/urlsessiontaskdelegate/1408299-urlsession

**Comment by MickeDG** [comment]
Thanks - I understand the main idea but not exactly how to implement it. Do I insert a function like this one:

urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)

in the the URLSessionFactory struct?

How do I then call it my code?

**Comment by phimage** [comment]
You make your own class or struct, which implement the delegate
then do `client.sessionFactory.delegate = <yourclassorstruct>`

and I think you will receive some events in your method. I have not tested it but if I put correctly the delegate in apple sessions and I do not put my own delegate ...

**Comment by MickeDG** [comment]
Thank you - I got it working! 

In URLSessionFactory

`public weak var taskDelegate: URLSessionTaskDelegate?`    
...
`public var useDataTaskClosure = false`

In my class:

```
override init() {
        super.init()
        appDelegate.oauthSwift.client.sessionFactory.taskDelegate = self
    }

```
```
func urlSession(_ session: URLSession, task: URLSessionTask, didSendBodyData bytesSent: Int64, totalBytesSent: Int64, totalBytesExpectedToSend: Int64) {
        let uploadProgress:Float = Float(totalBytesSent) / Float(totalBytesExpectedToSend)
        print(uploadProgress)
    }
```
