### ISSUE TITLE
in IOS 11 Restore session between the WKWebview and SFSafariViewController.

### ISSUE THREAD

**Issue by sharmam-lh** [OAuthSwift/OAuthSwift#544]
### Description:

How to restore session between the WKWebview and SFSafariViewController in iOS 11, As I am trying to restore existing cookies for already logged-In user. which I am not able to do in iOS 11.
the earlier version in iOS 9 and iOS 10, I am able to share the cookies between them. but in case of iOS 11, there are new changes from Apple side due to security problem.

Here I found apple developer documents regarding SFSafariViewController:- https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller
Looking for suggestions.

Thanks in advance.

**Comment by tguidon** [comment]
@sharmam-lh did you ever figure out how to implement this? My guess would be to use WKWebView? I need to implement something very similar soon.
