### ISSUE TITLE
UIWebView (Deprecated API Usage)

### ISSUE THREAD

**Issue by samwarfield** [OAuthSwift/OAuthSwift#547]
### Description:
Anyone getting this issue? 

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information. 

### OAuth Provider? (Twitter, Github, ..):
Any

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [x] Carthage
- [ ] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually

### Library version:
- [ ] head
- [x] v2.0.0
- [ ] v1.4.1
- [ ] v1.2.1
- [ ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ ] 11.x (Swift 5.1)
- [x] 10.x (Swift 5.0)
- [ ] 10.x (Swift 4.1)
- [ ] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
so apple check only the word UIWebView or any link to it, not the usage
I could remove it I think or maybe keep it with a compilation flag (If someone want to play with it)

**Comment by samwarfield** [comment]
I might have gotten confused. When I search the repo for UIWebView (`https://github.com/OAuthSwift/OAuthSwift/search?q=UIWebView&unscoped_q=UIWebView`)

I seen WKWebView commented out and UIWebView in there...

I took out OAuthSwift from my project and found another framework still using it. Might have been confused the whole time...

**Comment by phimage** [comment]
maybe I will force to use WKWebView then
