### ISSUE TITLE
Add New Release Tag

### ISSUE THREAD

**Issue by codecaffeine** [OAuthSwift/OAuthSwift#552]
### Description:
The latest release tag `2.0.0` has a compilation error when I try to build with Swift Package Manager. This issue ( #531 ) has been fixed, but it’s been _after_ the last tagged release (`2.0.0`) has gone out. I was wondering if it’s possible to release a new tag `2.0.1` with this fix.

### OAuth Provider? (Twitter, Github, ..):
n/a

### OAuth Version:
- [ ] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [x] Swift Package Manager
- [ ] Manually

### Library version:
- [ ] head
- [x] v2.0.0
- [x] v1.4.1
- [ ] v1.2.1
- [ ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [ ] 10.x (Swift 4.1)
- [ ] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
done

new release 2.1.0 if test pass will be also released

**Comment by codecaffeine** [comment]
Thank you, I appreciate it!
