### ISSUE TITLE
Need method to generate random code verifier and code challenge

### ISSUE THREAD

**Issue by dingtianran** [OAuthSwift/OAuthSwift#556]
Need some helper methods to generate random code verifier and code challenge. In order to adapt pace protocol, currently I'm using two class methods from https://github.com/openid/AppAuth-iOS to generate them. I think it'll be very handy to have them in `OAuthSwift` as well.

like:
`+ (nullable NSString *)generateCodeVerifier;`
`+ (nullable NSString *)codeChallengeS256ForVerifier:(nullable NSString *)codeVerifier;`

**Comment by phimage** [comment]
you use it to connect to?
there is an openID layer upon oauth2?

**Comment by phimage** [comment]
I see that seconde function depend on sha256 https://github.com/OAuthSwift/OAuthSwift/issues/540

 https://tools.ietf.org/html/rfc7636#section-4.2
code_challenge = BASE64URL-ENCODE(SHA256(ASCII(code_verifier)))

**Comment by MrWoWander** [comment]
I wrote and sent to the PR #647 generator random code verifier and code challenge
