### ISSUE TITLE
Swift 4.2 support on iOS 9.3.5

### ISSUE THREAD

**Issue by navinbanerjee** [OAuthSwift/OAuthSwift#563]
### Description: 

Can we use this on iOS version 9.3.5 with oAuth Swift Library on Swift 4.2?

### OAuth Version:
- [ x] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS : 9.3.5
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ x] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually

### Library version:
- [ ] head
- [ ] v2.1.0
- [ ] v2.0.0
- [ ] v1.4.1
- [ ] v1.2 (Swift 4.0)
- [x] ??

### Xcode version:
- [ ] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [ ] 10.x (Swift 4.1)
- [ ] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
Without trying I do not know. Just specify an old version and test
You can check old podspec version with associated ios version
https://github.com/CocoaPods/Specs/tree/9543734012238c33ea018af5a4381459c13f0916/Specs/b/c/6/OAuthSwift
