### ISSUE TITLE
The operation couldn’t be completed. (OAuthSwiftError error -11.)

### ISSUE THREAD

**Issue by dipendrapulse** [OAuthSwift/OAuthSwift#566]
### OAuth Version:
- [ ] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ x] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually

### Library version:
- [ ] head
- [ ] v2.1.0
- [x ] v2.0.0
- [ ] v1.4.1
- [ ] v1.2 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ ] 11.x (Swift 5.1)
- [ x] 10.x (Swift 5.0)
- [ ] 10.x (Swift 4.1)
- [ ] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

I am trying to integrate basecamp3 but getting the error.

           func createAuthRequest(){
        // create an instance and retain it
        oauthswift = OAuth2Swift(
            consumerKey:    clientID,
            consumerSecret: clientSecret,
            authorizeUrl:   authURL,
            accessTokenUrl: tokenURL,
            responseType:   "token"
            
        )
        
          oauthswift.authorizeURLHandler = internalWebViewController
        //oauthswift.authorizeURLHandler = SafariURLHandler(viewController: self, oauthSwift: oauthswift)
        
        let handle = oauthswift.authorize(
            withCallbackURL: URL(string: redirectURL)!,
            scope: "profile", state:"hjejklk") { result in
                switch result {
                case .success(let (credential, response, parameters)):
                    print(credential.oauthToken)
                // Do your request
                case .failure(let error):
                    print(error.localizedDescription)
                }
        }
    }

**Comment by phimage** [comment]
https://github.com/OAuthSwift/OAuthSwift/blob/master/Sources/OAuthSwiftError.swift#L59

use debuger and see in error not only the localizedDescription but the cause error, an URLError I think and you will now

**Comment by dipendrapulse** [comment]
It shows request error but i am not able to understand this. Please correct me if I am making something wrong

**Comment by phimage** [comment]
print? it is not debugger like I say...

or "switch" on the error enum

**Comment by dipendrapulse** [comment]
Sorry, I don't understand this. can you please help me to know how to  "switch" on the error enum.

**Comment by dipendrapulse** [comment]
I got the error, i changed my tokenurl to "https://launchpad.37signals.com/authorization/token?type=web_server" & it seems to be working now.
