### ISSUE TITLE
Is an OAuthSwift object Codable

### ISSUE THREAD

**Issue by IAINATTWATER** [OAuthSwift/OAuthSwift#570]
### Description: 

Question - I need to pass an OAuthswift object from the iOS App to the Watch Extension (using WatchConnectivity). Clearly such an object is not a Property List type so interested in passing as Data. Can the object be encoded/decoded? Doesn't look like it conforms. Or is there a convenience or helper function that can make a request after the tokens have been secured so that just the tokens can be passed to the watch. Thank you.

### OAuth Provider? (Twitter, Github, ..):
Twitter

### OAuth Version:
- [x] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [x] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually

### Library version:
- [ ] head
- [ ] v2.1.0
- [x] v2.0.0
- [ ] v1.4.1
- [ ] v1.2 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [ ] 10.x (Swift 4.1)
- [ ] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
please format correctly the message markdown

yes credential is `Codable`
a search show it 
https://github.com/OAuthSwift/OAuthSwift/search?q=Codable&unscoped_q=Codable
`oauthswift.client.credential`

**Comment by IAINATTWATER** [comment]
Thank you Eric. I managed to make that work.
