### ISSUE TITLE
Instagram Authentication after March 31, 2020

### ISSUE THREAD

**Issue by khambir** [OAuthSwift/OAuthSwift#577]
### Description:
> API Instagram Basic Display is not for authentication

It will be possible to authenticate users by Instagram, using OAuthSwift after March 31, 2020? 

### OAuth Provider:
Instagram

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS : 11
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually

### Library version:
- [ ] head
- [ ] v2.1.0
- [x] v2.0.0
- [ ] v1.4.1
- [ ] v1.2 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [ ] 10.x (Swift 4.1)
- [ ] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)
- [ ] objective c

**Comment by phimage** [comment]
you could connect, and get basic information
Using as authentication system is maybe an abuse, but its an instagram issue, not oauthswift
