### ISSUE TITLE
Dismissing bug with SFsafari

### ISSUE THREAD

**Issue by aakarshsasi** [OAuthSwift/OAuthSwift#580]
### Description:

 I am presenting a view controller modally and when a button is pressed on that SFSafariViewController is used to authenticate the user. I am calling the handle.dissmisscompletion to know if the dismiss is completed. The dismiss completion is excecuted correctly. But the problem is it does not dismiss the handler(Safari), but it dismisses the view controller I am using to present the signup button.
This is happening only when modalPresentationStyle = . overCurrentContext

### OAuth Version:
- [x ] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x ] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually

### Library version:
- [ ] head
- [ ] v2.1.0
- [x] v2.0.0
- [ ] v1.4.1
- [ ] v1.2 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x ] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [ ] 10.x (Swift 4.1)
- [ ] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by nonegu** [comment]
Following might be the problem here.

>  If you present several view controllers in succession, thus building a stack of presented view controllers, calling this method on a view controller lower in the stack dismisses its immediate child view controller and all view controllers above that child on the stack. When this happens, only the top-most view is dismissed in an animated fashion; any intermediate view controllers are simply removed from the stack. The top-most view is dismissed using its modal transition style, which may differ from the styles used by other view controllers lower in the stack.

Please refer to the documentation if this is the case.
https://developer.apple.com/documentation/uikit/uiviewcontroller/1621505-dismiss

**Comment by dnawarrior** [comment]
There is only one view controller present in the stack, on top of which the safari view controller is presented. It is happening only when using modalpresentationstyle as .overCurrentContext and not when using .currentContext or .fullScreen

**Comment by phimage** [comment]
in this situation you must debug to provide more information... or provide ready demo app with the issue


when you build your safari controller you pass a controller
this controller is used to present and dismiss the safari controller, not complicated to see it
https://github.com/OAuthSwift/OAuthSwift/blob/8c931c76de8b31d192bff12fe98caf7f626f6426/Sources/Handler/SafariURLHandler.swift#L44
You can customise the `UITransition`, make your own, etc.. there is a constructor with that

Then the dismiss is here
https://github.com/OAuthSwift/OAuthSwift/blob/8c931c76de8b31d192bff12fe98caf7f626f6426/Sources/Handler/SafariURLHandler.swift#L92
