### ISSUE TITLE
OAuth2Swift class is no longer able to be subclassed completely.

### ISSUE THREAD

**Issue by BrianDoig** [OAuthSwift/OAuthSwift#585]
### Description:
Due to a recent change in Swift, convenience initializers are no longer available to be called by subclasses, or users of that subclass.  Only default initializers may be called by a subclass.  Since OAuth2Swift default initializer does not allow you to set all parameters, subclasses are left calling only the default initializer and there is no way to implement all the init methods required.  This caused my OAuth2Swift subclass to stop compiling because the convenience initializers become private.

I tried wrapping OAuth2Swift in a class and forwarding all calls to it, but that broke when I needed to use a Safari controller because my wrapper could not be used with its init method because it is no longer a subclass of OAuth2Swift.

### OAuth Version:
- [ ] Version 1
- [X] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [x] Carthage
- [x] CocoaPods
- [x] Swift Package Manager
- [x] Manually

### Library version:
- [x] head
- [ ] v2.1.0
- [ ] v2.0.0
- [ ] v1.4.1
- [ ] v1.2 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [X] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [ ] 10.x (Swift 4.1)
- [ ] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
I replace by one `init` with default value fde7795 , more clean way to do it
@BrianDoig  Let me know if it work for you

ps: do not hesitate to PR for a change like that

**Comment by phimage** [comment]
feel free to comment or reopen if the issue is still there
