### ISSUE TITLE
Use of unresolved identifier 'OAuthSwiftOpenURLExternally' with OAuthSwift 2.1.0

### ISSUE THREAD

**Issue by jorgifumi** [OAuthSwift/OAuthSwift#589]
### Description:
I was using version 2.0.0 without problems, I have updated to 2.1.0 trying to get rid of three annoying warnings and then got this **Build Time** error in OAuth Swift URL Handler Type.swift, line 27:

`Use of unresolved identifier 'OAuthSwiftOpenURLExternally'`

I'm the only one with this issue? If I go back to 2.0.0 everything works again.

### OAuth Provider? (Twitter, Github, ..):
Custom ADFS server

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually

### Library version:
- [ ] head
- [x] v2.1.0
- [ ] v2.0.0
- [ ] v1.4.1
- [ ] v1.2 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ ] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [ ] 10.x (Swift 4.1)
- [ ] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [x] other: 11.4 (Swift 5.2)

- [ ] objective c

**Comment by phimage** [comment]
did you try head /master version?
because I have no issue with Xcode project

**Comment by phimage** [comment]
I create a release with latest code
