### ISSUE TITLE
tvOS project & @available attributes errors

### ISSUE THREAD

**Issue by max1mvs** [OAuthSwift/OAuthSwift#591]
### Description:
Building a blank tvOS project renders several issues regarding `@available` attributes referring to code that is only supported in tvOS 13.0 or newer:

**OAuthSwiftOpenURLExternally.swift, line 28:**

> 'open(_:options:completionHandler:)' is only available in tvOS 10.0 or newer

**String+OAuthSwift.swift, line 58-62:**

> 'scanUpToString' is only available in tvOS 13.0 or newer
> 'scanString' is only available in tvOS 13.0 or newer

**UIApplication+OAuthSwift.swift**
_Line 22 + 27:_

> 'UIWindowScene' is only available in tvOS 13.0 or newer

_Line 23:_

> 'connectedScenes' is only available in tvOS 13.0 or newer
> 'UIWindowScene' is only available in tvOS 13.0 or newer

Also, I get three warnings on 

- Collection+OAuthSwift.dia
- OAuthSwiftURLHandlerType.dia
- SHA1.dia

saying: 

> Could not read serialized diagnostics file: Invalid File: Invalid diagnostics signature

### OAuth Provider? (Twitter, Github, ..):
N/A

### OAuth Version:
- [ ] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [ ] iOS :
- [ ] OSX :
- [x] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [x] Swift Package Manager
- [ ] Manually

### Library version:
- [ ] head
- [x] v2.1.0
- [ ] v2.0.0
- [ ] v1.4.1
- [ ] v1.2 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [ ] 10.x (Swift 4.1)
- [ ] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
The minimum version is not very well specified. Even for iOS, I will do not take much time to make it compatible for version lower than 13.0
I update the code for instance with scanUpToString to fix Xcode warnings and use new api
So maybe an old version could work (or not if not tested by anybody)

**Comment by phimage** [comment]
I update the head code and add where is possible tvOS version checking
It seems to compile with tvOS 9
@max1mvs  let me know if it works and close the issue , thanks in advance

**Comment by max1mvs** [comment]
I don't seem to see the changes in version 2.1.1..?

**Comment by max1mvs** [comment]
Ok, figured out how to implement the latest build. All errors are gone now. Thank you!
