### ISSUE TITLE
SwiftUI Webview authorizeURLHandler

### ISSUE THREAD

**Issue by Veeit** [OAuthSwift/OAuthSwift#594]
### Description:

My SwiftUI application is working fine with oAuthSwift, the only problem is I use Safari for the login handler. But to get the app to the store I need to use a WebView inside my application, the problem that I have now is that I don't know how to create a authorizeURLHandler that opens a SwiftUI sheet with the WebView inside. 

### OAuth Provider? (Twitter, Github, ..):
Makerlog

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [x] Swift Package Manager
- [ ] Manually

### Library version:
- [x] head
- [ ] v2.1.0
- [ ] v2.0.0
- [ ] v1.4.1
- [ ] v1.2 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [ ] 10.x (Swift 4.1)
- [ ] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
good question,  never tested
did you try other handler like SafariURLHandler or ASWebAuthenticationURLHandler?

**Comment by Veeit** [comment]
I didn't I just looked at SafariURLHandler but I need to add a Controller and I don't have one. I have created a function inside my ObservableObject for the login. 
The big problem is I need to warp the WebView (or what ever the webpage displays) inside a UIViewControllerRepresentable to use it with swiftUI.

**Comment by Veeit** [comment]
https://github.com/Veeit/makerslog-App/blob/release-v1/Shared/View%20Model/Api/LoginData.swift

line 258 is the login function, if you are interested in the code :)

**Comment by Veeit** [comment]
```
 var root: UIViewController
        oauthswift.authorizeURLHandler = SafariURLHandler(viewController: root, oauthSwift: oauthswift)

        if let windowScene = scene as? UIWindowScene {
            let window = UIWindow(windowScene: windowScene)
            window.rootViewController = root
            self.window = window
            window.makeKeyAndVisible()
        }
```

Got it working :) I need to configure the SafariURLHandler like this inside the SceneDelegate, actually it took me a while to get to thins solution but that is simple.

**Comment by phimage** [comment]
thanks for the code it could help other people
