### ISSUE TITLE
Bug: Authorization Header is ignored

### ISSUE THREAD

**Issue by BJAdeGraaf** [OAuthSwift/OAuthSwift#595]
### Description:
The custom header is getting ignored when authorizing. It seems it uses the default header `[:]`.
For instance, I can't request "full access" with `headers: ["Access": "Full"]`, because it doesn't end up in the authorization URL.

### OAuth Provider? (Twitter, Github, ..): 
SmugMug

### OAuth Version:
- [x] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [ ] iOS :
- [x] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [x] Swift Package Manager
- [ ] Manually

### Library version:
- [x] head
- [ ] v2.1.0
- [ ] v2.0.0
- [ ] v1.4.1
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 11.4 (Swift 5.2)
- [ ] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
please debug and provide more information
https://github.com/OAuthSwift/OAuthSwift/blob/master/Sources/OAuth1Swift.swift#L99
https://github.com/OAuthSwift/OAuthSwift/blob/master/Sources/OAuth1Swift.swift#L160
https://github.com/OAuthSwift/OAuthSwift/blob/master/Sources/OAuth1Swift.swift#L193
