### ISSUE TITLE
Is discord possible?

### ISSUE THREAD

**Issue by jonahbrandwagt** [OAuthSwift/OAuthSwift#597]
### Description:
Is it possible to OAuth with discord? I am looking for a way but I have no idea how to do it. I want that people can login with their discord account so the app can check if they are in a specific server.
### OAuth Provider? (Twitter, Github, ..):
Discord?

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually

### Library version:
- [ ] head
- [ ] v2.1.0
- [x] v2.0.0
- [ ] v1.4.1
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 11.4 (Swift 5.2)
- [ ] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
yes is is
https://discord.com/developers/docs/topics/oauth2
