### ISSUE TITLE
unable to distinguish canceled logins from errors when using SFAuthenticationSession/ASWebAuthenticationSession

### ISSUE THREAD

**Issue by eastsss** [OAuthSwift/OAuthSwift#600]
### Description:
Right now there is no way to distinguish canceled logins from any other errors when using ASWebAuthenticationURLHandler or SFAuthenticationURLHandler. 
Proposed solution: https://github.com/OAuthSwift/OAuthSwift/pull/599

### OAuth Version:
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :

### Installation method:
- [x] CocoaPods

### Library version:
- [ ] v2.1.0

### Xcode version:
- [x] 11.4 (Swift 5.2)

**Comment by phimage** [comment]
thanks
