### ISSUE TITLE
Adding project with SPM adds additional libraries? 

### ISSUE THREAD

**Issue by pepejeria** [OAuthSwift/OAuthSwift#607]
Adding the library to a project using SPM also adds Kanna, Erik and swifter as dependencies. These libraries don't seem to be added when using Cocoapods. 

Can you please clarify this? 
Thank you.

**Comment by phimage** [comment]
as you can see its only for testig
https://github.com/OAuthSwift/OAuthSwift/blob/master/Package.swift#L37
yes its downloaded but not in your app runtime

you can find similar behaviour with some  package that use Quick Nimble to test
in javascript there is dev dependencies for instance
