### ISSUE TITLE
Release version 2.1.2 to CocoaPods

### ISSUE THREAD

**Issue by moberwasserlechner** [OAuthSwift/OAuthSwift#615]
### Description:

Would it be possible to release the latest bugfix release to *CocoaPods.org*?

Currently only version 2.1.0 can be obtained from there. (see https://cocoapods.org/pods/OAuthSwift) 

Thx & BR, Michael

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually

**Comment by phimage** [comment]
I will do when I have some time, If I can I prefer to make some test before releasing. 
You could use HEAD code in podfile

**Comment by ghowen** [comment]
@phimage Nice one! I always seem to forget this. Just on a side note: `:head` is deprecated and has been replaced with `:git`. So to get the master branch one would add

`  pod 'OAuthSwift', :git => 'https://github.com/OAuthSwift/OAuthSwift.git'
`

to one's `podfile`. 

Anyways, thanks for the library. OAuth1ing to OpenStreetMap is a breeze with this 👍

**Comment by moberwasserlechner** [comment]
@ghowen @phimage Thank you both I didn't know that this was possible with cocoapods.

**Comment by vgritsenko** [comment]
While it is possible to use `:git => ... branch => ` with CocoaPods in the Podfile, the same is not possible for other pods which declare OAuthSwift as a dependency. As a result, any such pod would fail validation and it would not be possible to release such pod automatically:

```
pod repo push <repo> MyAwesomePod.podspec --<parameters>
```

In our case we are waiting for the 2.1.3 release which brings in addition for token refresh. Would it be possible to release 2.1.3 sooner?

https://github.com/OAuthSwift/OAuthSwift/pull/620

**Comment by macbellingrath** [comment]
@phimage any update on the release?

**Comment by macbellingrath** [comment]
@phimage would a release be considered for sponsors?

**Comment by phatblat** [comment]
@macbellingrath 2.1.2 was release a couple days ago
