### ISSUE TITLE
invalid_redirect_uri With dribbble

### ISSUE THREAD

**Issue by huainanzi** [OAuthSwift/OAuthSwift#619]
### OAuth Version:
- [ ] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually

### Library version:
- [ ] head
- [ ] v2.1.0
- [ ] v2.0.0
- [ ] v1.4.1
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ ] 11.4 (Swift 5.2)
- [ ] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

I get ["error_description": "The+requested+redirect+uri+is+malformed+or+doesn%27t+match+client+redirect+URI.", "error": "invalid_redirect_uri"]
serverError[invalid_redirect_uri] With dribbble

**Comment by phimage** [comment]
not enough information, do not take time to fill template
