### ISSUE TITLE
Facing issues when using OAuth2 PKCE like shown in readme

### ISSUE THREAD

**Issue by flowinho** [OAuthSwift/OAuthSwift#622]
### Description:
Hey there! 

#### The circumstances

I'd like to use the OAuthSwift framework with a custom system based on Amazon KeyCloak. However i'm facing issue upon initialization of the framework. The Readme describes the following method:

```swift
// create an instance and retain it
oauthswift = OAuth2Swift(
   ...
)
oauthswift.accessTokenBasicAuthentification = true

let codeVerifier = base64url("abcd...") // line with error
let codeChallenge = codeChallenge(for: codeVerifier) // line with error
 
let handle = oauthswift.authorize( // line with error
    withCallbackURL: "myApp://callback/",
    scope: "requestedScope", 
    state:"State01",
    codeChallenge: codeChallenge,
    codeChallengeMethod: "S256",
    codeVerifier: codeVerifier) { result in
    switch result {
        ...
     }
)
```
#### The problem

My compiler tells me that `base64url`, `codeChallenge` are unknown types and that `oauthswift` does not have a member `authorize`. 

Any ideas on how to solve this? The app-project up until is very basic, no big changes have been made to the project-settings and third-party tools that edit the project (e.g. Cocoapods) are not present.

Looking forward to receiving your help. <3

Greetings from Southern Germany

### OAuth Provider? (Twitter, Github, ..):
- Custom (but does not matter at this point)

### OAuth Version:
- [ ] Version 1
- [X] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [ ] Swift Package Manager
- [X] Manually

### Library version:
- [X] head
- [ ] v2.1.0
- [ ] v2.0.0
- [ ] v1.4.1
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [X] 11.5
- [ ] 11.4 (Swift 5.2)
- [ ] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by kdembler** [comment]
Seems both `base64url` and `codeChallenge` are stubs for your own implementation. This article https://auth0.com/docs/flows/call-your-api-using-the-authorization-code-flow-with-pkce has examples of generating both `codeVerifier` and `codeChallenge` in Swift

**Comment by lveecode** [comment]
> that oauthswift does not have a member `authorize`

OAuthSwift itself does not, but OAuth2Swift does. If it's an instance variable, make sure oauthswift is defined as OAuth2Swift (not OAuthSwift). 
Alternatively, if it has to be a generic OAuthSwift,

```
let oauthswift = OAuth2Swift( [...] )

self.oauthswift = oauthswift

let handle = oauthswift.authorize( [...] ) // no error anymore
```

**Comment by MrWoWander** [comment]
I wrote and sent to the PR #647 generator random code verifier and code challenge
