### ISSUE TITLE
How can I use SafariURLHandler in SwiftUI App Lifecycle?

### ISSUE THREAD

**Issue by kkk669** [OAuthSwift/OAuthSwift#626]
### Description:
The [README.md](https://github.com/OAuthSwift/OAuthSwift#use-the-sfsafariviewcontroller-ios9) describes how to use the `SFSafariViewController`. However, how can I use it in SwiftUI App Lifecycle like the below?

```swift
@main
struct FooApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```

### OAuth Provider? (Twitter, Github, ..):
Any

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Xcode version:
- [x] other: 12.x (Swift 5.3)

**Comment by phimage** [comment]
not without some adaptation 

you must look at SFSafariViewController and swiftui 

I never tested it but I think you must implement [UIViewControllerRepresentable](https://developer.apple.com/documentation/swiftui/uiviewcontrollerrepresentable) and provide the controller used with ` makeUIViewController(`
maybe SafariURLHandler could implement it or add another object to encapsulate  (do not hesitate to share if you have a solution and to close this issue)

**Comment by kkk669** [comment]
Thanks you @phimage.

`SafariURLHandler(present:,dismiss:,oauthSwift:)` may be what I was looking for. If it works, I'll share it and close this issue.

**Comment by kkk669** [comment]
BTW, I gave up using OAuthSwift with SwiftUI's App Lifecycle.

**Comment by kkk669** [comment]
I succeeded in using OAuthSwift with SwiftUI App Lifecycle. I gave up using `SafariURLHandler`, but [`ASWebAuthenticationURLHandler`](https://github.com/OAuthSwift/OAuthSwift/blob/master/Sources/Handler/ASWebAuthenticationURLHandler.swift) and [`ASWebAuthenticationSessionURLHandler`](https://github.com/raxityo/OAuthSwiftAuthenticationServices/blob/1.0.0/Sources/OAuthSwiftAuthenticationServices/ASWebAuthenticationSessionURLHandler.swift) of #621 can be used with SwiftUI App Lifecyle.

Here is an example.

```swift
@main
struct DemoApp {}

extension DemoApp: App {
    var body: some Scene {
        DemoScene()
    }
}

struct DemoScene {
    init() {
        <SingletonDataManager>.oauthSwift.authorizeURLHandler = ASWebAuthenticationSessionURLHandler(
            callbackURLScheme: <CallbackURLScheme>,
            presentationAnchor: nil  // If the app doesn't support for multiple windows, it doesn't matter to use nil.
        )
    }
}

extension LandScanScene: Scene {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```
