### ISSUE TITLE
Issues with Oauth 1.0

### ISSUE THREAD

**Issue by cyrussinc** [OAuthSwift/OAuthSwift#627]
### OAuth Version:
- [x ] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [x ] Swift Package Manager
- [ ] Manually

### Library version:
- [ ] head
- [x ] v2.1.0
- [ ] v2.0.0
- [ ] v1.4.1
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x ] 11.4 (Swift 5.2)
- [ ] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

I'm running into problems when trying to use the Oauth1Swift instance to do the authorization process; when my code runs I get the error:

The operation couldn’t be completed. (OAuthSwiftError error -6.) <-according to the source code this is an "encoding error"

When I use the Oauth2Swift instance, I don't get this error and the login flow appears smoothly as it should, but the problem is that the API I'm using is on Oauth 1.0 so I don't get redirected once the user authorizes the app.

Is there any way I can either fix the encoding error (or alternatively use the Oauth2Swift instance and get redirectURL to work)?

Here's my code:

   let oauthSwift = OAuth1Swift(
            consumerKey:    Constants.consumerKey,
        consumerSecret: Constants.consumerSecret, requestTokenUrl: "",
            //requestTokenUrl: "",
          authorizeUrl:   Constants.authURL,
        accessTokenUrl: ""
           )
        oauthSwift.authorizeURLHandler = SafariURLHandler(viewController: self, oauthSwift: oauthSwift)

        guard let rwURL = URL(string: Constants.redirectURI) else{return}
        
        oauthSwift.authorize(withCallbackURL: rwURL) { (result) in
            switch result{
            case.success(let (credential, response, parameters)):
                print(credential.oauthToken)
                print(credential.oauthTokenSecret)
            case.failure(let error):
                print(error.localizedDescription)
            }
        }

**Comment by phimage** [comment]
not enough info, break point on OAuthSwift code when encoding
bad markdown usage in description
