### ISSUE TITLE
OAuth provider returns 403 instead of 401 for expired token

### ISSUE THREAD

**Issue by fmoraes74** [OAuthSwift/OAuthSwift#629]
### Description:

The HSReplay OAuth provider is returning 403 instead of 401 for an expired token. This means that automatic token renewal is not working as the code only checks for 401 and 400 errors in the NSError extension. Is there a way to work around it without having to explicitly try to refresh the token in case of an unexpected error?

### OAuth Provider? (Twitter, Github, ..):

HSReplay.net

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [ ] iOS :
- [x] OSX : 10.15.7
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [x] Carthage
- [ ] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually

### Library version:
- [ ] head
- [ ] v2.1.0
- [ ] v2.0.0
- [x] v1.4.1
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ ] 11.4 (Swift 5.2)
- [ ] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [x] other: 12.1

- [ ] objective c

**Comment by phimage** [comment]
add a new case in code (PR)
https://github.com/OAuthSwift/OAuthSwift/blob/master/Sources/NSError%2BOAuthSwift.swift#L70
