### ISSUE TITLE
Retain error -10 only when assigning authorizeURLHandler?

### ISSUE THREAD

**Issue by serenapascual** [OAuthSwift/OAuthSwift#632]
### Description:
When I do not set authorizeURLHandler and allow the URL to open in an external browser, the authorization is successful. However, once I try to use SafariURLHandler, I get a retain error:
`The operation couldn’t be completed. (OAuthSwiftError error -10.)` 

Here is my code:

```
class AccountViewController: UIViewController {
	
    var oauthswift: OAuth2Swift!
	
    override func viewDidLoad() {
        super.viewDidLoad()

		let loginButton: UIButton = {
                    // . . . 
                }		
	}
    
	@objc func loginButtonAction(_ sender:UIButton!) {
		doOAuthReddit()
	}
	
}

extension AccountViewController {
	
	func doOAuthReddit() {
		self.oauthswift = OAuth2Swift(
			consumerKey: "",
			consumerSecret: "",
			authorizeUrl: "https://www.reddit.com/api/v1/authorize.compact",
			accessTokenUrl: "https://www.reddit.com/api/v1/access_token",
			responseType: "code"
		)
				
		oauthswift.accessTokenBasicAuthentification = true

                // Success if the line below is commented out 
		oauthswift.authorizeURLHandler = SafariURLHandler(viewController: self, oauthSwift: oauthswift)
		
		let _ = oauthswift.authorize(withCallbackURL: "oauth://oauth-callback", scope: "read", state: "aStateOfFearAndConfusionOhDear") { result in
				switch result {
				case .success(let (credential, _, _)):
					print(credential.oauthToken)
				case .failure(let error):
					print(error.localizedDescription)
				}
		}
	}
	
}
```

I have also tried creating a property for the SafariURLHandler instance and storing that there, but doing so did not help.

### OAuth Provider? (Twitter, Github, ..):
Reddit

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS : 14.1
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [ ] Swift Package Manager
- [x] Manually

### Library version:
- [x] head
- [ ] v2.1.0
- [ ] v2.0.0
- [ ] v1.4.1
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ ] 11.4 (Swift 5.2)
- [ ] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [x] other: 12.1 (Swift 5.3)

- [ ] objective c

**Comment by phimage** [comment]
it's seems weird
do you have dismissed AccountViewController ?

if not we will try to force "retain"

could you try to assign to a class variable the return of authorise instead of `let _ = `
or reference self in callback, for instance by extracting it to afunction

```swift     
func log() {
                       switch result {
				case .success(let (credential, _, _)):
					print(credential.oauthToken)
				case .failure(let error):
					print(error.localizedDescription)
			}
}
```
and call` self.log()`in callback (yes it is crappy because you must use [weak self] to not retain ad cause memory leak)

**Comment by serenapascual** [comment]
Hi Eric, thank you for your prompt and helpful response.


> do you have dismissed AccountViewController ?

No dismissal.

> could you try to assign to a class variable the return of authorise instead of `let _ = `

I tried this and the same error occurs.

> or reference self in callback, for instance by extracting it to afunction
> 
> ```swift
> func log() {
>                        switch result {
> 				case .success(let (credential, _, _)):
> 					print(credential.oauthToken)
> 				case .failure(let error):
> 					print(error.localizedDescription)
> 			}
> }
> ```
> 
> and call` self.log()`in callback (yes it is crappy because you must use [weak self] to not retain ad cause memory leak)

It took me a while to figure this out (sorry - new to Swift), and I think it works! At least, that is when I don't use [weak self], which causes self to evaluate to nil during callback. Do you have any tips?

This is what I've added that leads to a successful result.

```swift
var log: ((Result<OAuthSwift.TokenSuccess, OAuthSwiftError>) -> Void) = { result in
		switch result {
		 case .success(let (credential, _, _)):
			 print(credential.oauthToken)
		 case .failure(let error):
			 print(error.localizedDescription)
		}
}

// . . .

let _ = oauthswift.authorize(withCallbackURL: "oauth://oauth-callback", scope: "read", state: "aStateOfFearAndConfusionOhDear") { result in
			self.log(result)
```

**Comment by phimage** [comment]
Close Stale Issue
