### ISSUE TITLE
Adding timeout interval to "makeRequest" methods

### ISSUE THREAD

**Issue by rentateam-mashatrubina** [OAuthSwift/OAuthSwift#635]
### Description:
Hi!

Could you please add the possibility to set **timeout interval** right inside one of the `makeRequest` methods?
For now it can be done in `OAuthSwiftClient.makeRequest(_: URLRequest)` only, as I may see. I find this not that convenient as I need to do some preparations to `URLRequest` instance before passing it to `makeRequest` (add parameters, httpMethod and so on). While all of that could be easily done with `makeRequest` method, if it could accept time interval parameter as well.

P.S. Thank you very much for your work! Your framework saves me tons of hours!

### OAuth Provider? (Twitter, Github, ..):
Auth using grant type "password"

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually

### Library version:
- [ ] head
- [x] v2.1.0
- [ ] v2.0.0
- [ ] v1.4.1
- [ ] other: (Please fill in the version you are using.)

**Comment by phimage** [comment]
timeout is generally managed by session manager, there is `URLSessionFactory` and the configuration to create the session
