### ISSUE TITLE
Confused about how credential should be persisted and repopulated.

### ISSUE THREAD

**Issue by AshRobinson** [OAuthSwift/OAuthSwift#642]
### Description:

I have the OAuth mechanism working end to end, however I'm confused about how the credentials should be persisted. I'm using NSKeyedArchiver to covert the credentials to data which I'm then storing in the keychain in response to the application being terminated. On re-launch I'm checking if the keychain contains any credentials, if so I'm using NSKeyedUnarchiver to reconstruct the credential object but at this point I'm unable to set the credentials back on the SwiftOAuth Client object as the property is get only? 

I want to ensure future calls to startAuthorizedRequest use my persisted credentials rather than asking the user to log in again each time the application is killed, what's the correct way to handle this?

### OAuth Version:
- [x] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually

### Library version:
- [ ] head
- [x] v2.1.0
- [ ] v2.0.0
- [ ] v1.4.1
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ ] 11.4 (Swift 5.2)
- [ ] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [x] other: (Please fill in the version you are using.) - 12.1

- [ ] objective c

**Comment by phimage** [comment]
https://github.com/OAuthSwift/OAuthSwift/wiki/Store-credential
