### ISSUE TITLE
Allow customization of OAuth1 authorize url params

### ISSUE THREAD

**Issue by daironmichel** [OAuthSwift/OAuthSwift#644]
### Description:
By default OAuth1Swift.authorize() function generates an authorize url with params `?oath_token=oauthRequestToken`.
However ETrade's authorize url params must be `?key=consumerKey&token=oauthRequestToken` or the authorization will fail.

### OAuth Provider? (Twitter, Github, ..):
ETrade (https://api.etrade.com)

### OAuth Version:
- [x] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [x] Swift Package Manager
- [ ] Manually

### Library version:
- [x] head
- [ ] v2.1.0
- [ ] v2.0.0
- [ ] v1.4.1
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 11.4 (Swift 5.2)
- [ ] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment]
you could provide a PR with a boolean to configure like that

for instance there is here some
https://github.com/OAuthSwift/OAuthSwift/blob/master/Sources/OAuth1Swift.swift#L15
