### ISSUE TITLE
RequestError for renewAccessToken

### ISSUE THREAD

**Issue by pandapancake** [OAuthSwift/OAuthSwift#648]
### Description:
I'm not sure what to put in the parameters, header .  Read a lot of different questions but still can't figure it out or any good example. Thank you!

```
if tokenExpire == true {
  auth = OAuth2Swift(consumerKey: **********,
                                     consumerSecret: ***********,
                                     authorizeUrl: "",
                                     accessTokenUrl: tokenURL,
                                     responseType: "")
   auth?.renewAccessToken(withRefreshToken: oauth.oauthRefreshToken,  parameters: nil, headers: nil, completionHandler: { response in
      //do something...
    })
}
```

### OAuth Version:
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :

### Installation method:
- [x] CocoaPods

### Library version:
- [x] head

### Xcode version:
- [x] 11.4 (Swift 5.2)

**Comment by phimage** [comment]
nothing, add only if you know and need it, there is default value to nil already set `headers: OAuthSwift.Headers? = nil,`
