### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by Nef10** [OAuthSwift/OAuthSwift#656]
I just wanted to follow up on the comment in #649 on the next release, given that the ticket was closed. 

@phatblat may I ask you for an update on the release plan?

The problem for me is that due to limitation of the Swift Package Manger, I see the warning which were introduced by Swift 5.4 and fixed in #650 in my packages. As I configure my build to treat warnings as errors, the build is failing now.

**Comment by phimage** [comment]
in Swift Package Manger we could use temporary head/master branch code, isn't?

here I make a plan before release https://github.com/OAuthSwift/OAuthSwift/issues/649#issuecomment-828761986
to provide some info on what I see on change done since last tag/release
but phatblat could release when he want

**Comment by phatblat** [comment]
Sorry for the delay on this. Last week was crazy. I will work on getting 2.1.3 out today.

**Comment by phatblat** [comment]
FYI, @Nef10 you can use code that's in master branch before it's released using:

```swift
    dependencies: [
        .package(
            url: "https://github.com/OAuthSwift/OAuthSwift.git",
            .branch("master")
        ),
    ],
```

However, this can produce different behavior over time as new PRs are merged into master.

**Comment by Nef10** [comment]
Hey, no worries, I just wanted to ask what the status is. :)

I know I can specify a branch or a specific commit in SPM, however this only works in the end consumer project. When you include a library via a branch or commit in another library, you won't be able to consume this library by specifying a version:

> Note that packages which use branch-based dependency requirements
 cannot be depended-upon by packages which use version-based dependency
 requirements; you should remove branch-based dependency requirements
 before publishing a version of your package.

 from  https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html#package-dependency-requirement

To fix this one would need to use branch or commit dependency requirements in every library up to the last consumer.

**Comment by phimage** [comment]
I just check CI and launch locally
```
%  xcodebuild -scheme "OAuthSwift" | xcpretty
▸ Processing Info.plist
▸ Compiling OAuth1Swift.swift
▸ Compiling OAuth2Swift.swift

❌  /Users/emarchand/Documents/GitHub/OAuthSwift/Sources/OAuth2Swift.swift:145:31: cannot find 'SFAuthenticationURLHandler' in scope

                              SFAuthenticationURLHandler.isCancelledError(domain: domain, code: code) {
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~


** BUILD FAILED **
```
the code is a little crappy with all version and case, I suppose its issue is with target macCatalyst, in fact no sdk is passed in argument of build

I think in CI I will add compile on iOS and one one Mac catalyst

**Comment by phatblat** [comment]
Version [2.2.0](https://github.com/OAuthSwift/OAuthSwift/releases/tag/2.2.0) is live now 🎉

**Comment by phimage** [comment]
thank you very much for the work done

**Comment by Nef10** [comment]
Thanks!
