### ISSUE TITLE
/Package.swift has no Package.swift manifest for version 0.6.0 in https://github.com/OAuthSwift/OAuthSwift

### ISSUE THREAD

**Issue by ZhannySunny** [OAuthSwift/OAuthSwift#686]
I'm getting this error "**Package.swift has no Package.swift manifest for version 0.6.0 in https://github.com/OAuthSwift/OAuthSwift**" when installing OAuthSwift with SPM and Xcode 13.1. Could you please how can I fix this error and successfully install this library?

**Comment by phimage** [comment]
for 0.6.0, some years ago before SwiftPM exists? use a more recent version compatible with Xcode 13.1 please
and do not remove issue template next time
