### ISSUE TITLE
Cannot redirect to the app after autosubmit credentials

### ISSUE THREAD

**Issue by denis-huma** [OAuthSwift/OAuthSwift#705]
### Description:
Hello guys, please help with my issue. I'm using OAuthSwift and universal links. It is related to the FITBIT credential page. Once user have opened Fitbit login page (via SFSafariController) and fill it automatically (autosubmit email/password - via Face ID) he cannot be redirected to the app again but rather got an error message on a web page. But when user inserts credentials manually he then able to be redirected to the app without any errors. Any suggestions how can I fix this problem? Thanks.

### OAuth Provider?: 
Fitbit

### OAuth Version:

- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually

### Library version:
- [ ] head
- [ ] v2.1.0
- [ ] v2.0.0
- [ ] v1.4.1
- [x] other: (pod 'OAuthSwift', :git => 'https://github.com/OAuthSwift/OAuthSwift.git')

### Xcode version:
- [ ] 11.4 (Swift 5.2)
- [ ] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [x] other: (14.1)

- [ ] objective c

**Comment by phimage** [comment]
Fitbit is only https scheme or any app scheme?

maybe only https so the page where it is redirected is your server?
if yes, it's your server that return the error and do not handle correctly the request, the server must do the job to redirect to an url that must be handled by the mobile app (url scheme, or universal links, ...)

**Comment by denis-huma** [comment]
> Fitbit is only https scheme or any app scheme?
> 
> maybe only https so the page where it is redirected is your server? if yes, it's your server that return the error and do not handle correctly the request, the server must do the job to redirect to an url that must be handled by the mobile app (url scheme, or universal links, ...)

### Fitbit is only https scheme or any app scheme? - yes
the page where it is redirected is your server? - yes

The thing is if I insert credentials manually - it works fine, but when I use FaceID to automatically fill saved credentials - I receive this error.

**Comment by denis-huma** [comment]
@phimage Here is the response when I got 404 (FaceID case - automatic credentials fill), and correct response when I entered credentials manually. 
<img width="1352" alt="5 1" src="https://user-images.githubusercontent.com/85576894/205596406-bd941553-c0c0-492a-b734-d1012540d961.png">
<img width="1352" alt="5" src="https://user-images.githubusercontent.com/85576894/205596447-63ca1a37-ac4d-4dba-81e4-73cb4a5d720f.png">

**Comment by phimage** [comment]
I have no clue about your server code 
404 say that the page do not exists on your server, here the root page for a GET request

Maybe you are expecting an other path on your server like https://xxxx.yyy/callback/?code=....
did you make the code yourself ?
