### ISSUE TITLE
the closure for the authorize function callback is not being executed at all.

### ISSUE THREAD

**Issue by Monkey-X-Byte** [OAuthSwift/OAuthSwift#706]
### Description:

During my usage of OAuthSwift 2.2.0, the closure for the authorize function callback is not being executed at all.

`let oauth = OAuth2Swift(consumerKey: appId, consumerSecret: appSecret, authorizeUrl: authorizeUrl, accessTokenUrl: accessTokenUrl, responseType: responseType, contentType: nil)
        oauth.allowMissingStateCheck = true
        #if os(iOS)
        oauth.authorizeURLHandler = SafariURLHandler(viewController: viewController, oauthSwift: oauth)
        #endif
        self.oauth = oauth
        _ = oauth.authorize(withCallbackURL: URL(string: callbackUrl), scope: scope, state: state, parameters: authorizeParameters, completionHandler: { result in
            switch result {
            case .success(let token):
                completion(.success(token))
            case .failure(let error):
                completion(.failure(error))
            }
        })`

### OAuth Version:
- [ ] Version 1
- [ x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x ] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually

### Library version:
- [ ] head
- [ x] v2.2.0
- [ ] v2.0.0
- [ ] v1.4.1
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ ] 11.4 (Swift 5.2)
- [ ] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [x ] other: (XCode14.3.)

- [ ] objective c

**Comment by phimage** [comment]
let oauth = OAuth2Swift

retain it in memory

**Comment by Monkey-X-Byte** [comment]
> let oauth = OAuth2Swift
> 
> retain it in memory

You may not have seen that I mentioned the issue of retaining in memory. I'm encountering this issue while using OAuth2Swift in a SwiftUI application
