### ISSUE TITLE
Does not work with Zotero Oauth

### ISSUE THREAD

**Issue by hassanzadeh** [OAuthSwift/OAuthSwift#712]
### Description:
Tried with Zotero (Oauth v1) but failed with error:  The operation couldn’t be completed. (OAuthSwiftError error -10.)

### OAuth Provider? (Twitter, Github, ..):
Zotero: https://www.zotero.org/support/dev/web_api/v2/oauth

### OAuth Version:
Version 1

### OS (Please fill the version) :
- macOS
- 
### Installation method:
- [ ] Swift Package Manager

### Library version:
Latest version

### Xcode version:
Xcode v15

Swift

**Comment by hassanzadeh** [comment]
Here is my code:
`func authenticateWithZotero() {
                        let oauthswift = OAuth1Swift(
                            consumerKey:    "xxx",
                            consumerSecret: "zzzz",
                            requestTokenUrl: "https://www.zotero.org/oauth/request",
                            authorizeUrl:    "https://www.zotero.org/oauth/authorize",
                            accessTokenUrl:  "https://www.zotero.org/oauth/access"
                        )
                        
                        oauthswift.authorize(
                            withCallbackURL: URL(string: "scholarsync://zotero")!) { result in
                                switch result {
                                case .success(let (credential, _, _)):
                                    print(credential.oauthToken)
                                    // Save these tokens; they are needed for accessing the API
                                case .failure(let error):
                                    print(error.localizedDescription)
                                }
                            }
                    }`

**Comment by phimage** [comment]
please use correctly markdown

`let oauthswift = OAuth1Swift` is bad, you do not follow readme and demo code
that cause
-10 > https://github.com/OAuthSwift/OAuthSwift/blob/master/Sources/OAuthSwiftError.swift#L58

**Comment by hassanzadeh** [comment]
Thanks for your response,
I tested it, it gives me the oauth_token but Not the access_token, is there a specific function I should call to get the access token?
